using System.Security.Cryptography;
using System.Text;
using GnOuGo.Assets.Bears;

var builder = WebApplication.CreateSlimBuilder(args);

var app = builder.Build();

app.MapMethods("/", ["GET"], (RequestDelegate)(async context =>
{
    var options = CreateRandomBearOptions(TryGetSeed(context));
    var html = RenderAnimationGallery(options);

    context.Response.Headers.CacheControl = "no-store";
    context.Response.ContentType = "text/html; charset=utf-8";
    await context.Response.WriteAsync(html);
}));

app.MapMethods("/bear.svg", ["GET"], (RequestDelegate)(async context =>
{
    if (!TryGetAnimation(context, out var animation))
    {
        context.Response.StatusCode = StatusCodes.Status400BadRequest;
        context.Response.ContentType = "text/plain; charset=utf-8";
        await context.Response.WriteAsync(
            $"Unknown animation. Supported values: {string.Join(", ", Enum.GetNames<GnouGnouBearAnimation>())}.");
        return;
    }

    var options = CreateRandomBearOptions(TryGetSeed(context)) with
    {
        Animation = animation,
        Size = 512,
        SvgIdPrefix = "standalone-preview",
        Title = $"{animation} GnOuGo animation",
        Description = $"Standalone {animation} animation generated by GnOuGo.Assets.Bears."
    };
    var svg = GnouGnouBearSvgGenerator.Generate(options);

    context.Response.Headers.CacheControl = "no-store";
    context.Response.ContentType = "image/svg+xml; charset=utf-8";
    await context.Response.WriteAsync(svg);
}));

app.Run();

static GnouGnouBearOptions CreateRandomBearOptions(int? seed = null)
{
    var actualSeed = seed ?? RandomNumberGenerator.GetInt32(1, int.MaxValue);
    var random = new Random(actualSeed);

    return new GnouGnouBearOptions
    {
        Seed = actualSeed,
        Role = Pick<GnouGnouBearRole>(random),
        Emotion = Pick<GnouGnouBearEmotion>(random),
        Accessory = Pick<GnouGnouBearAccessory>(random),
        State = Pick<GnouGnouBearState>(random),
        Theme = Pick<GnouGnouBearTheme>(random),
        FurPalette = Pick<GnouGnouBearFurPalette>(random),
        EyeStyle = Pick<GnouGnouBearEyeStyle>(random),
        HasHeadphones = RandomBool(random, percentTrue: 55),
        HasBowTie = RandomBool(random, percentTrue: 55),
        HasBeard = RandomBool(random, percentTrue: 30),
        Size = 320,
        Title = "GnouGnou animation preview",
        Description = $"Deterministic GnouGnou SVG mascot generated from seed {actualSeed}."
    };
}

static T Pick<T>(Random random)
    where T : struct, Enum
{
    var values = Enum.GetValues<T>();
    return values[random.Next(values.Length)];
}

static bool RandomBool(Random random, int percentTrue)
{
    return random.Next(100) < percentTrue;
}

static int? TryGetSeed(HttpContext context)
{
    return int.TryParse(context.Request.Query["seed"], out var seed) ? seed : null;
}

static bool TryGetAnimation(HttpContext context, out GnouGnouBearAnimation animation)
{
    var value = context.Request.Query["animation"].ToString();
    if (string.IsNullOrWhiteSpace(value))
    {
        animation = GnouGnouBearAnimation.None;
        return true;
    }

    return Enum.TryParse(value, ignoreCase: true, out animation)
        && Enum.IsDefined(animation);
}

static string RenderAnimationGallery(GnouGnouBearOptions baseOptions)
{
    var builder = new StringBuilder(capacity: 280_000);
    builder.AppendLine("<!doctype html>");
    builder.AppendLine("<html lang=\"en\">");
    builder.AppendLine("<head>");
    builder.AppendLine("  <meta charset=\"utf-8\">");
    builder.AppendLine("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
    builder.AppendLine("  <meta http-equiv=\"cache-control\" content=\"no-store\">");
    builder.AppendLine("  <title>GnOuGo Bears Animation Gallery</title>");
    builder.AppendLine("  <style>");
    builder.AppendLine("    :root { color-scheme: light; font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif; background: #edf5ff; color: #17243a; }");
    builder.AppendLine("    * { box-sizing: border-box; }");
    builder.AppendLine("    body { margin: 0; min-height: 100vh; background: radial-gradient(circle at 10% 0%, #fff 0, #edf5ff 38%, #e4ecfb 100%); }");
    builder.AppendLine("    main { width: min(1480px, 100%); margin: 0 auto; padding: 34px clamp(18px, 4vw, 54px) 56px; }");
    builder.AppendLine("    header { display: grid; grid-template-columns: minmax(0, 1fr) auto; gap: 24px; align-items: end; margin-bottom: 28px; }");
    builder.AppendLine("    .eyebrow { margin: 0 0 7px; color: #2e67b3; font-size: .78rem; font-weight: 850; letter-spacing: .13em; text-transform: uppercase; }");
    builder.AppendLine("    h1 { margin: 0; color: #173b6d; font-size: clamp(2.25rem, 5vw, 5rem); line-height: .94; letter-spacing: -.055em; }");
    builder.AppendLine("    .intro { max-width: 760px; margin: 15px 0 0; color: #52637b; font-size: 1.02rem; line-height: 1.65; }");
    builder.AppendLine("    .toolbar { display: flex; flex-wrap: wrap; gap: 9px; align-items: end; justify-content: flex-end; }");
    builder.AppendLine("    .seed-form { display: grid; grid-template-columns: minmax(120px, 160px) auto; gap: 8px; align-items: end; }");
    builder.AppendLine("    label { display: grid; gap: 5px; color: #53657c; font-size: .75rem; font-weight: 800; letter-spacing: .04em; text-transform: uppercase; }");
    builder.AppendLine("    input { width: 100%; min-height: 43px; border: 1px solid #b8c9df; border-radius: 11px; padding: 0 12px; background: rgba(255,255,255,.9); color: #17243a; font: inherit; font-weight: 700; }");
    builder.AppendLine("    button, .button { min-height: 43px; display: inline-flex; align-items: center; justify-content: center; border: 0; border-radius: 11px; padding: 0 15px; background: #245aa6; color: #fff; font: inherit; font-weight: 800; text-decoration: none; cursor: pointer; box-shadow: 0 8px 18px rgba(36,90,166,.18); }");
    builder.AppendLine("    .button.secondary { background: #fff; color: #245aa6; border: 1px solid #c4d3e7; box-shadow: none; }");
    builder.AppendLine("    .summary { display: flex; flex-wrap: wrap; gap: 8px; margin: 0 0 20px; }");
    builder.AppendLine("    .pill { border: 1px solid rgba(115,139,170,.24); border-radius: 999px; padding: 7px 11px; background: rgba(255,255,255,.66); color: #51647d; font-size: .78rem; font-weight: 750; }");
    builder.AppendLine("    .gallery { display: grid; grid-template-columns: repeat(auto-fit, minmax(245px, 1fr)); gap: 18px; }");
    builder.AppendLine("    .card { position: relative; overflow: hidden; display: grid; grid-template-rows: auto 1fr auto; min-height: 366px; border: 1px solid rgba(103,132,170,.22); border-radius: 22px; background: rgba(255,255,255,.82); box-shadow: 0 18px 44px rgba(37,66,104,.1); backdrop-filter: blur(9px); transition: transform .2s ease, box-shadow .2s ease; }");
    builder.AppendLine("    .card:hover { transform: translateY(-3px); box-shadow: 0 22px 52px rgba(37,66,104,.15); }");
    builder.AppendLine("    .card-head { display: flex; justify-content: space-between; gap: 10px; align-items: center; padding: 16px 17px 0; }");
    builder.AppendLine("    h2 { margin: 0; color: #193c68; font-size: 1rem; letter-spacing: -.01em; }");
    builder.AppendLine("    .status { border-radius: 999px; padding: 5px 8px; background: #e9f1fb; color: #4d6788; font-size: .68rem; font-weight: 850; letter-spacing: .06em; text-transform: uppercase; }");
    builder.AppendLine("    .status.live { background: #dbfaf2; color: #18755f; }");
    builder.AppendLine("    .bear { display: grid; place-items: center; min-height: 272px; padding: 3px 10px 0; }");
    builder.AppendLine("    .bear svg { width: min(270px, 100%); height: auto; display: block; }");
    builder.AppendLine("    .card-foot { display: flex; justify-content: space-between; align-items: center; gap: 12px; padding: 0 17px 16px; color: #687991; font-size: .78rem; }");
    builder.AppendLine("    .open-svg { color: #245aa6; font-weight: 800; text-decoration: none; }");
    builder.AppendLine("    .motion-note { margin: 22px 0 0; color: #697b92; font-size: .82rem; text-align: center; }");
    builder.AppendLine("    @media (max-width: 820px) { header { grid-template-columns: 1fr; align-items: start; } .toolbar { justify-content: flex-start; } }");
    builder.AppendLine("    @media (max-width: 520px) { main { padding-inline: 14px; } .seed-form { grid-template-columns: 1fr auto; } .gallery { grid-template-columns: 1fr; } }");
    builder.AppendLine("    @media (prefers-reduced-motion: reduce) { .card { transition: none; } }");
    builder.AppendLine("  </style>");
    builder.AppendLine("</head>");
    builder.AppendLine("<body>");
    builder.AppendLine("  <main>");
    builder.AppendLine("    <header>");
    builder.AppendLine("      <div>");
    builder.AppendLine("        <p class=\"eyebrow\">GnOuGo.Assets.Bears</p>");
    builder.AppendLine("        <h1>Animation gallery</h1>");
    builder.AppendLine("        <p class=\"intro\">Compare every script-free SVG preset on the same deterministic GnOuGo. Static mode is included so the animated rig can be checked against the original mascot.</p>");
    builder.AppendLine("      </div>");
    builder.AppendLine("      <div class=\"toolbar\">");
    builder.AppendLine("        <form class=\"seed-form\" method=\"get\" action=\"/\">");
    builder.Append("          <label>Seed<input name=\"seed\" type=\"number\" min=\"1\" max=\"2147483647\" value=\"").Append(baseOptions.Seed).AppendLine("\"></label>");
    builder.AppendLine("          <button type=\"submit\">Apply</button>");
    builder.AppendLine("        </form>");
    builder.AppendLine("        <a class=\"button secondary\" href=\"/\">Randomize</a>");
    builder.AppendLine("      </div>");
    builder.AppendLine("    </header>");
    builder.AppendLine("    <div class=\"summary\" aria-label=\"Mascot appearance\">");
    AppendPill(builder, $"Seed {baseOptions.Seed}");
    AppendPill(builder, baseOptions.FurPalette.ToString());
    AppendPill(builder, baseOptions.EyeStyle.ToString());
    AppendPill(builder, baseOptions.HasBeard ? "Bearded" : "No beard");
    AppendPill(builder, baseOptions.HasHeadphones ? "Headphones" : "No headphones");
    AppendPill(builder, baseOptions.HasBowTie ? "Bow tie" : "No bow tie");
    builder.AppendLine("    </div>");
    builder.AppendLine("    <section class=\"gallery\" aria-label=\"Available GnOuGo animations\">");

    foreach (var animation in Enum.GetValues<GnouGnouBearAnimation>())
    {
        var token = animation.ToString().ToLowerInvariant();
        var animated = animation != GnouGnouBearAnimation.None;
        var options = baseOptions with
        {
            Animation = animation,
            SvgIdPrefix = $"gallery-{token}",
            Title = $"{animation} GnOuGo animation",
            Description = animated
                ? $"GnOuGo demonstrating the {animation} animation preset."
                : "Static GnOuGo with animation disabled."
        };
        var svg = GnouGnouBearSvgGenerator.Generate(options);

        builder.AppendLine("      <article class=\"card\">");
        builder.AppendLine("        <div class=\"card-head\">");
        builder.Append("          <h2>").Append(animation).AppendLine("</h2>");
        builder.Append("          <span class=\"status").Append(animated ? " live" : string.Empty).Append("\">")
            .Append(animated ? "Animated" : "Static").AppendLine("</span>");
        builder.Append("        </div><div class=\"bear\">").Append(svg).AppendLine("</div>");
        builder.AppendLine("        <div class=\"card-foot\">");
        builder.Append("          <span>").Append(animated ? "CSS preset" : "Legacy rendering").AppendLine("</span>");
        builder.Append("          <a class=\"open-svg\" href=\"/bear.svg?seed=").Append(baseOptions.Seed)
            .Append("&amp;animation=").Append(animation).AppendLine("\" target=\"_blank\" rel=\"noopener\">Open SVG ↗</a>");
        builder.AppendLine("        </div>");
        builder.AppendLine("      </article>");
    }

    builder.AppendLine("    </section>");
    builder.AppendLine("    <p class=\"motion-note\">Your operating system’s reduced-motion preference is respected automatically.</p>");
    builder.AppendLine("  </main>");
    builder.AppendLine("</body>");
    builder.AppendLine("</html>");
    return builder.ToString();
}

static void AppendPill(StringBuilder builder, string value)
{
    builder.Append("      <span class=\"pill\">").Append(value).AppendLine("</span>");
}
