using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using GnOuGo.Assets.Bears;

var builder = WebApplication.CreateSlimBuilder(args);

var app = builder.Build();

app.MapMethods("/", ["GET"], (RequestDelegate)(async context =>
{
    var options = CreateRandomBearOptions(TryGetSeed(context));
    var html = RenderAnimationGallery(options);

    context.Response.Headers.CacheControl = "no-store";
    context.Response.ContentType = "text/html; charset=utf-8";
    await context.Response.WriteAsync(html);
}));

app.MapMethods("/bear.svg", ["GET"], (RequestDelegate)(async context =>
{
    if (!TryGetAnimation(context, out var animation))
    {
        context.Response.StatusCode = StatusCodes.Status400BadRequest;
        context.Response.ContentType = "text/plain; charset=utf-8";
        await context.Response.WriteAsync(
            $"Unknown animation. Supported values: {string.Join(", ", Enum.GetNames<GnouGnouBearAnimation>())}.");
        return;
    }

    var baseOptions = CreateRandomBearOptions(TryGetSeed(context));
    var appearance = TryGetAppearance(context, baseOptions);
    var options = (appearance?.Options ?? baseOptions) with
    {
        Animation = animation,
        Size = 512,
        SvgIdPrefix = "standalone-preview",
        Title = $"{animation} GnOuGo animation",
        Description = $"Standalone {animation} animation generated by GnOuGo.Assets.Bears."
    };
    var svg = GnouGnouBearSvgGenerator.Generate(options);

    context.Response.Headers.CacheControl = "no-store";
    context.Response.ContentType = "image/svg+xml; charset=utf-8";
    await context.Response.WriteAsync(svg);
}));

app.MapMethods("/text", ["GET"], (RequestDelegate)(async context =>
{
    var initialOptions = new GnouGnouTextOptions();
    if (TryCreateTextOptions(context, out var requestedOptions, out _)
        && TryGenerateTextSvg(requestedOptions, out _, out _))
    {
        initialOptions = requestedOptions;
    }

    context.Response.Headers.CacheControl = "no-store";
    context.Response.ContentType = "text/html; charset=utf-8";
    await context.Response.WriteAsync(TextDemoPage.Render(initialOptions));
}));

app.MapMethods("/text.svg", ["GET"], (RequestDelegate)(async context =>
{
    if (!TryCreateTextOptions(context, out var options, out var parseError))
    {
        context.Response.StatusCode = StatusCodes.Status400BadRequest;
        context.Response.Headers.CacheControl = "no-store";
        context.Response.ContentType = "text/plain; charset=utf-8";
        await context.Response.WriteAsync(parseError ?? "Invalid text SVG options.");
        return;
    }

    if (!TryGenerateTextSvg(options, out var svg, out var generationError))
    {
        context.Response.StatusCode = StatusCodes.Status400BadRequest;
        context.Response.Headers.CacheControl = "no-store";
        context.Response.ContentType = "text/plain; charset=utf-8";
        await context.Response.WriteAsync(generationError ?? "Invalid text SVG options.");
        return;
    }

    context.Response.Headers.CacheControl = "no-store";
    context.Response.ContentType = "image/svg+xml; charset=utf-8";
    await context.Response.WriteAsync(svg);
}));

app.MapMethods("/bear-text", ["GET"], (RequestDelegate)(async context =>
{
    var initialOptions = new GnouGnouBearTextOptions();
    if (TryCreateBearTextOptions(context, out var requestedOptions, out _)
        && TryGenerateBearTextSvg(requestedOptions, out _, out _))
    {
        initialOptions = requestedOptions;
    }

    context.Response.Headers.CacheControl = "no-store";
    context.Response.ContentType = "text/html; charset=utf-8";
    await context.Response.WriteAsync(BearTextDemoPage.Render(initialOptions));
}));

app.MapMethods("/bear-text.svg", ["GET"], (RequestDelegate)(async context =>
{
    if (!TryCreateBearTextOptions(context, out var options, out var parseError))
    {
        context.Response.StatusCode = StatusCodes.Status400BadRequest;
        context.Response.Headers.CacheControl = "no-store";
        context.Response.ContentType = "text/plain; charset=utf-8";
        await context.Response.WriteAsync(parseError ?? "Invalid bear and text SVG options.");
        return;
    }

    if (!TryGenerateBearTextSvg(options, out var svg, out var generationError))
    {
        context.Response.StatusCode = StatusCodes.Status400BadRequest;
        context.Response.Headers.CacheControl = "no-store";
        context.Response.ContentType = "text/plain; charset=utf-8";
        await context.Response.WriteAsync(generationError ?? "Invalid bear and text SVG options.");
        return;
    }

    context.Response.Headers.CacheControl = "no-store";
    context.Response.ContentType = "image/svg+xml; charset=utf-8";
    await context.Response.WriteAsync(svg);
}));

app.Run();

static GnouGnouBearOptions CreateRandomBearOptions(int? seed = null)
{
    var actualSeed = seed ?? RandomNumberGenerator.GetInt32(1, int.MaxValue);
    var random = new Random(actualSeed);

    return new GnouGnouBearOptions
    {
        Seed = actualSeed,
        Role = Pick<GnouGnouBearRole>(random),
        Emotion = Pick<GnouGnouBearEmotion>(random),
        Accessory = Pick<GnouGnouBearAccessory>(random),
        State = Pick<GnouGnouBearState>(random),
        Theme = Pick<GnouGnouBearTheme>(random),
        FurPalette = Pick<GnouGnouBearFurPalette>(random),
        EyeStyle = Pick<GnouGnouBearEyeStyle>(random),
        NoseStyle = Pick<GnouGnouBearNoseStyle>(random),
        BeardStyle = Pick<GnouGnouBearBeardStyle>(random),
        HasHeadphones = RandomBool(random, percentTrue: 55),
        HasBowTie = RandomBool(random, percentTrue: 55),
        HasBeard = RandomBool(random, percentTrue: 30),
        Size = 320,
        Title = "GnouGnou animation preview",
        Description = $"Deterministic GnouGnou SVG mascot generated from seed {actualSeed}."
    };
}

static T Pick<T>(Random random)
    where T : struct, Enum
{
    var values = Enum.GetValues<T>();
    return values[random.Next(values.Length)];
}

static bool RandomBool(Random random, int percentTrue)
{
    return random.Next(100) < percentTrue;
}

static int? TryGetSeed(HttpContext context)
{
    return int.TryParse(context.Request.Query["seed"], out var seed) ? seed : null;
}

static bool TryCreateTextOptions(
    HttpContext context,
    out GnouGnouTextOptions options,
    out string? error)
{
    var defaults = new GnouGnouTextOptions();
    var query = context.Request.Query;
    var text = query.TryGetValue("text", out var textValue) ? textValue.ToString() : defaults.Text;

    var size = defaults.Size;
    if (query.TryGetValue("size", out var sizeValue)
        && !int.TryParse(sizeValue.ToString(), NumberStyles.Integer, CultureInfo.InvariantCulture, out size))
    {
        options = defaults;
        error = "Size must be an integer between 16 and 1024.";
        return false;
    }

    var starCount = defaults.StarCount;
    if (query.TryGetValue("stars", out var starsValue)
        && !int.TryParse(starsValue.ToString(), NumberStyles.Integer, CultureInfo.InvariantCulture, out starCount))
    {
        options = defaults;
        error = "Stars must be an integer between zero and eight.";
        return false;
    }

    var starScale = defaults.StarScale;
    if (query.TryGetValue("starScale", out var starScaleValue)
        && !double.TryParse(starScaleValue.ToString(), NumberStyles.Float, CultureInfo.InvariantCulture, out starScale))
    {
        options = defaults;
        error = "Star scale must be a number between 0.25 and 3.";
        return false;
    }

    double? horizontalMargin = null;
    if (query.TryGetValue("marginX", out var horizontalMarginValue)
        && !string.IsNullOrWhiteSpace(horizontalMarginValue.ToString()))
    {
        if (!double.TryParse(
                horizontalMarginValue.ToString(),
                NumberStyles.Float,
                CultureInfo.InvariantCulture,
                out var parsedHorizontalMargin))
        {
            options = defaults;
            error = "Horizontal margin must be a number between zero and 4096.";
            return false;
        }

        horizontalMargin = parsedHorizontalMargin;
    }

    double? verticalMargin = null;
    if (query.TryGetValue("marginY", out var verticalMarginValue)
        && !string.IsNullOrWhiteSpace(verticalMarginValue.ToString()))
    {
        if (!double.TryParse(
                verticalMarginValue.ToString(),
                NumberStyles.Float,
                CultureInfo.InvariantCulture,
                out var parsedVerticalMargin))
        {
            options = defaults;
            error = "Vertical margin must be a number between zero and 4096.";
            return false;
        }

        verticalMargin = parsedVerticalMargin;
    }

    var animation = defaults.Animation;
    if (query.TryGetValue("animation", out var animationValue)
        && (!Enum.TryParse(animationValue.ToString(), ignoreCase: true, out animation)
            || !Enum.IsDefined(animation)))
    {
        options = defaults;
        error = $"Unknown text animation. Supported values: {string.Join(", ", Enum.GetNames<GnouGnouTextAnimation>())}.";
        return false;
    }

    var colors = query.TryGetValue("color", out var colorValues) && colorValues.Count > 0
        ? colorValues.Select(static color => color ?? string.Empty).ToArray()
        : defaults.GradientColors;
    var starColor = query.TryGetValue("starColor", out var starColorValue)
        && !string.IsNullOrWhiteSpace(starColorValue.ToString())
            ? starColorValue.ToString()
            : null;
    var svgIdPrefix = query.TryGetValue("idPrefix", out var idPrefixValue)
        && !string.IsNullOrWhiteSpace(idPrefixValue.ToString())
            ? idPrefixValue.ToString()
            : null;

    options = defaults with
    {
        Text = text,
        Size = size,
        HorizontalMargin = horizontalMargin,
        VerticalMargin = verticalMargin,
        GradientColors = colors,
        StarCount = starCount,
        StarColor = starColor,
        StarScale = starScale,
        Animation = animation,
        SvgIdPrefix = svgIdPrefix
    };
    error = null;
    return true;
}

static bool TryGenerateTextSvg(
    GnouGnouTextOptions options,
    out string svg,
    out string? error)
{
    try
    {
        svg = GnouGnouTextSvgGenerator.Generate(options);
        error = null;
        return true;
    }
    catch (ArgumentException exception)
    {
        svg = string.Empty;
        error = exception.Message;
        return false;
    }
}

static bool TryCreateBearTextOptions(
    HttpContext context,
    out GnouGnouBearTextOptions options,
    out string? error)
{
    var defaults = new GnouGnouBearTextOptions();
    var query = context.Request.Query;

    if (!TryReadInt(query, "seed", defaults.BearOptions.Seed, out var seed, out error)
        || !TryReadInt(query, "bearSize", defaults.BearOptions.Size, out var bearSize, out error)
        || !TryReadInt(query, "accessoryColor", defaults.BearOptions.AccessoryColorVariant, out var accessoryColor, out error)
        || !TryReadEnum(query, "role", defaults.BearOptions.Role, out GnouGnouBearRole role, out error)
        || !TryReadEnum(query, "emotion", defaults.BearOptions.Emotion, out GnouGnouBearEmotion emotion, out error)
        || !TryReadEnum(query, "accessory", defaults.BearOptions.Accessory, out GnouGnouBearAccessory accessory, out error)
        || !TryReadEnum(query, "state", defaults.BearOptions.State, out GnouGnouBearState state, out error)
        || !TryReadEnum(query, "theme", defaults.BearOptions.Theme, out GnouGnouBearTheme theme, out error)
        || !TryReadEnum(query, "fur", defaults.BearOptions.FurPalette, out GnouGnouBearFurPalette fur, out error)
        || !TryReadEnum(query, "eyes", defaults.BearOptions.EyeStyle, out GnouGnouBearEyeStyle eyes, out error)
        || !TryReadEnum(query, "nose", defaults.BearOptions.NoseStyle, out GnouGnouBearNoseStyle nose, out error)
        || !TryReadEnum(query, "beardStyle", defaults.BearOptions.BeardStyle, out GnouGnouBearBeardStyle beardStyle, out error)
        || !TryReadEnum(query, "bearAnimation", defaults.BearOptions.Animation, out GnouGnouBearAnimation bearAnimation, out error)
        || !TryReadBool(query, "headphones", defaults.BearOptions.HasHeadphones, out var headphones, out error)
        || !TryReadBool(query, "bowTie", defaults.BearOptions.HasBowTie, out var bowTie, out error)
        || !TryReadBool(query, "beard", defaults.BearOptions.HasBeard, out var beard, out error)
        || !TryReadInt(query, "textSize", defaults.TextOptions.Size, out var textSize, out error)
        || !TryReadNullableDouble(query, "marginX", out var marginX, out error)
        || !TryReadNullableDouble(query, "marginY", out var marginY, out error)
        || !TryReadInt(query, "stars", defaults.TextOptions.StarCount, out var stars, out error)
        || !TryReadDouble(query, "starScale", defaults.TextOptions.StarScale, out var starScale, out error)
        || !TryReadEnum(query, "textAnimation", defaults.TextOptions.Animation, out GnouGnouTextAnimation textAnimation, out error)
        || !TryReadDouble(query, "gap", defaults.Gap, out var gap, out error))
    {
        options = defaults;
        return false;
    }

    var text = query.TryGetValue("text", out var textValue)
        ? textValue.ToString()
        : defaults.TextOptions.Text;
    var colors = query.TryGetValue("color", out var colorValues) && colorValues.Count > 0
        ? colorValues.Select(static color => color ?? string.Empty).ToArray()
        : defaults.TextOptions.GradientColors;
    var starColor = query.TryGetValue("starColor", out var starColorValue)
        && !string.IsNullOrWhiteSpace(starColorValue.ToString())
            ? starColorValue.ToString()
            : null;
    var idPrefix = query.TryGetValue("idPrefix", out var idPrefixValue)
        && !string.IsNullOrWhiteSpace(idPrefixValue.ToString())
            ? idPrefixValue.ToString()
            : null;

    options = defaults with
    {
        BearOptions = defaults.BearOptions with
        {
            Seed = seed,
            Size = bearSize,
            Role = role,
            Emotion = emotion,
            Accessory = accessory,
            AccessoryColorVariant = accessoryColor,
            State = state,
            Theme = theme,
            FurPalette = fur,
            EyeStyle = eyes,
            NoseStyle = nose,
            BeardStyle = beardStyle,
            HasHeadphones = headphones,
            HasBowTie = bowTie,
            HasBeard = beard,
            Animation = bearAnimation
        },
        TextOptions = defaults.TextOptions with
        {
            Text = text,
            Size = textSize,
            HorizontalMargin = marginX,
            VerticalMargin = marginY,
            GradientColors = colors,
            StarCount = stars,
            StarColor = starColor,
            StarScale = starScale,
            Animation = textAnimation
        },
        Gap = gap,
        SvgIdPrefix = idPrefix
    };
    error = null;
    return true;
}

static bool TryGenerateBearTextSvg(
    GnouGnouBearTextOptions options,
    out string svg,
    out string? error)
{
    try
    {
        svg = GnouGnouBearTextSvgGenerator.Generate(options);
        error = null;
        return true;
    }
    catch (ArgumentException exception)
    {
        svg = string.Empty;
        error = exception.Message;
        return false;
    }
}

static bool TryReadInt(
    IQueryCollection query,
    string name,
    int defaultValue,
    out int value,
    out string? error)
{
    value = defaultValue;
    if (!query.TryGetValue(name, out var rawValue))
    {
        error = null;
        return true;
    }

    if (int.TryParse(rawValue.ToString(), NumberStyles.Integer, CultureInfo.InvariantCulture, out value))
    {
        error = null;
        return true;
    }

    error = $"{name} must be an integer.";
    return false;
}

static bool TryReadDouble(
    IQueryCollection query,
    string name,
    double defaultValue,
    out double value,
    out string? error)
{
    value = defaultValue;
    if (!query.TryGetValue(name, out var rawValue))
    {
        error = null;
        return true;
    }

    if (double.TryParse(rawValue.ToString(), NumberStyles.Float, CultureInfo.InvariantCulture, out value))
    {
        error = null;
        return true;
    }

    error = $"{name} must be a number.";
    return false;
}

static bool TryReadNullableDouble(
    IQueryCollection query,
    string name,
    out double? value,
    out string? error)
{
    value = null;
    if (!query.TryGetValue(name, out var rawValue) || string.IsNullOrWhiteSpace(rawValue.ToString()))
    {
        error = null;
        return true;
    }

    if (double.TryParse(rawValue.ToString(), NumberStyles.Float, CultureInfo.InvariantCulture, out var parsedValue))
    {
        value = parsedValue;
        error = null;
        return true;
    }

    error = $"{name} must be a number.";
    return false;
}

static bool TryReadBool(
    IQueryCollection query,
    string name,
    bool defaultValue,
    out bool value,
    out string? error)
{
    value = defaultValue;
    if (!query.TryGetValue(name, out var rawValue))
    {
        error = null;
        return true;
    }

    if (bool.TryParse(rawValue.ToString(), out value))
    {
        error = null;
        return true;
    }

    error = $"{name} must be true or false.";
    return false;
}

static bool TryReadEnum<T>(
    IQueryCollection query,
    string name,
    T defaultValue,
    out T value,
    out string? error)
    where T : struct, Enum
{
    value = defaultValue;
    if (!query.TryGetValue(name, out var rawValue))
    {
        error = null;
        return true;
    }

    if (Enum.TryParse(rawValue.ToString(), ignoreCase: true, out value) && Enum.IsDefined(value))
    {
        error = null;
        return true;
    }

    error = $"Unknown {name}. Supported values: {string.Join(", ", Enum.GetNames<T>())}.";
    return false;
}

static bool TryGetAnimation(HttpContext context, out GnouGnouBearAnimation animation)
{
    var value = context.Request.Query["animation"].ToString();
    if (string.IsNullOrWhiteSpace(value))
    {
        animation = GnouGnouBearAnimation.None;
        return true;
    }

    return Enum.TryParse(value, ignoreCase: true, out animation)
        && Enum.IsDefined(animation);
}

static GalleryAppearance? TryGetAppearance(HttpContext context, GnouGnouBearOptions baseOptions)
{
    var token = context.Request.Query["appearance"].ToString();
    if (string.IsNullOrWhiteSpace(token))
        return null;

    return CreateGalleryAppearances(baseOptions).FirstOrDefault(appearance =>
        string.Equals(appearance.Token, token, StringComparison.OrdinalIgnoreCase));
}

static IReadOnlyList<GalleryAppearance> CreateGalleryAppearances(GnouGnouBearOptions baseOptions)
{
    GnouGnouBearOptions Face(
        int ordinal,
        GnouGnouBearEmotion emotion,
        GnouGnouBearEyeStyle eyeStyle,
        GnouGnouBearNoseStyle noseStyle,
        GnouGnouBearFurPalette furPalette,
        GnouGnouBearBeardStyle beardStyle = GnouGnouBearBeardStyle.Random,
        bool hasBeard = false,
        bool hasHeadphones = true)
    {
        return baseOptions with
        {
            Seed = unchecked(baseOptions.Seed ^ (ordinal * 7919)),
            Role = GnouGnouBearRole.Default,
            Emotion = emotion,
            Accessory = GnouGnouBearAccessory.None,
            Accessories = [],
            State = GnouGnouBearState.Idle,
            Theme = GnouGnouBearTheme.Transparent,
            FurPalette = furPalette,
            EyeStyle = eyeStyle,
            NoseStyle = noseStyle,
            BeardStyle = beardStyle,
            HasHeadphones = hasHeadphones,
            HasBowTie = true,
            HasBeard = hasBeard,
            Size = 320
        };
    }

    return
    [
        new(
            "bright-smile",
            "Bright smile",
            "Big glossy eyes · soft brows · button nose · happy mouth",
            Face(1, GnouGnouBearEmotion.Happy, GnouGnouBearEyeStyle.BigGlossy, GnouGnouBearNoseStyle.Button, GnouGnouBearFurPalette.Classic)),
        new(
            "curious-side-eye",
            "Curious",
            "Side-eye pupils · asymmetric brows · triangle nose · thinking mouth",
            Face(2, GnouGnouBearEmotion.Thinking, GnouGnouBearEyeStyle.SideEye, GnouGnouBearNoseStyle.Triangle, GnouGnouBearFurPalette.Honey)),
        new(
            "starry-pride",
            "Starry pride",
            "Starry eyes · bold brows · heart nose · proud grin",
            Face(3, GnouGnouBearEmotion.Proud, GnouGnouBearEyeStyle.Starry, GnouGnouBearNoseStyle.Heart, GnouGnouBearFurPalette.Rose, hasHeadphones: false)),
        new(
            "sleepy-soft",
            "Sleepy soft",
            "Closed eyes · relaxed brows · button nose · sleepy mouth",
            Face(4, GnouGnouBearEmotion.Sleeping, GnouGnouBearEyeStyle.Default, GnouGnouBearNoseStyle.Button, GnouGnouBearFurPalette.Polar, hasHeadphones: false)),
        new(
            "sparkling-surprise",
            "Sparkling surprise",
            "Sparkly eyes · raised brows · wide nose · surprised mouth",
            Face(5, GnouGnouBearEmotion.Surprised, GnouGnouBearEyeStyle.Sparkly, GnouGnouBearNoseStyle.Wide, GnouGnouBearFurPalette.Lavender)),
        new(
            "classic-beard",
            "Classic beard",
            "Focused eyes and brows · default nose · classic rounded beard",
            Face(6, GnouGnouBearEmotion.Focused, GnouGnouBearEyeStyle.Default, GnouGnouBearNoseStyle.Default, GnouGnouBearFurPalette.Cocoa, GnouGnouBearBeardStyle.Classic, hasBeard: true)),
        new(
            "long-point-beard",
            "Long-point beard",
            "Tiny eyes · proud brows · triangle nose · long pointed beard",
            Face(7, GnouGnouBearEmotion.Proud, GnouGnouBearEyeStyle.Tiny, GnouGnouBearNoseStyle.Triangle, GnouGnouBearFurPalette.Blueberry, GnouGnouBearBeardStyle.LongPoint, hasBeard: true)),
        new(
            "cloud-beard",
            "Cloud beard",
            "Glossy eyes · friendly brows · button nose · cloud beard",
            Face(8, GnouGnouBearEmotion.Happy, GnouGnouBearEyeStyle.BigGlossy, GnouGnouBearNoseStyle.Button, GnouGnouBearFurPalette.Mint, GnouGnouBearBeardStyle.Cloud, hasBeard: true)),
        new(
            "square-beard",
            "Square beard",
            "Side-eye pupils · worried brows · wide nose · square beard",
            Face(9, GnouGnouBearEmotion.Worried, GnouGnouBearEyeStyle.SideEye, GnouGnouBearNoseStyle.Wide, GnouGnouBearFurPalette.Panda, GnouGnouBearBeardStyle.Square, hasBeard: true, hasHeadphones: false)),
        new(
            "split-beard",
            "Split beard",
            "Winking eyes · thinking brows · heart nose · split beard",
            Face(10, GnouGnouBearEmotion.Thinking, GnouGnouBearEyeStyle.Wink, GnouGnouBearNoseStyle.Heart, GnouGnouBearFurPalette.Classic, GnouGnouBearBeardStyle.Split, hasBeard: true))
    ];
}

static string RenderAnimationGallery(GnouGnouBearOptions baseOptions)
{
    var appearances = CreateGalleryAppearances(baseOptions);
    var animations = Enum.GetValues<GnouGnouBearAnimation>()
        .Where(static animation => animation != GnouGnouBearAnimation.None)
        .OrderBy(static animation => animation == GnouGnouBearAnimation.Thinking ? 0 : 1)
        .ThenBy(static animation => (int)animation)
        .ToArray();
    var builder = new StringBuilder(capacity: 520_000);
    builder.AppendLine("<!doctype html>");
    builder.AppendLine("<html lang=\"en\">");
    builder.AppendLine("<head>");
    builder.AppendLine("  <meta charset=\"utf-8\">");
    builder.AppendLine("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
    builder.AppendLine("  <meta http-equiv=\"cache-control\" content=\"no-store\">");
    builder.AppendLine("  <title>GnOuGo Bears Animation Gallery</title>");
    builder.AppendLine("  <style>");
    builder.AppendLine("    :root { color-scheme: light; font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif; background: #edf5ff; color: #17243a; }");
    builder.AppendLine("    * { box-sizing: border-box; }");
    builder.AppendLine("    body { margin: 0; min-height: 100vh; background: radial-gradient(circle at 10% 0%, #fff 0, #edf5ff 38%, #e4ecfb 100%); }");
    builder.AppendLine("    main { width: min(1480px, 100%); margin: 0 auto; padding: 34px clamp(18px, 4vw, 54px) 56px; }");
    builder.AppendLine("    header { display: grid; grid-template-columns: minmax(0, 1fr) auto; gap: 24px; align-items: end; margin-bottom: 28px; }");
    builder.AppendLine("    .eyebrow { margin: 0 0 7px; color: #2e67b3; font-size: .78rem; font-weight: 850; letter-spacing: .13em; text-transform: uppercase; }");
    builder.AppendLine("    h1 { margin: 0; color: #173b6d; font-size: clamp(2.25rem, 5vw, 5rem); line-height: .94; letter-spacing: -.055em; }");
    builder.AppendLine("    .intro { max-width: 760px; margin: 15px 0 0; color: #52637b; font-size: 1.02rem; line-height: 1.65; }");
    builder.AppendLine("    .toolbar { display: flex; flex-wrap: wrap; gap: 9px; align-items: end; justify-content: flex-end; }");
    builder.AppendLine("    .seed-form { display: grid; grid-template-columns: minmax(120px, 160px) auto; gap: 8px; align-items: end; }");
    builder.AppendLine("    label { display: grid; gap: 5px; color: #53657c; font-size: .75rem; font-weight: 800; letter-spacing: .04em; text-transform: uppercase; }");
    builder.AppendLine("    input { width: 100%; min-height: 43px; border: 1px solid #b8c9df; border-radius: 11px; padding: 0 12px; background: rgba(255,255,255,.9); color: #17243a; font: inherit; font-weight: 700; }");
    builder.AppendLine("    button, .button { min-height: 43px; display: inline-flex; align-items: center; justify-content: center; border: 0; border-radius: 11px; padding: 0 15px; background: #245aa6; color: #fff; font: inherit; font-weight: 800; text-decoration: none; cursor: pointer; box-shadow: 0 8px 18px rgba(36,90,166,.18); }");
    builder.AppendLine("    .button.secondary { background: #fff; color: #245aa6; border: 1px solid #c4d3e7; box-shadow: none; }");
    builder.AppendLine("    .summary { display: flex; flex-wrap: wrap; gap: 8px; margin: 0 0 18px; }");
    builder.AppendLine("    .pill { border: 1px solid rgba(115,139,170,.24); border-radius: 999px; padding: 7px 11px; background: rgba(255,255,255,.66); color: #51647d; font-size: .78rem; font-weight: 750; }");
    builder.AppendLine("    .gallery-nav { position: sticky; top: 12px; z-index: 5; display: inline-flex; gap: 5px; margin: 0 0 30px; padding: 5px; border: 1px solid rgba(103,132,170,.22); border-radius: 14px; background: rgba(255,255,255,.9); box-shadow: 0 10px 26px rgba(37,66,104,.1); backdrop-filter: blur(12px); }");
    builder.AppendLine("    .gallery-tab { display: inline-flex; align-items: center; gap: 8px; min-height: 39px; padding: 0 14px; border-radius: 10px; color: #53657c; font-size: .84rem; font-weight: 850; text-decoration: none; }");
    builder.AppendLine("    .gallery-tab:first-child { background: #245aa6; color: #fff; }");
    builder.AppendLine("    .gallery-tab span { display: inline-grid; place-items: center; min-width: 22px; height: 22px; padding: 0 6px; border-radius: 999px; background: rgba(255,255,255,.18); font-size: .68rem; }");
    builder.AppendLine("    .gallery-tab:not(:first-child) span { background: #e8eff8; color: #48617f; }");
    builder.AppendLine("    .collection { scroll-margin-top: 80px; }");
    builder.AppendLine("    .collection + .collection { margin-top: 54px; padding-top: 46px; border-top: 1px solid rgba(103,132,170,.22); }");
    builder.AppendLine("    .collection-head { display: grid; grid-template-columns: minmax(0, 1fr) auto; gap: 24px; align-items: end; margin-bottom: 18px; }");
    builder.AppendLine("    .collection-kicker { margin: 0 0 5px; color: #2e67b3; font-size: .7rem; font-weight: 900; letter-spacing: .12em; text-transform: uppercase; }");
    builder.AppendLine("    .collection h2 { margin: 0; color: #173b6d; font-size: clamp(1.7rem, 3vw, 2.65rem); letter-spacing: -.035em; }");
    builder.AppendLine("    .collection-copy { max-width: 680px; margin: 8px 0 0; color: #60728a; line-height: 1.55; }");
    builder.AppendLine("    .collection-count { color: #72839a; font-size: .78rem; font-weight: 800; white-space: nowrap; }");
    builder.AppendLine("    .gallery { display: grid; grid-template-columns: repeat(auto-fit, minmax(245px, 1fr)); gap: 18px; }");
    builder.AppendLine("    .card { position: relative; overflow: hidden; display: grid; grid-template-rows: auto 1fr auto; min-height: 366px; border: 1px solid rgba(103,132,170,.22); border-radius: 22px; background: rgba(255,255,255,.82); box-shadow: 0 18px 44px rgba(37,66,104,.1); backdrop-filter: blur(9px); transition: transform .2s ease, box-shadow .2s ease; }");
    builder.AppendLine("    .card:hover { transform: translateY(-3px); box-shadow: 0 22px 52px rgba(37,66,104,.15); }");
    builder.AppendLine("    .card-head { display: flex; justify-content: space-between; gap: 10px; align-items: center; padding: 16px 17px 0; }");
    builder.AppendLine("    h3 { margin: 0; color: #193c68; font-size: 1rem; letter-spacing: -.01em; }");
    builder.AppendLine("    .status { border-radius: 999px; padding: 5px 8px; background: #e9f1fb; color: #4d6788; font-size: .68rem; font-weight: 850; letter-spacing: .06em; text-transform: uppercase; }");
    builder.AppendLine("    .status.live { background: #dbfaf2; color: #18755f; }");
    builder.AppendLine("    .bear { display: grid; place-items: center; min-height: 272px; padding: 3px 10px 0; }");
    builder.AppendLine("    .bear svg { width: min(270px, 100%); height: auto; display: block; }");
    builder.AppendLine("    .card-foot { display: flex; justify-content: space-between; align-items: flex-end; gap: 14px; padding: 0 17px 16px; color: #687991; font-size: .76rem; line-height: 1.45; }");
    builder.AppendLine("    .feature-note { max-width: 72%; }");
    builder.AppendLine("    .open-svg { flex: none; color: #245aa6; font-weight: 800; text-decoration: none; white-space: nowrap; }");
    builder.AppendLine("    .motion-note { margin: 22px 0 0; color: #697b92; font-size: .82rem; text-align: center; }");
    builder.AppendLine("    @media (max-width: 820px) { header, .collection-head { grid-template-columns: 1fr; align-items: start; } .toolbar { justify-content: flex-start; } }");
    builder.AppendLine("    @media (max-width: 520px) { main { padding-inline: 14px; } .seed-form { grid-template-columns: 1fr auto; } .gallery { grid-template-columns: 1fr; } }");
    builder.AppendLine("    @media (prefers-reduced-motion: reduce) { .card { transition: none; } }");
    builder.AppendLine("  </style>");
    builder.AppendLine("</head>");
    builder.AppendLine("<body>");
    builder.AppendLine("  <main>");
    builder.AppendLine("    <header>");
    builder.AppendLine("      <div>");
    builder.AppendLine("        <p class=\"eyebrow\">GnOuGo.Assets.Bears</p>");
    builder.AppendLine("        <h1>Animation gallery</h1>");
    builder.AppendLine("        <p class=\"intro\">Explore a visual library of static GnOuGo faces and the same diverse characters in motion. Eyes, eyebrows, noses, mouths, and five beard silhouettes remain deterministic, script-free SVG assets.</p>");
    builder.AppendLine("      </div>");
    builder.AppendLine("      <div class=\"toolbar\">");
    builder.AppendLine("        <form class=\"seed-form\" method=\"get\" action=\"/\">");
    builder.Append("          <label>Seed<input name=\"seed\" type=\"number\" min=\"1\" max=\"2147483647\" value=\"").Append(baseOptions.Seed).AppendLine("\"></label>");
    builder.AppendLine("          <button type=\"submit\">Apply</button>");
    builder.AppendLine("        </form>");
    builder.AppendLine("        <a class=\"button secondary\" href=\"/\">Randomize</a>");
    builder.AppendLine("        <a class=\"button secondary\" href=\"/text\">Text SVG demo</a>");
    builder.AppendLine("        <a class=\"button secondary\" href=\"/bear-text\">Bear + text demo</a>");
    builder.AppendLine("      </div>");
    builder.AppendLine("    </header>");
    builder.AppendLine("    <div class=\"summary\" aria-label=\"Mascot appearance\">");
    AppendPill(builder, $"Seed {baseOptions.Seed}");
    AppendPill(builder, $"{appearances.Count} static looks");
    AppendPill(builder, $"{animations.Length} animated presets");
    AppendPill(builder, "AI thinking included");
    AppendPill(builder, $"{Enum.GetValues<GnouGnouBearEyeStyle>().Length} eye styles");
    AppendPill(builder, $"{Enum.GetValues<GnouGnouBearNoseStyle>().Length} nose styles");
    AppendPill(builder, "5 beard silhouettes");
    builder.AppendLine("    </div>");
    builder.AppendLine("    <nav class=\"gallery-nav\" aria-label=\"Gallery collections\">");
    builder.Append("      <a class=\"gallery-tab\" href=\"#static\">Static <span>").Append(appearances.Count).AppendLine("</span></a>");
    builder.Append("      <a class=\"gallery-tab\" href=\"#animated\">Animated <span>").Append(animations.Length).AppendLine("</span></a>");
    builder.AppendLine("    </nav>");
    builder.AppendLine("    <section class=\"collection\" id=\"static\" aria-labelledby=\"static-title\">");
    builder.AppendLine("      <div class=\"collection-head\"><div>");
    builder.AppendLine("        <p class=\"collection-kicker\">Appearance library</p>");
    builder.AppendLine("        <h2 id=\"static-title\">Static</h2>");
    builder.AppendLine("        <p class=\"collection-copy\">Clean, still SVG references for comparing facial construction, expression, and beard silhouettes without body motion.</p>");
    builder.Append("      </div><span class=\"collection-count\">").Append(appearances.Count).AppendLine(" reproducible characters</span></div>");
    builder.AppendLine("      <div class=\"gallery\" aria-label=\"Static GnOuGo appearance variants\">");

    foreach (var appearance in appearances)
    {
        var options = appearance.Options with
        {
            Animation = GnouGnouBearAnimation.None,
            SvgIdPrefix = $"gallery-static-{appearance.Token}",
            Title = $"{appearance.Name} static GnOuGo",
            Description = appearance.Description
        };
        AppendGalleryCard(builder, appearance.Name, appearance.Description, options, "Static", false,
            $"/bear.svg?seed={baseOptions.Seed}&amp;appearance={appearance.Token}&amp;animation=None");
    }

    builder.AppendLine("      </div>");
    builder.AppendLine("    </section>");
    builder.AppendLine("    <section class=\"collection\" id=\"animated\" aria-labelledby=\"animated-title\">");
    builder.AppendLine("      <div class=\"collection-head\"><div>");
    builder.AppendLine("        <p class=\"collection-kicker\">Motion library</p>");
    builder.AppendLine("        <h2 id=\"animated-title\">Animated</h2>");
    builder.AppendLine("        <p class=\"collection-copy\">The same facial and beard diversity carried by semantic rigs with blinking, breathing, gestures, work poses, and outcome animations. AI Thinking is featured first with focused eyes, a warmer face, and forehead sweat drops.</p>");
    builder.Append("      </div><span class=\"collection-count\">").Append(animations.Length).AppendLine(" script-free presets</span></div>");
    builder.AppendLine("      <div class=\"gallery\" aria-label=\"Animated GnOuGo presets\">");

    for (var index = 0; index < animations.Length; index++)
    {
        var animation = animations[index];
        var appearance = appearances[index % appearances.Count];
        var animationToken = animation.ToString().ToLowerInvariant();
        var title = animation == GnouGnouBearAnimation.Thinking ? "AI Thinking" : animation.ToString();
        var description = animation == GnouGnouBearAnimation.Thinking
            ? $"{appearance.Name} · Concentrated moving eyes, inward brows, a warm face flush, and animated forehead sweat drops."
            : $"{appearance.Name} · {appearance.Description}";
        var options = appearance.Options with
        {
            Animation = animation,
            SvgIdPrefix = $"gallery-animated-{animationToken}-{appearance.Token}",
            Title = $"{title} animation on {appearance.Name} GnOuGo",
            Description = animation == GnouGnouBearAnimation.Thinking
                ? "GnOuGo concentrates during an AI call with changing eyes, a warmer face, and animated sweat drops."
                : $"{appearance.Description}. Demonstrating the {animation} animation preset."
        };
        AppendGalleryCard(builder, title, description, options, "Animated", true,
            $"/bear.svg?seed={baseOptions.Seed}&amp;appearance={appearance.Token}&amp;animation={animation}");
    }

    builder.AppendLine("      </div>");
    builder.AppendLine("    </section>");
    builder.AppendLine("    <p class=\"motion-note\">Your operating system’s reduced-motion preference is respected automatically.</p>");
    builder.AppendLine("  </main>");
    builder.AppendLine("</body>");
    builder.AppendLine("</html>");
    return builder.ToString();
}

static void AppendGalleryCard(
    StringBuilder builder,
    string title,
    string description,
    GnouGnouBearOptions options,
    string status,
    bool animated,
    string href)
{
    var svg = GnouGnouBearSvgGenerator.Generate(options);
    builder.Append("        <article class=\"card\" data-gallery-kind=\"")
        .Append(animated ? "animated" : "static").AppendLine("\">");
    builder.AppendLine("          <div class=\"card-head\">");
    builder.Append("            <h3>").Append(title).AppendLine("</h3>");
    builder.Append("            <span class=\"status").Append(animated ? " live" : string.Empty).Append("\">")
        .Append(status).AppendLine("</span>");
    builder.Append("          </div><div class=\"bear\">").Append(svg).AppendLine("</div>");
    builder.AppendLine("          <div class=\"card-foot\">");
    builder.Append("            <span class=\"feature-note\">").Append(description).AppendLine("</span>");
    builder.Append("            <a class=\"open-svg\" href=\"").Append(href)
        .AppendLine("\" target=\"_blank\" rel=\"noopener\">Open SVG ↗</a>");
    builder.AppendLine("          </div>");
    builder.AppendLine("        </article>");
}

static void AppendPill(StringBuilder builder, string value)
{
    builder.Append("      <span class=\"pill\">").Append(value).AppendLine("</span>");
}

sealed record GalleryAppearance(
    string Token,
    string Name,
    string Description,
    GnouGnouBearOptions Options);

public partial class Program;
