// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Update.Internal;

#pragma warning disable 219, 612, 618
#nullable disable

namespace GnOuGo.Agent.Mcp.Data.CompiledModels
{
    public partial class AgentDbContextModel
    {
        private AgentDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("ca55f4e0-f0f9-46a3-8ba5-06e376882638"), entityTypeCount: 2)
        {
        }

        partial void Initialize()
        {
            var agentDefinition = AgentDefinitionEntityType.Create(this);
            var userConfigRecord = UserConfigRecordEntityType.Create(this);

            AgentDefinitionEntityType.CreateAnnotations(agentDefinition);
            UserConfigRecordEntityType.CreateAnnotations(userConfigRecord);

            AddAnnotation("ProductVersion", "10.0.8");
            AddRuntimeAnnotation("Relational:RelationalModelFactory", () => CreateRelationalModel());
        }

        private IRelationalModel CreateRelationalModel()
        {
            var relationalModel = new RelationalModel(this);

            var agentDefinition = FindEntityType("GnOuGo.Agent.Mcp.Models.AgentDefinition")!;

            var defaultTableMappings = new List<TableMappingBase<ColumnMappingBase>>();
            agentDefinition.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings);
            var gnOuGoAgentMcpModelsAgentDefinitionTableBase = new TableBase("GnOuGo.Agent.Mcp.Models.AgentDefinition", null, relationalModel);
            var createdAtTicksColumnBase = new ColumnBase<ColumnMappingBase>("CreatedAtTicks", "INTEGER", gnOuGoAgentMcpModelsAgentDefinitionTableBase);
            gnOuGoAgentMcpModelsAgentDefinitionTableBase.Columns.Add("CreatedAtTicks", createdAtTicksColumnBase);
            var idColumnBase = new ColumnBase<ColumnMappingBase>("Id", "TEXT", gnOuGoAgentMcpModelsAgentDefinitionTableBase);
            gnOuGoAgentMcpModelsAgentDefinitionTableBase.Columns.Add("Id", idColumnBase);
            var nameColumnBase = new ColumnBase<ColumnMappingBase>("Name", "TEXT", gnOuGoAgentMcpModelsAgentDefinitionTableBase);
            gnOuGoAgentMcpModelsAgentDefinitionTableBase.Columns.Add("Name", nameColumnBase);
            var originalPromptColumnBase = new ColumnBase<ColumnMappingBase>("OriginalPrompt", "TEXT", gnOuGoAgentMcpModelsAgentDefinitionTableBase)
            {
                IsNullable = true
            };
            gnOuGoAgentMcpModelsAgentDefinitionTableBase.Columns.Add("OriginalPrompt", originalPromptColumnBase);
            var scheduleDescriptionColumnBase = new ColumnBase<ColumnMappingBase>("ScheduleDescription", "TEXT", gnOuGoAgentMcpModelsAgentDefinitionTableBase)
            {
                IsNullable = true
            };
            gnOuGoAgentMcpModelsAgentDefinitionTableBase.Columns.Add("ScheduleDescription", scheduleDescriptionColumnBase);
            var schedulesJsonColumnBase = new ColumnBase<ColumnMappingBase>("SchedulesJson", "TEXT", gnOuGoAgentMcpModelsAgentDefinitionTableBase);
            gnOuGoAgentMcpModelsAgentDefinitionTableBase.Columns.Add("SchedulesJson", schedulesJsonColumnBase);
            var tenantIdColumnBase = new ColumnBase<ColumnMappingBase>("TenantId", "TEXT", gnOuGoAgentMcpModelsAgentDefinitionTableBase)
            {
                IsNullable = true
            };
            gnOuGoAgentMcpModelsAgentDefinitionTableBase.Columns.Add("TenantId", tenantIdColumnBase);
            var updatedAtTicksColumnBase = new ColumnBase<ColumnMappingBase>("UpdatedAtTicks", "INTEGER", gnOuGoAgentMcpModelsAgentDefinitionTableBase);
            gnOuGoAgentMcpModelsAgentDefinitionTableBase.Columns.Add("UpdatedAtTicks", updatedAtTicksColumnBase);
            var workflowColumnBase = new ColumnBase<ColumnMappingBase>("Workflow", "TEXT", gnOuGoAgentMcpModelsAgentDefinitionTableBase);
            gnOuGoAgentMcpModelsAgentDefinitionTableBase.Columns.Add("Workflow", workflowColumnBase);
            relationalModel.DefaultTables.Add("GnOuGo.Agent.Mcp.Models.AgentDefinition", gnOuGoAgentMcpModelsAgentDefinitionTableBase);
            var gnOuGoAgentMcpModelsAgentDefinitionMappingBase = new TableMappingBase<ColumnMappingBase>(agentDefinition, gnOuGoAgentMcpModelsAgentDefinitionTableBase, null);
            gnOuGoAgentMcpModelsAgentDefinitionTableBase.AddTypeMapping(gnOuGoAgentMcpModelsAgentDefinitionMappingBase, false);
            defaultTableMappings.Add(gnOuGoAgentMcpModelsAgentDefinitionMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase, agentDefinition.FindProperty("Id")!, gnOuGoAgentMcpModelsAgentDefinitionMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)createdAtTicksColumnBase, agentDefinition.FindProperty("CreatedAtTicks")!, gnOuGoAgentMcpModelsAgentDefinitionMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nameColumnBase, agentDefinition.FindProperty("Name")!, gnOuGoAgentMcpModelsAgentDefinitionMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)originalPromptColumnBase, agentDefinition.FindProperty("OriginalPrompt")!, gnOuGoAgentMcpModelsAgentDefinitionMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)scheduleDescriptionColumnBase, agentDefinition.FindProperty("ScheduleDescription")!, gnOuGoAgentMcpModelsAgentDefinitionMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)schedulesJsonColumnBase, agentDefinition.FindProperty("SchedulesJson")!, gnOuGoAgentMcpModelsAgentDefinitionMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)tenantIdColumnBase, agentDefinition.FindProperty("TenantId")!, gnOuGoAgentMcpModelsAgentDefinitionMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)updatedAtTicksColumnBase, agentDefinition.FindProperty("UpdatedAtTicks")!, gnOuGoAgentMcpModelsAgentDefinitionMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)workflowColumnBase, agentDefinition.FindProperty("Workflow")!, gnOuGoAgentMcpModelsAgentDefinitionMappingBase);

            var tableMappings = new List<TableMapping>();
            agentDefinition.SetRuntimeAnnotation("Relational:TableMappings", tableMappings);
            var agentsTable = new Table("Agents", null, relationalModel);
            var idColumn = new Column("Id", "TEXT", agentsTable);
            agentsTable.Columns.Add("Id", idColumn);
            idColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(idColumn);
            var createdAtTicksColumn = new Column("CreatedAtTicks", "INTEGER", agentsTable);
            agentsTable.Columns.Add("CreatedAtTicks", createdAtTicksColumn);
            createdAtTicksColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<long>(createdAtTicksColumn);
            var nameColumn = new Column("Name", "TEXT", agentsTable);
            agentsTable.Columns.Add("Name", nameColumn);
            nameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(nameColumn);
            var originalPromptColumn = new Column("OriginalPrompt", "TEXT", agentsTable)
            {
                IsNullable = true
            };
            agentsTable.Columns.Add("OriginalPrompt", originalPromptColumn);
            originalPromptColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(originalPromptColumn);
            var scheduleDescriptionColumn = new Column("ScheduleDescription", "TEXT", agentsTable)
            {
                IsNullable = true
            };
            agentsTable.Columns.Add("ScheduleDescription", scheduleDescriptionColumn);
            scheduleDescriptionColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(scheduleDescriptionColumn);
            var schedulesJsonColumn = new Column("SchedulesJson", "TEXT", agentsTable);
            agentsTable.Columns.Add("SchedulesJson", schedulesJsonColumn);
            schedulesJsonColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(schedulesJsonColumn);
            var tenantIdColumn = new Column("TenantId", "TEXT", agentsTable)
            {
                IsNullable = true
            };
            agentsTable.Columns.Add("TenantId", tenantIdColumn);
            tenantIdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(tenantIdColumn);
            var updatedAtTicksColumn = new Column("UpdatedAtTicks", "INTEGER", agentsTable);
            agentsTable.Columns.Add("UpdatedAtTicks", updatedAtTicksColumn);
            updatedAtTicksColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<long>(updatedAtTicksColumn);
            var workflowColumn = new Column("Workflow", "TEXT", agentsTable);
            agentsTable.Columns.Add("Workflow", workflowColumn);
            workflowColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(workflowColumn);
            relationalModel.Tables.Add(("Agents", null), agentsTable);
            var agentsTableMapping = new TableMapping(agentDefinition, agentsTable, null);
            agentsTable.AddTypeMapping(agentsTableMapping, false);
            tableMappings.Add(agentsTableMapping);
            RelationalModel.CreateColumnMapping(idColumn, agentDefinition.FindProperty("Id")!, agentsTableMapping);
            RelationalModel.CreateColumnMapping(createdAtTicksColumn, agentDefinition.FindProperty("CreatedAtTicks")!, agentsTableMapping);
            RelationalModel.CreateColumnMapping(nameColumn, agentDefinition.FindProperty("Name")!, agentsTableMapping);
            RelationalModel.CreateColumnMapping(originalPromptColumn, agentDefinition.FindProperty("OriginalPrompt")!, agentsTableMapping);
            RelationalModel.CreateColumnMapping(scheduleDescriptionColumn, agentDefinition.FindProperty("ScheduleDescription")!, agentsTableMapping);
            RelationalModel.CreateColumnMapping(schedulesJsonColumn, agentDefinition.FindProperty("SchedulesJson")!, agentsTableMapping);
            RelationalModel.CreateColumnMapping(tenantIdColumn, agentDefinition.FindProperty("TenantId")!, agentsTableMapping);
            RelationalModel.CreateColumnMapping(updatedAtTicksColumn, agentDefinition.FindProperty("UpdatedAtTicks")!, agentsTableMapping);
            RelationalModel.CreateColumnMapping(workflowColumn, agentDefinition.FindProperty("Workflow")!, agentsTableMapping);
            var pK_Agents = new UniqueConstraint("PK_Agents", agentsTable, new[] { idColumn });
            agentsTable.PrimaryKey = pK_Agents;
            pK_Agents.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<Guid>(pK_Agents));
            var pK_AgentsKey = RelationalModel.GetKey(this,
                "GnOuGo.Agent.Mcp.Models.AgentDefinition",
                new[] { "Id" });
            pK_Agents.MappedKeys.Add(pK_AgentsKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_AgentsKey).Add(pK_Agents);
            agentsTable.UniqueConstraints.Add("PK_Agents", pK_Agents);
            var iX_Agents_Name_TenantId = new TableIndex(
            "IX_Agents_Name_TenantId", agentsTable, new[] { nameColumn, tenantIdColumn }, true);
            iX_Agents_Name_TenantId.SetRowIndexValueFactory(new CompositeRowIndexValueFactory(iX_Agents_Name_TenantId));
            var iX_Agents_Name_TenantIdIx = RelationalModel.GetIndex(this,
                "GnOuGo.Agent.Mcp.Models.AgentDefinition",
                new[] { "Name", "TenantId" });
            iX_Agents_Name_TenantId.MappedIndexes.Add(iX_Agents_Name_TenantIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Agents_Name_TenantIdIx).Add(iX_Agents_Name_TenantId);
            agentsTable.Indexes.Add("IX_Agents_Name_TenantId", iX_Agents_Name_TenantId);
            var iX_Agents_TenantId = new TableIndex(
            "IX_Agents_TenantId", agentsTable, new[] { tenantIdColumn }, false);
            iX_Agents_TenantId.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<Guid>(iX_Agents_TenantId));
            var iX_Agents_TenantIdIx = RelationalModel.GetIndex(this,
                "GnOuGo.Agent.Mcp.Models.AgentDefinition",
                new[] { "TenantId" });
            iX_Agents_TenantId.MappedIndexes.Add(iX_Agents_TenantIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Agents_TenantIdIx).Add(iX_Agents_TenantId);
            agentsTable.Indexes.Add("IX_Agents_TenantId", iX_Agents_TenantId);

            var userConfigRecord = FindEntityType("GnOuGo.Agent.Mcp.Models.UserConfigRecord")!;

            var defaultTableMappings0 = new List<TableMappingBase<ColumnMappingBase>>();
            userConfigRecord.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings0);
            var gnOuGoAgentMcpModelsUserConfigRecordTableBase = new TableBase("GnOuGo.Agent.Mcp.Models.UserConfigRecord", null, relationalModel);
            var defaultAgentColumnBase = new ColumnBase<ColumnMappingBase>("DefaultAgent", "TEXT", gnOuGoAgentMcpModelsUserConfigRecordTableBase)
            {
                IsNullable = true
            };
            gnOuGoAgentMcpModelsUserConfigRecordTableBase.Columns.Add("DefaultAgent", defaultAgentColumnBase);
            var defaultEmbeddingConfigColumnBase = new ColumnBase<ColumnMappingBase>("DefaultEmbeddingConfig", "TEXT", gnOuGoAgentMcpModelsUserConfigRecordTableBase)
            {
                IsNullable = true
            };
            gnOuGoAgentMcpModelsUserConfigRecordTableBase.Columns.Add("DefaultEmbeddingConfig", defaultEmbeddingConfigColumnBase);
            var defaultLlmModelColumnBase = new ColumnBase<ColumnMappingBase>("DefaultLlmModel", "TEXT", gnOuGoAgentMcpModelsUserConfigRecordTableBase)
            {
                IsNullable = true
            };
            gnOuGoAgentMcpModelsUserConfigRecordTableBase.Columns.Add("DefaultLlmModel", defaultLlmModelColumnBase);
            var defaultLlmProviderColumnBase = new ColumnBase<ColumnMappingBase>("DefaultLlmProvider", "TEXT", gnOuGoAgentMcpModelsUserConfigRecordTableBase)
            {
                IsNullable = true
            };
            gnOuGoAgentMcpModelsUserConfigRecordTableBase.Columns.Add("DefaultLlmProvider", defaultLlmProviderColumnBase);
            var idColumnBase0 = new ColumnBase<ColumnMappingBase>("Id", "TEXT", gnOuGoAgentMcpModelsUserConfigRecordTableBase);
            gnOuGoAgentMcpModelsUserConfigRecordTableBase.Columns.Add("Id", idColumnBase0);
            var modelOverridesJsonColumnBase = new ColumnBase<ColumnMappingBase>("ModelOverridesJson", "TEXT", gnOuGoAgentMcpModelsUserConfigRecordTableBase)
            {
                IsNullable = true
            };
            gnOuGoAgentMcpModelsUserConfigRecordTableBase.Columns.Add("ModelOverridesJson", modelOverridesJsonColumnBase);
            var tenantIdColumnBase0 = new ColumnBase<ColumnMappingBase>("TenantId", "TEXT", gnOuGoAgentMcpModelsUserConfigRecordTableBase)
            {
                IsNullable = true
            };
            gnOuGoAgentMcpModelsUserConfigRecordTableBase.Columns.Add("TenantId", tenantIdColumnBase0);
            var tenantScopeKeyColumnBase = new ColumnBase<ColumnMappingBase>("TenantScopeKey", "TEXT", gnOuGoAgentMcpModelsUserConfigRecordTableBase);
            gnOuGoAgentMcpModelsUserConfigRecordTableBase.Columns.Add("TenantScopeKey", tenantScopeKeyColumnBase);
            var updatedAtTicksColumnBase0 = new ColumnBase<ColumnMappingBase>("UpdatedAtTicks", "INTEGER", gnOuGoAgentMcpModelsUserConfigRecordTableBase);
            gnOuGoAgentMcpModelsUserConfigRecordTableBase.Columns.Add("UpdatedAtTicks", updatedAtTicksColumnBase0);
            relationalModel.DefaultTables.Add("GnOuGo.Agent.Mcp.Models.UserConfigRecord", gnOuGoAgentMcpModelsUserConfigRecordTableBase);
            var gnOuGoAgentMcpModelsUserConfigRecordMappingBase = new TableMappingBase<ColumnMappingBase>(userConfigRecord, gnOuGoAgentMcpModelsUserConfigRecordTableBase, null);
            gnOuGoAgentMcpModelsUserConfigRecordTableBase.AddTypeMapping(gnOuGoAgentMcpModelsUserConfigRecordMappingBase, false);
            defaultTableMappings0.Add(gnOuGoAgentMcpModelsUserConfigRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase0, userConfigRecord.FindProperty("Id")!, gnOuGoAgentMcpModelsUserConfigRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)defaultAgentColumnBase, userConfigRecord.FindProperty("DefaultAgent")!, gnOuGoAgentMcpModelsUserConfigRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)defaultEmbeddingConfigColumnBase, userConfigRecord.FindProperty("DefaultEmbeddingConfig")!, gnOuGoAgentMcpModelsUserConfigRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)defaultLlmModelColumnBase, userConfigRecord.FindProperty("DefaultLlmModel")!, gnOuGoAgentMcpModelsUserConfigRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)defaultLlmProviderColumnBase, userConfigRecord.FindProperty("DefaultLlmProvider")!, gnOuGoAgentMcpModelsUserConfigRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)modelOverridesJsonColumnBase, userConfigRecord.FindProperty("ModelOverridesJson")!, gnOuGoAgentMcpModelsUserConfigRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)tenantIdColumnBase0, userConfigRecord.FindProperty("TenantId")!, gnOuGoAgentMcpModelsUserConfigRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)tenantScopeKeyColumnBase, userConfigRecord.FindProperty("TenantScopeKey")!, gnOuGoAgentMcpModelsUserConfigRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)updatedAtTicksColumnBase0, userConfigRecord.FindProperty("UpdatedAtTicks")!, gnOuGoAgentMcpModelsUserConfigRecordMappingBase);

            var tableMappings0 = new List<TableMapping>();
            userConfigRecord.SetRuntimeAnnotation("Relational:TableMappings", tableMappings0);
            var userConfigsTable = new Table("UserConfigs", null, relationalModel);
            var idColumn0 = new Column("Id", "TEXT", userConfigsTable);
            userConfigsTable.Columns.Add("Id", idColumn0);
            idColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(idColumn0);
            var defaultAgentColumn = new Column("DefaultAgent", "TEXT", userConfigsTable)
            {
                IsNullable = true
            };
            userConfigsTable.Columns.Add("DefaultAgent", defaultAgentColumn);
            defaultAgentColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(defaultAgentColumn);
            var defaultEmbeddingConfigColumn = new Column("DefaultEmbeddingConfig", "TEXT", userConfigsTable)
            {
                IsNullable = true
            };
            userConfigsTable.Columns.Add("DefaultEmbeddingConfig", defaultEmbeddingConfigColumn);
            defaultEmbeddingConfigColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(defaultEmbeddingConfigColumn);
            var defaultLlmModelColumn = new Column("DefaultLlmModel", "TEXT", userConfigsTable)
            {
                IsNullable = true
            };
            userConfigsTable.Columns.Add("DefaultLlmModel", defaultLlmModelColumn);
            defaultLlmModelColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(defaultLlmModelColumn);
            var defaultLlmProviderColumn = new Column("DefaultLlmProvider", "TEXT", userConfigsTable)
            {
                IsNullable = true
            };
            userConfigsTable.Columns.Add("DefaultLlmProvider", defaultLlmProviderColumn);
            defaultLlmProviderColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(defaultLlmProviderColumn);
            var modelOverridesJsonColumn = new Column("ModelOverridesJson", "TEXT", userConfigsTable)
            {
                IsNullable = true
            };
            userConfigsTable.Columns.Add("ModelOverridesJson", modelOverridesJsonColumn);
            modelOverridesJsonColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(modelOverridesJsonColumn);
            var tenantIdColumn0 = new Column("TenantId", "TEXT", userConfigsTable)
            {
                IsNullable = true
            };
            userConfigsTable.Columns.Add("TenantId", tenantIdColumn0);
            tenantIdColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(tenantIdColumn0);
            var tenantScopeKeyColumn = new Column("TenantScopeKey", "TEXT", userConfigsTable);
            userConfigsTable.Columns.Add("TenantScopeKey", tenantScopeKeyColumn);
            tenantScopeKeyColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(tenantScopeKeyColumn);
            var updatedAtTicksColumn0 = new Column("UpdatedAtTicks", "INTEGER", userConfigsTable);
            userConfigsTable.Columns.Add("UpdatedAtTicks", updatedAtTicksColumn0);
            updatedAtTicksColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<long>(updatedAtTicksColumn0);
            relationalModel.Tables.Add(("UserConfigs", null), userConfigsTable);
            var userConfigsTableMapping = new TableMapping(userConfigRecord, userConfigsTable, null);
            userConfigsTable.AddTypeMapping(userConfigsTableMapping, false);
            tableMappings0.Add(userConfigsTableMapping);
            RelationalModel.CreateColumnMapping(idColumn0, userConfigRecord.FindProperty("Id")!, userConfigsTableMapping);
            RelationalModel.CreateColumnMapping(defaultAgentColumn, userConfigRecord.FindProperty("DefaultAgent")!, userConfigsTableMapping);
            RelationalModel.CreateColumnMapping(defaultEmbeddingConfigColumn, userConfigRecord.FindProperty("DefaultEmbeddingConfig")!, userConfigsTableMapping);
            RelationalModel.CreateColumnMapping(defaultLlmModelColumn, userConfigRecord.FindProperty("DefaultLlmModel")!, userConfigsTableMapping);
            RelationalModel.CreateColumnMapping(defaultLlmProviderColumn, userConfigRecord.FindProperty("DefaultLlmProvider")!, userConfigsTableMapping);
            RelationalModel.CreateColumnMapping(modelOverridesJsonColumn, userConfigRecord.FindProperty("ModelOverridesJson")!, userConfigsTableMapping);
            RelationalModel.CreateColumnMapping(tenantIdColumn0, userConfigRecord.FindProperty("TenantId")!, userConfigsTableMapping);
            RelationalModel.CreateColumnMapping(tenantScopeKeyColumn, userConfigRecord.FindProperty("TenantScopeKey")!, userConfigsTableMapping);
            RelationalModel.CreateColumnMapping(updatedAtTicksColumn0, userConfigRecord.FindProperty("UpdatedAtTicks")!, userConfigsTableMapping);
            var pK_UserConfigs = new UniqueConstraint("PK_UserConfigs", userConfigsTable, new[] { idColumn0 });
            userConfigsTable.PrimaryKey = pK_UserConfigs;
            pK_UserConfigs.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<Guid>(pK_UserConfigs));
            var pK_UserConfigsKey = RelationalModel.GetKey(this,
                "GnOuGo.Agent.Mcp.Models.UserConfigRecord",
                new[] { "Id" });
            pK_UserConfigs.MappedKeys.Add(pK_UserConfigsKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_UserConfigsKey).Add(pK_UserConfigs);
            userConfigsTable.UniqueConstraints.Add("PK_UserConfigs", pK_UserConfigs);
            var iX_UserConfigs_TenantId = new TableIndex(
            "IX_UserConfigs_TenantId", userConfigsTable, new[] { tenantIdColumn0 }, false);
            iX_UserConfigs_TenantId.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<Guid>(iX_UserConfigs_TenantId));
            var iX_UserConfigs_TenantIdIx = RelationalModel.GetIndex(this,
                "GnOuGo.Agent.Mcp.Models.UserConfigRecord",
                new[] { "TenantId" });
            iX_UserConfigs_TenantId.MappedIndexes.Add(iX_UserConfigs_TenantIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_UserConfigs_TenantIdIx).Add(iX_UserConfigs_TenantId);
            userConfigsTable.Indexes.Add("IX_UserConfigs_TenantId", iX_UserConfigs_TenantId);
            var iX_UserConfigs_TenantScopeKey = new TableIndex(
            "IX_UserConfigs_TenantScopeKey", userConfigsTable, new[] { tenantScopeKeyColumn }, true);
            iX_UserConfigs_TenantScopeKey.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<string>(iX_UserConfigs_TenantScopeKey));
            var iX_UserConfigs_TenantScopeKeyIx = RelationalModel.GetIndex(this,
                "GnOuGo.Agent.Mcp.Models.UserConfigRecord",
                new[] { "TenantScopeKey" });
            iX_UserConfigs_TenantScopeKey.MappedIndexes.Add(iX_UserConfigs_TenantScopeKeyIx);
            RelationalModel.GetOrCreateTableIndexes(iX_UserConfigs_TenantScopeKeyIx).Add(iX_UserConfigs_TenantScopeKey);
            userConfigsTable.Indexes.Add("IX_UserConfigs_TenantScopeKey", iX_UserConfigs_TenantScopeKey);
            return relationalModel.MakeReadOnly();
        }
    }
}
