// <auto-generated />
using GnOuGo.Agent.Mcp.Data;
using GnOuGo.Agent.Mcp.Data.CompiledModels;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(AgentDbContext), typeof(AgentDbContextModel))]
