// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using GnOuGo.Agent.Mcp.Models;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;

#pragma warning disable 219, 612, 618
#nullable disable

namespace GnOuGo.Agent.Mcp.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class AgentDefinitionEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "GnOuGo.Agent.Mcp.Models.AgentDefinition",
                typeof(AgentDefinition),
                baseEntityType,
                propertyCount: 9,
                unnamedIndexCount: 2,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(AgentDefinition).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AgentDefinition).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.SetGetter(
                Guid (AgentDefinition instance) => AgentDefinitionUnsafeAccessors.Id(instance),
                bool (AgentDefinition instance) => AgentDefinitionUnsafeAccessors.Id(instance) == new Guid("00000000-0000-0000-0000-000000000000"));
            id.SetSetter(
                AgentDefinition (AgentDefinition instance, Guid value) =>
                {
                    AgentDefinitionUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                AgentDefinition (AgentDefinition instance, Guid value) =>
                {
                    AgentDefinitionUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                Guid (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<Guid>(0) : (entry.FlaggedAsTemporary(0) && AgentDefinitionUnsafeAccessors.Id(((AgentDefinition)(entry.Entity))) == new Guid("00000000-0000-0000-0000-000000000000") ? entry.ReadTemporaryValue<Guid>(0) : AgentDefinitionUnsafeAccessors.Id(((AgentDefinition)(entry.Entity))))),
                Guid (IInternalEntry entry) => AgentDefinitionUnsafeAccessors.Id(((AgentDefinition)(entry.Entity))),
                Guid (IInternalEntry entry) => entry.ReadOriginalValue<Guid>(id, 0),
                Guid (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<Guid>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = SqliteGuidTypeMapping.Default;
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<Guid>(id));

            var createdAtTicks = runtimeEntityType.AddProperty(
                "CreatedAtTicks",
                typeof(long),
                propertyInfo: typeof(AgentDefinition).GetProperty("CreatedAtTicks", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AgentDefinition).GetField("<CreatedAtTicks>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            createdAtTicks.SetGetter(
                long (AgentDefinition instance) => AgentDefinitionUnsafeAccessors.CreatedAtTicks(instance),
                bool (AgentDefinition instance) => AgentDefinitionUnsafeAccessors.CreatedAtTicks(instance) == 0L);
            createdAtTicks.SetSetter(
                AgentDefinition (AgentDefinition instance, long value) =>
                {
                    AgentDefinitionUnsafeAccessors.CreatedAtTicks(instance) = value;
                    return instance;
                });
            createdAtTicks.SetMaterializationSetter(
                AgentDefinition (AgentDefinition instance, long value) =>
                {
                    AgentDefinitionUnsafeAccessors.CreatedAtTicks(instance) = value;
                    return instance;
                });
            createdAtTicks.SetAccessors(
                long (IInternalEntry entry) => AgentDefinitionUnsafeAccessors.CreatedAtTicks(((AgentDefinition)(entry.Entity))),
                long (IInternalEntry entry) => AgentDefinitionUnsafeAccessors.CreatedAtTicks(((AgentDefinition)(entry.Entity))),
                long (IInternalEntry entry) => entry.ReadOriginalValue<long>(createdAtTicks, 1),
                long (IInternalEntry entry) => entry.GetCurrentValue<long>(createdAtTicks));
            createdAtTicks.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            createdAtTicks.TypeMapping = LongTypeMapping.Default.Clone(
                comparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                keyComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                providerValueComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var name = runtimeEntityType.AddProperty(
                "Name",
                typeof(string),
                propertyInfo: typeof(AgentDefinition).GetProperty("Name", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AgentDefinition).GetField("<Name>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 256);
            name.SetGetter(
                string (AgentDefinition instance) => AgentDefinitionUnsafeAccessors.Name(instance),
                bool (AgentDefinition instance) => AgentDefinitionUnsafeAccessors.Name(instance) == null);
            name.SetSetter(
                AgentDefinition (AgentDefinition instance, string value) =>
                {
                    AgentDefinitionUnsafeAccessors.Name(instance) = value;
                    return instance;
                });
            name.SetMaterializationSetter(
                AgentDefinition (AgentDefinition instance, string value) =>
                {
                    AgentDefinitionUnsafeAccessors.Name(instance) = value;
                    return instance;
                });
            name.SetAccessors(
                string (IInternalEntry entry) => AgentDefinitionUnsafeAccessors.Name(((AgentDefinition)(entry.Entity))),
                string (IInternalEntry entry) => AgentDefinitionUnsafeAccessors.Name(((AgentDefinition)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(name, 2),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(name));
            name.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            name.TypeMapping = SqliteStringTypeMapping.Default;
            name.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(name));

            var originalPrompt = runtimeEntityType.AddProperty(
                "OriginalPrompt",
                typeof(string),
                propertyInfo: typeof(AgentDefinition).GetProperty("OriginalPrompt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AgentDefinition).GetField("<OriginalPrompt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            originalPrompt.SetGetter(
                string (AgentDefinition instance) => AgentDefinitionUnsafeAccessors.OriginalPrompt(instance),
                bool (AgentDefinition instance) => AgentDefinitionUnsafeAccessors.OriginalPrompt(instance) == null);
            originalPrompt.SetSetter(
                AgentDefinition (AgentDefinition instance, string value) =>
                {
                    AgentDefinitionUnsafeAccessors.OriginalPrompt(instance) = value;
                    return instance;
                });
            originalPrompt.SetMaterializationSetter(
                AgentDefinition (AgentDefinition instance, string value) =>
                {
                    AgentDefinitionUnsafeAccessors.OriginalPrompt(instance) = value;
                    return instance;
                });
            originalPrompt.SetAccessors(
                string (IInternalEntry entry) => AgentDefinitionUnsafeAccessors.OriginalPrompt(((AgentDefinition)(entry.Entity))),
                string (IInternalEntry entry) => AgentDefinitionUnsafeAccessors.OriginalPrompt(((AgentDefinition)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(originalPrompt, 3),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(originalPrompt));
            originalPrompt.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            originalPrompt.TypeMapping = SqliteStringTypeMapping.Default;

            var scheduleDescription = runtimeEntityType.AddProperty(
                "ScheduleDescription",
                typeof(string),
                propertyInfo: typeof(AgentDefinition).GetProperty("ScheduleDescription", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AgentDefinition).GetField("<ScheduleDescription>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            scheduleDescription.SetGetter(
                string (AgentDefinition instance) => AgentDefinitionUnsafeAccessors.ScheduleDescription(instance),
                bool (AgentDefinition instance) => AgentDefinitionUnsafeAccessors.ScheduleDescription(instance) == null);
            scheduleDescription.SetSetter(
                AgentDefinition (AgentDefinition instance, string value) =>
                {
                    AgentDefinitionUnsafeAccessors.ScheduleDescription(instance) = value;
                    return instance;
                });
            scheduleDescription.SetMaterializationSetter(
                AgentDefinition (AgentDefinition instance, string value) =>
                {
                    AgentDefinitionUnsafeAccessors.ScheduleDescription(instance) = value;
                    return instance;
                });
            scheduleDescription.SetAccessors(
                string (IInternalEntry entry) => AgentDefinitionUnsafeAccessors.ScheduleDescription(((AgentDefinition)(entry.Entity))),
                string (IInternalEntry entry) => AgentDefinitionUnsafeAccessors.ScheduleDescription(((AgentDefinition)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(scheduleDescription, 4),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(scheduleDescription));
            scheduleDescription.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            scheduleDescription.TypeMapping = SqliteStringTypeMapping.Default;

            var schedulesJson = runtimeEntityType.AddProperty(
                "SchedulesJson",
                typeof(string),
                propertyInfo: typeof(AgentDefinition).GetProperty("SchedulesJson", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AgentDefinition).GetField("<SchedulesJson>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd);
            schedulesJson.SetGetter(
                string (AgentDefinition instance) => AgentDefinitionUnsafeAccessors.SchedulesJson(instance),
                bool (AgentDefinition instance) => AgentDefinitionUnsafeAccessors.SchedulesJson(instance) == null);
            schedulesJson.SetSetter(
                AgentDefinition (AgentDefinition instance, string value) =>
                {
                    AgentDefinitionUnsafeAccessors.SchedulesJson(instance) = value;
                    return instance;
                });
            schedulesJson.SetMaterializationSetter(
                AgentDefinition (AgentDefinition instance, string value) =>
                {
                    AgentDefinitionUnsafeAccessors.SchedulesJson(instance) = value;
                    return instance;
                });
            schedulesJson.SetAccessors(
                string (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(5) ? entry.ReadStoreGeneratedValue<string>(1) : (entry.FlaggedAsTemporary(5) && AgentDefinitionUnsafeAccessors.SchedulesJson(((AgentDefinition)(entry.Entity))) == null ? entry.ReadTemporaryValue<string>(1) : AgentDefinitionUnsafeAccessors.SchedulesJson(((AgentDefinition)(entry.Entity))))),
                string (IInternalEntry entry) => AgentDefinitionUnsafeAccessors.SchedulesJson(((AgentDefinition)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(schedulesJson, 5),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(schedulesJson));
            schedulesJson.SetPropertyIndexes(
                index: 5,
                originalValueIndex: 5,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: 1);
            schedulesJson.TypeMapping = SqliteStringTypeMapping.Default;
            schedulesJson.AddAnnotation("Relational:ColumnName", "SchedulesJson");
            schedulesJson.AddAnnotation("Relational:DefaultValue", "[]");

            var tenantId = runtimeEntityType.AddProperty(
                "TenantId",
                typeof(Guid?),
                propertyInfo: typeof(AgentDefinition).GetProperty("TenantId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AgentDefinition).GetField("<TenantId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            tenantId.SetGetter(
                Guid? (AgentDefinition instance) => AgentDefinitionUnsafeAccessors.TenantId(instance),
                bool (AgentDefinition instance) => !(AgentDefinitionUnsafeAccessors.TenantId(instance).HasValue));
            tenantId.SetSetter(
                AgentDefinition (AgentDefinition instance, Guid? value) =>
                {
                    AgentDefinitionUnsafeAccessors.TenantId(instance) = value;
                    return instance;
                });
            tenantId.SetMaterializationSetter(
                AgentDefinition (AgentDefinition instance, Guid? value) =>
                {
                    AgentDefinitionUnsafeAccessors.TenantId(instance) = value;
                    return instance;
                });
            tenantId.SetAccessors(
                Guid? (IInternalEntry entry) => AgentDefinitionUnsafeAccessors.TenantId(((AgentDefinition)(entry.Entity))),
                Guid? (IInternalEntry entry) => AgentDefinitionUnsafeAccessors.TenantId(((AgentDefinition)(entry.Entity))),
                Guid? (IInternalEntry entry) => entry.ReadOriginalValue<Guid?>(tenantId, 6),
                Guid? (IInternalEntry entry) => entry.GetCurrentValue<Guid?>(tenantId));
            tenantId.SetPropertyIndexes(
                index: 6,
                originalValueIndex: 6,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            tenantId.TypeMapping = SqliteGuidTypeMapping.Default;
            tenantId.SetCurrentValueComparer(new EntryCurrentValueComparer<Guid?>(tenantId));
            tenantId.SetComparer(new NullableValueComparer<Guid>(tenantId.TypeMapping.Comparer));
            tenantId.SetKeyComparer(new NullableValueComparer<Guid>(tenantId.TypeMapping.KeyComparer));

            var updatedAtTicks = runtimeEntityType.AddProperty(
                "UpdatedAtTicks",
                typeof(long),
                propertyInfo: typeof(AgentDefinition).GetProperty("UpdatedAtTicks", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AgentDefinition).GetField("<UpdatedAtTicks>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            updatedAtTicks.SetGetter(
                long (AgentDefinition instance) => AgentDefinitionUnsafeAccessors.UpdatedAtTicks(instance),
                bool (AgentDefinition instance) => AgentDefinitionUnsafeAccessors.UpdatedAtTicks(instance) == 0L);
            updatedAtTicks.SetSetter(
                AgentDefinition (AgentDefinition instance, long value) =>
                {
                    AgentDefinitionUnsafeAccessors.UpdatedAtTicks(instance) = value;
                    return instance;
                });
            updatedAtTicks.SetMaterializationSetter(
                AgentDefinition (AgentDefinition instance, long value) =>
                {
                    AgentDefinitionUnsafeAccessors.UpdatedAtTicks(instance) = value;
                    return instance;
                });
            updatedAtTicks.SetAccessors(
                long (IInternalEntry entry) => AgentDefinitionUnsafeAccessors.UpdatedAtTicks(((AgentDefinition)(entry.Entity))),
                long (IInternalEntry entry) => AgentDefinitionUnsafeAccessors.UpdatedAtTicks(((AgentDefinition)(entry.Entity))),
                long (IInternalEntry entry) => entry.ReadOriginalValue<long>(updatedAtTicks, 7),
                long (IInternalEntry entry) => entry.GetCurrentValue<long>(updatedAtTicks));
            updatedAtTicks.SetPropertyIndexes(
                index: 7,
                originalValueIndex: 7,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            updatedAtTicks.TypeMapping = LongTypeMapping.Default.Clone(
                comparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                keyComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                providerValueComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var workflow = runtimeEntityType.AddProperty(
                "Workflow",
                typeof(string),
                propertyInfo: typeof(AgentDefinition).GetProperty("Workflow", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AgentDefinition).GetField("<Workflow>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            workflow.SetGetter(
                string (AgentDefinition instance) => AgentDefinitionUnsafeAccessors.Workflow(instance),
                bool (AgentDefinition instance) => AgentDefinitionUnsafeAccessors.Workflow(instance) == null);
            workflow.SetSetter(
                AgentDefinition (AgentDefinition instance, string value) =>
                {
                    AgentDefinitionUnsafeAccessors.Workflow(instance) = value;
                    return instance;
                });
            workflow.SetMaterializationSetter(
                AgentDefinition (AgentDefinition instance, string value) =>
                {
                    AgentDefinitionUnsafeAccessors.Workflow(instance) = value;
                    return instance;
                });
            workflow.SetAccessors(
                string (IInternalEntry entry) => AgentDefinitionUnsafeAccessors.Workflow(((AgentDefinition)(entry.Entity))),
                string (IInternalEntry entry) => AgentDefinitionUnsafeAccessors.Workflow(((AgentDefinition)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(workflow, 8),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(workflow));
            workflow.SetPropertyIndexes(
                index: 8,
                originalValueIndex: 8,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            workflow.TypeMapping = SqliteStringTypeMapping.Default;

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { tenantId });

            var index0 = runtimeEntityType.AddIndex(
                new[] { name, tenantId },
                unique: true);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var createdAtTicks = runtimeEntityType.FindProperty("CreatedAtTicks");
            var name = runtimeEntityType.FindProperty("Name");
            var originalPrompt = runtimeEntityType.FindProperty("OriginalPrompt");
            var scheduleDescription = runtimeEntityType.FindProperty("ScheduleDescription");
            var schedulesJson = runtimeEntityType.FindProperty("SchedulesJson");
            var tenantId = runtimeEntityType.FindProperty("TenantId");
            var updatedAtTicks = runtimeEntityType.FindProperty("UpdatedAtTicks");
            var workflow = runtimeEntityType.FindProperty("Workflow");
            var key = runtimeEntityType.FindKey(new[] { id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<Guid>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<Guid>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((AgentDefinition)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid, long, string, string, string, string, Guid?, long, string>(((ValueComparer<Guid>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid>(id)), ((ValueComparer<long>)(((IProperty)createdAtTicks).GetValueComparer())).Snapshot(source.GetCurrentValue<long>(createdAtTicks)), (source.GetCurrentValue<string>(name) == null ? null : ((ValueComparer<string>)(((IProperty)name).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(name))), (source.GetCurrentValue<string>(originalPrompt) == null ? null : ((ValueComparer<string>)(((IProperty)originalPrompt).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(originalPrompt))), (source.GetCurrentValue<string>(scheduleDescription) == null ? null : ((ValueComparer<string>)(((IProperty)scheduleDescription).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(scheduleDescription))), (source.GetCurrentValue<string>(schedulesJson) == null ? null : ((ValueComparer<string>)(((IProperty)schedulesJson).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(schedulesJson))), (source.GetCurrentValue<Guid?>(tenantId) == null ? null : ((ValueComparer<Guid?>)(((IProperty)tenantId).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid?>(tenantId))), ((ValueComparer<long>)(((IProperty)updatedAtTicks).GetValueComparer())).Snapshot(source.GetCurrentValue<long>(updatedAtTicks)), (source.GetCurrentValue<string>(workflow) == null ? null : ((ValueComparer<string>)(((IProperty)workflow).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(workflow))))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<Guid, string>(((ValueComparer<Guid>)(((IProperty)id).GetValueComparer())).Snapshot(default(Guid)), (default(string) == null ? null : ((ValueComparer<string>)(((IProperty)schedulesJson).GetValueComparer())).Snapshot(default(string)))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<Guid, string>(default(Guid), default(string)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((AgentDefinition)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid>(((ValueComparer<Guid>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<Guid>(id)))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 9,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 9,
                shadowCount: 0,
                relationshipCount: 1,
                storeGeneratedCount: 2));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Agents");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
