// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using GnOuGo.Agent.Mcp.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace GnOuGo.Agent.Mcp.Data.CompiledModels
{
    public static class AgentDefinitionUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref Guid Id(AgentDefinition @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAtTicks>k__BackingField")]
        public static extern ref long CreatedAtTicks(AgentDefinition @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
        public static extern ref string Name(AgentDefinition @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<OriginalPrompt>k__BackingField")]
        public static extern ref string OriginalPrompt(AgentDefinition @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ScheduleDescription>k__BackingField")]
        public static extern ref string ScheduleDescription(AgentDefinition @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SchedulesJson>k__BackingField")]
        public static extern ref string SchedulesJson(AgentDefinition @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TenantId>k__BackingField")]
        public static extern ref Guid? TenantId(AgentDefinition @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UpdatedAtTicks>k__BackingField")]
        public static extern ref long UpdatedAtTicks(AgentDefinition @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Workflow>k__BackingField")]
        public static extern ref string Workflow(AgentDefinition @this);
    }
}
