// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using GnOuGo.Agent.Mcp.Models;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;

#pragma warning disable 219, 612, 618
#nullable disable

namespace GnOuGo.Agent.Mcp.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class UserConfigRecordEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "GnOuGo.Agent.Mcp.Models.UserConfigRecord",
                typeof(UserConfigRecord),
                baseEntityType,
                propertyCount: 9,
                unnamedIndexCount: 2,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(UserConfigRecord).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UserConfigRecord).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.SetGetter(
                Guid (UserConfigRecord instance) => UserConfigRecordUnsafeAccessors.Id(instance),
                bool (UserConfigRecord instance) => UserConfigRecordUnsafeAccessors.Id(instance) == new Guid("00000000-0000-0000-0000-000000000000"));
            id.SetSetter(
                UserConfigRecord (UserConfigRecord instance, Guid value) =>
                {
                    UserConfigRecordUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                UserConfigRecord (UserConfigRecord instance, Guid value) =>
                {
                    UserConfigRecordUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                Guid (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<Guid>(0) : (entry.FlaggedAsTemporary(0) && UserConfigRecordUnsafeAccessors.Id(((UserConfigRecord)(entry.Entity))) == new Guid("00000000-0000-0000-0000-000000000000") ? entry.ReadTemporaryValue<Guid>(0) : UserConfigRecordUnsafeAccessors.Id(((UserConfigRecord)(entry.Entity))))),
                Guid (IInternalEntry entry) => UserConfigRecordUnsafeAccessors.Id(((UserConfigRecord)(entry.Entity))),
                Guid (IInternalEntry entry) => entry.ReadOriginalValue<Guid>(id, 0),
                Guid (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<Guid>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = SqliteGuidTypeMapping.Default;
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<Guid>(id));

            var defaultAgent = runtimeEntityType.AddProperty(
                "DefaultAgent",
                typeof(string),
                propertyInfo: typeof(UserConfigRecord).GetProperty("DefaultAgent", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UserConfigRecord).GetField("<DefaultAgent>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 256);
            defaultAgent.SetGetter(
                string (UserConfigRecord instance) => UserConfigRecordUnsafeAccessors.DefaultAgent(instance),
                bool (UserConfigRecord instance) => UserConfigRecordUnsafeAccessors.DefaultAgent(instance) == null);
            defaultAgent.SetSetter(
                UserConfigRecord (UserConfigRecord instance, string value) =>
                {
                    UserConfigRecordUnsafeAccessors.DefaultAgent(instance) = value;
                    return instance;
                });
            defaultAgent.SetMaterializationSetter(
                UserConfigRecord (UserConfigRecord instance, string value) =>
                {
                    UserConfigRecordUnsafeAccessors.DefaultAgent(instance) = value;
                    return instance;
                });
            defaultAgent.SetAccessors(
                string (IInternalEntry entry) => UserConfigRecordUnsafeAccessors.DefaultAgent(((UserConfigRecord)(entry.Entity))),
                string (IInternalEntry entry) => UserConfigRecordUnsafeAccessors.DefaultAgent(((UserConfigRecord)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(defaultAgent, 1),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(defaultAgent));
            defaultAgent.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            defaultAgent.TypeMapping = SqliteStringTypeMapping.Default;

            var defaultEmbeddingConfig = runtimeEntityType.AddProperty(
                "DefaultEmbeddingConfig",
                typeof(string),
                propertyInfo: typeof(UserConfigRecord).GetProperty("DefaultEmbeddingConfig", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UserConfigRecord).GetField("<DefaultEmbeddingConfig>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 256);
            defaultEmbeddingConfig.SetGetter(
                string (UserConfigRecord instance) => UserConfigRecordUnsafeAccessors.DefaultEmbeddingConfig(instance),
                bool (UserConfigRecord instance) => UserConfigRecordUnsafeAccessors.DefaultEmbeddingConfig(instance) == null);
            defaultEmbeddingConfig.SetSetter(
                UserConfigRecord (UserConfigRecord instance, string value) =>
                {
                    UserConfigRecordUnsafeAccessors.DefaultEmbeddingConfig(instance) = value;
                    return instance;
                });
            defaultEmbeddingConfig.SetMaterializationSetter(
                UserConfigRecord (UserConfigRecord instance, string value) =>
                {
                    UserConfigRecordUnsafeAccessors.DefaultEmbeddingConfig(instance) = value;
                    return instance;
                });
            defaultEmbeddingConfig.SetAccessors(
                string (IInternalEntry entry) => UserConfigRecordUnsafeAccessors.DefaultEmbeddingConfig(((UserConfigRecord)(entry.Entity))),
                string (IInternalEntry entry) => UserConfigRecordUnsafeAccessors.DefaultEmbeddingConfig(((UserConfigRecord)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(defaultEmbeddingConfig, 2),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(defaultEmbeddingConfig));
            defaultEmbeddingConfig.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            defaultEmbeddingConfig.TypeMapping = SqliteStringTypeMapping.Default;

            var defaultLlmModel = runtimeEntityType.AddProperty(
                "DefaultLlmModel",
                typeof(string),
                propertyInfo: typeof(UserConfigRecord).GetProperty("DefaultLlmModel", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UserConfigRecord).GetField("<DefaultLlmModel>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 256);
            defaultLlmModel.SetGetter(
                string (UserConfigRecord instance) => UserConfigRecordUnsafeAccessors.DefaultLlmModel(instance),
                bool (UserConfigRecord instance) => UserConfigRecordUnsafeAccessors.DefaultLlmModel(instance) == null);
            defaultLlmModel.SetSetter(
                UserConfigRecord (UserConfigRecord instance, string value) =>
                {
                    UserConfigRecordUnsafeAccessors.DefaultLlmModel(instance) = value;
                    return instance;
                });
            defaultLlmModel.SetMaterializationSetter(
                UserConfigRecord (UserConfigRecord instance, string value) =>
                {
                    UserConfigRecordUnsafeAccessors.DefaultLlmModel(instance) = value;
                    return instance;
                });
            defaultLlmModel.SetAccessors(
                string (IInternalEntry entry) => UserConfigRecordUnsafeAccessors.DefaultLlmModel(((UserConfigRecord)(entry.Entity))),
                string (IInternalEntry entry) => UserConfigRecordUnsafeAccessors.DefaultLlmModel(((UserConfigRecord)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(defaultLlmModel, 3),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(defaultLlmModel));
            defaultLlmModel.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            defaultLlmModel.TypeMapping = SqliteStringTypeMapping.Default;

            var defaultLlmProvider = runtimeEntityType.AddProperty(
                "DefaultLlmProvider",
                typeof(string),
                propertyInfo: typeof(UserConfigRecord).GetProperty("DefaultLlmProvider", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UserConfigRecord).GetField("<DefaultLlmProvider>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 256);
            defaultLlmProvider.SetGetter(
                string (UserConfigRecord instance) => UserConfigRecordUnsafeAccessors.DefaultLlmProvider(instance),
                bool (UserConfigRecord instance) => UserConfigRecordUnsafeAccessors.DefaultLlmProvider(instance) == null);
            defaultLlmProvider.SetSetter(
                UserConfigRecord (UserConfigRecord instance, string value) =>
                {
                    UserConfigRecordUnsafeAccessors.DefaultLlmProvider(instance) = value;
                    return instance;
                });
            defaultLlmProvider.SetMaterializationSetter(
                UserConfigRecord (UserConfigRecord instance, string value) =>
                {
                    UserConfigRecordUnsafeAccessors.DefaultLlmProvider(instance) = value;
                    return instance;
                });
            defaultLlmProvider.SetAccessors(
                string (IInternalEntry entry) => UserConfigRecordUnsafeAccessors.DefaultLlmProvider(((UserConfigRecord)(entry.Entity))),
                string (IInternalEntry entry) => UserConfigRecordUnsafeAccessors.DefaultLlmProvider(((UserConfigRecord)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(defaultLlmProvider, 4),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(defaultLlmProvider));
            defaultLlmProvider.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            defaultLlmProvider.TypeMapping = SqliteStringTypeMapping.Default;

            var modelOverridesJson = runtimeEntityType.AddProperty(
                "ModelOverridesJson",
                typeof(string),
                propertyInfo: typeof(UserConfigRecord).GetProperty("ModelOverridesJson", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UserConfigRecord).GetField("<ModelOverridesJson>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            modelOverridesJson.SetGetter(
                string (UserConfigRecord instance) => UserConfigRecordUnsafeAccessors.ModelOverridesJson(instance),
                bool (UserConfigRecord instance) => UserConfigRecordUnsafeAccessors.ModelOverridesJson(instance) == null);
            modelOverridesJson.SetSetter(
                UserConfigRecord (UserConfigRecord instance, string value) =>
                {
                    UserConfigRecordUnsafeAccessors.ModelOverridesJson(instance) = value;
                    return instance;
                });
            modelOverridesJson.SetMaterializationSetter(
                UserConfigRecord (UserConfigRecord instance, string value) =>
                {
                    UserConfigRecordUnsafeAccessors.ModelOverridesJson(instance) = value;
                    return instance;
                });
            modelOverridesJson.SetAccessors(
                string (IInternalEntry entry) => UserConfigRecordUnsafeAccessors.ModelOverridesJson(((UserConfigRecord)(entry.Entity))),
                string (IInternalEntry entry) => UserConfigRecordUnsafeAccessors.ModelOverridesJson(((UserConfigRecord)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(modelOverridesJson, 5),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(modelOverridesJson));
            modelOverridesJson.SetPropertyIndexes(
                index: 5,
                originalValueIndex: 5,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            modelOverridesJson.TypeMapping = SqliteStringTypeMapping.Default;

            var tenantId = runtimeEntityType.AddProperty(
                "TenantId",
                typeof(Guid?),
                propertyInfo: typeof(UserConfigRecord).GetProperty("TenantId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UserConfigRecord).GetField("<TenantId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            tenantId.SetGetter(
                Guid? (UserConfigRecord instance) => UserConfigRecordUnsafeAccessors.TenantId(instance),
                bool (UserConfigRecord instance) => !(UserConfigRecordUnsafeAccessors.TenantId(instance).HasValue));
            tenantId.SetSetter(
                UserConfigRecord (UserConfigRecord instance, Guid? value) =>
                {
                    UserConfigRecordUnsafeAccessors.TenantId(instance) = value;
                    return instance;
                });
            tenantId.SetMaterializationSetter(
                UserConfigRecord (UserConfigRecord instance, Guid? value) =>
                {
                    UserConfigRecordUnsafeAccessors.TenantId(instance) = value;
                    return instance;
                });
            tenantId.SetAccessors(
                Guid? (IInternalEntry entry) => UserConfigRecordUnsafeAccessors.TenantId(((UserConfigRecord)(entry.Entity))),
                Guid? (IInternalEntry entry) => UserConfigRecordUnsafeAccessors.TenantId(((UserConfigRecord)(entry.Entity))),
                Guid? (IInternalEntry entry) => entry.ReadOriginalValue<Guid?>(tenantId, 6),
                Guid? (IInternalEntry entry) => entry.GetCurrentValue<Guid?>(tenantId));
            tenantId.SetPropertyIndexes(
                index: 6,
                originalValueIndex: 6,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            tenantId.TypeMapping = SqliteGuidTypeMapping.Default;
            tenantId.SetComparer(new NullableValueComparer<Guid>(tenantId.TypeMapping.Comparer));
            tenantId.SetKeyComparer(new NullableValueComparer<Guid>(tenantId.TypeMapping.KeyComparer));

            var tenantScopeKey = runtimeEntityType.AddProperty(
                "TenantScopeKey",
                typeof(string),
                propertyInfo: typeof(UserConfigRecord).GetProperty("TenantScopeKey", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UserConfigRecord).GetField("<TenantScopeKey>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 64);
            tenantScopeKey.SetGetter(
                string (UserConfigRecord instance) => UserConfigRecordUnsafeAccessors.TenantScopeKey(instance),
                bool (UserConfigRecord instance) => UserConfigRecordUnsafeAccessors.TenantScopeKey(instance) == null);
            tenantScopeKey.SetSetter(
                UserConfigRecord (UserConfigRecord instance, string value) =>
                {
                    UserConfigRecordUnsafeAccessors.TenantScopeKey(instance) = value;
                    return instance;
                });
            tenantScopeKey.SetMaterializationSetter(
                UserConfigRecord (UserConfigRecord instance, string value) =>
                {
                    UserConfigRecordUnsafeAccessors.TenantScopeKey(instance) = value;
                    return instance;
                });
            tenantScopeKey.SetAccessors(
                string (IInternalEntry entry) => UserConfigRecordUnsafeAccessors.TenantScopeKey(((UserConfigRecord)(entry.Entity))),
                string (IInternalEntry entry) => UserConfigRecordUnsafeAccessors.TenantScopeKey(((UserConfigRecord)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(tenantScopeKey, 7),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(tenantScopeKey));
            tenantScopeKey.SetPropertyIndexes(
                index: 7,
                originalValueIndex: 7,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            tenantScopeKey.TypeMapping = SqliteStringTypeMapping.Default;
            tenantScopeKey.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(tenantScopeKey));

            var updatedAtTicks = runtimeEntityType.AddProperty(
                "UpdatedAtTicks",
                typeof(long),
                propertyInfo: typeof(UserConfigRecord).GetProperty("UpdatedAtTicks", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UserConfigRecord).GetField("<UpdatedAtTicks>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            updatedAtTicks.SetGetter(
                long (UserConfigRecord instance) => UserConfigRecordUnsafeAccessors.UpdatedAtTicks(instance),
                bool (UserConfigRecord instance) => UserConfigRecordUnsafeAccessors.UpdatedAtTicks(instance) == 0L);
            updatedAtTicks.SetSetter(
                UserConfigRecord (UserConfigRecord instance, long value) =>
                {
                    UserConfigRecordUnsafeAccessors.UpdatedAtTicks(instance) = value;
                    return instance;
                });
            updatedAtTicks.SetMaterializationSetter(
                UserConfigRecord (UserConfigRecord instance, long value) =>
                {
                    UserConfigRecordUnsafeAccessors.UpdatedAtTicks(instance) = value;
                    return instance;
                });
            updatedAtTicks.SetAccessors(
                long (IInternalEntry entry) => UserConfigRecordUnsafeAccessors.UpdatedAtTicks(((UserConfigRecord)(entry.Entity))),
                long (IInternalEntry entry) => UserConfigRecordUnsafeAccessors.UpdatedAtTicks(((UserConfigRecord)(entry.Entity))),
                long (IInternalEntry entry) => entry.ReadOriginalValue<long>(updatedAtTicks, 8),
                long (IInternalEntry entry) => entry.GetCurrentValue<long>(updatedAtTicks));
            updatedAtTicks.SetPropertyIndexes(
                index: 8,
                originalValueIndex: 8,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            updatedAtTicks.TypeMapping = LongTypeMapping.Default.Clone(
                comparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                keyComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                providerValueComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { tenantId });

            var index0 = runtimeEntityType.AddIndex(
                new[] { tenantScopeKey },
                unique: true);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var defaultAgent = runtimeEntityType.FindProperty("DefaultAgent");
            var defaultEmbeddingConfig = runtimeEntityType.FindProperty("DefaultEmbeddingConfig");
            var defaultLlmModel = runtimeEntityType.FindProperty("DefaultLlmModel");
            var defaultLlmProvider = runtimeEntityType.FindProperty("DefaultLlmProvider");
            var modelOverridesJson = runtimeEntityType.FindProperty("ModelOverridesJson");
            var tenantId = runtimeEntityType.FindProperty("TenantId");
            var tenantScopeKey = runtimeEntityType.FindProperty("TenantScopeKey");
            var updatedAtTicks = runtimeEntityType.FindProperty("UpdatedAtTicks");
            var key = runtimeEntityType.FindKey(new[] { id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<Guid>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<Guid>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((UserConfigRecord)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid, string, string, string, string, string, Guid?, string, long>(((ValueComparer<Guid>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid>(id)), (source.GetCurrentValue<string>(defaultAgent) == null ? null : ((ValueComparer<string>)(((IProperty)defaultAgent).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(defaultAgent))), (source.GetCurrentValue<string>(defaultEmbeddingConfig) == null ? null : ((ValueComparer<string>)(((IProperty)defaultEmbeddingConfig).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(defaultEmbeddingConfig))), (source.GetCurrentValue<string>(defaultLlmModel) == null ? null : ((ValueComparer<string>)(((IProperty)defaultLlmModel).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(defaultLlmModel))), (source.GetCurrentValue<string>(defaultLlmProvider) == null ? null : ((ValueComparer<string>)(((IProperty)defaultLlmProvider).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(defaultLlmProvider))), (source.GetCurrentValue<string>(modelOverridesJson) == null ? null : ((ValueComparer<string>)(((IProperty)modelOverridesJson).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(modelOverridesJson))), (source.GetCurrentValue<Guid?>(tenantId) == null ? null : ((ValueComparer<Guid?>)(((IProperty)tenantId).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid?>(tenantId))), (source.GetCurrentValue<string>(tenantScopeKey) == null ? null : ((ValueComparer<string>)(((IProperty)tenantScopeKey).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(tenantScopeKey))), ((ValueComparer<long>)(((IProperty)updatedAtTicks).GetValueComparer())).Snapshot(source.GetCurrentValue<long>(updatedAtTicks)))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<Guid>(((ValueComparer<Guid>)(((IProperty)id).GetValueComparer())).Snapshot(default(Guid))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<Guid>(default(Guid)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((UserConfigRecord)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid>(((ValueComparer<Guid>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<Guid>(id)))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 9,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 9,
                shadowCount: 0,
                relationshipCount: 1,
                storeGeneratedCount: 1));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "UserConfigs");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
