// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using GnOuGo.Agent.Mcp.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace GnOuGo.Agent.Mcp.Data.CompiledModels
{
    public static class UserConfigRecordUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref Guid Id(UserConfigRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<DefaultAgent>k__BackingField")]
        public static extern ref string DefaultAgent(UserConfigRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<DefaultEmbeddingConfig>k__BackingField")]
        public static extern ref string DefaultEmbeddingConfig(UserConfigRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<DefaultLlmModel>k__BackingField")]
        public static extern ref string DefaultLlmModel(UserConfigRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<DefaultLlmProvider>k__BackingField")]
        public static extern ref string DefaultLlmProvider(UserConfigRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ModelOverridesJson>k__BackingField")]
        public static extern ref string ModelOverridesJson(UserConfigRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TenantId>k__BackingField")]
        public static extern ref Guid? TenantId(UserConfigRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TenantScopeKey>k__BackingField")]
        public static extern ref string TenantScopeKey(UserConfigRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UpdatedAtTicks>k__BackingField")]
        public static extern ref long UpdatedAtTicks(UserConfigRecord @this);
    }
}
