// <auto-generated />
using GnOuGo.Flow.Persistence;
using GnOuGo.Flow.Persistence.CompiledModels;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(WorkflowRunDbContext), typeof(WorkflowRunDbContextModel))]
