// <auto-generated />
using System;
using System.Runtime.CompilerServices;

#pragma warning disable 219, 612, 618
#nullable disable

namespace GnOuGo.Flow.Persistence.CompiledModels
{
    public static class WorkflowRunIndexUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TenantId>k__BackingField")]
        public static extern ref string TenantId(WorkflowRunIndex @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<RunId>k__BackingField")]
        public static extern ref string RunId(WorkflowRunIndex @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Revision>k__BackingField")]
        public static extern ref long Revision(WorkflowRunIndex @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Status>k__BackingField")]
        public static extern ref string Status(WorkflowRunIndex @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UpdatedAtTicks>k__BackingField")]
        public static extern ref long UpdatedAtTicks(WorkflowRunIndex @this);
    }
}
