// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Update.Internal;

#pragma warning disable 219, 612, 618
#nullable disable

namespace GnOuGo.Flow.Persistence.CompiledModels
{
    public partial class WorkflowRunDbContextModel
    {
        private WorkflowRunDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("405583df-f607-460b-8111-f30206b1354a"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var workflowRunIndex = WorkflowRunIndexEntityType.Create(this);

            WorkflowRunIndexEntityType.CreateAnnotations(workflowRunIndex);

            AddAnnotation("ProductVersion", "10.0.12");
            AddRuntimeAnnotation("Relational:RelationalModelFactory", () => CreateRelationalModel());
        }

        private IRelationalModel CreateRelationalModel()
        {
            var relationalModel = new RelationalModel(this);

            var workflowRunIndex = FindEntityType("GnOuGo.Flow.Persistence.WorkflowRunIndex")!;

            var defaultTableMappings = new List<TableMappingBase<ColumnMappingBase>>();
            workflowRunIndex.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings);
            var gnOuGoFlowPersistenceWorkflowRunIndexTableBase = new TableBase("GnOuGo.Flow.Persistence.WorkflowRunIndex", null, relationalModel);
            var revisionColumnBase = new ColumnBase<ColumnMappingBase>("Revision", "INTEGER", gnOuGoFlowPersistenceWorkflowRunIndexTableBase);
            gnOuGoFlowPersistenceWorkflowRunIndexTableBase.Columns.Add("Revision", revisionColumnBase);
            var runIdColumnBase = new ColumnBase<ColumnMappingBase>("RunId", "TEXT", gnOuGoFlowPersistenceWorkflowRunIndexTableBase);
            gnOuGoFlowPersistenceWorkflowRunIndexTableBase.Columns.Add("RunId", runIdColumnBase);
            var statusColumnBase = new ColumnBase<ColumnMappingBase>("Status", "TEXT", gnOuGoFlowPersistenceWorkflowRunIndexTableBase);
            gnOuGoFlowPersistenceWorkflowRunIndexTableBase.Columns.Add("Status", statusColumnBase);
            var tenantIdColumnBase = new ColumnBase<ColumnMappingBase>("TenantId", "TEXT", gnOuGoFlowPersistenceWorkflowRunIndexTableBase);
            gnOuGoFlowPersistenceWorkflowRunIndexTableBase.Columns.Add("TenantId", tenantIdColumnBase);
            var updatedAtTicksColumnBase = new ColumnBase<ColumnMappingBase>("UpdatedAtTicks", "INTEGER", gnOuGoFlowPersistenceWorkflowRunIndexTableBase);
            gnOuGoFlowPersistenceWorkflowRunIndexTableBase.Columns.Add("UpdatedAtTicks", updatedAtTicksColumnBase);
            relationalModel.DefaultTables.Add("GnOuGo.Flow.Persistence.WorkflowRunIndex", gnOuGoFlowPersistenceWorkflowRunIndexTableBase);
            var gnOuGoFlowPersistenceWorkflowRunIndexMappingBase = new TableMappingBase<ColumnMappingBase>(workflowRunIndex, gnOuGoFlowPersistenceWorkflowRunIndexTableBase, null);
            gnOuGoFlowPersistenceWorkflowRunIndexTableBase.AddTypeMapping(gnOuGoFlowPersistenceWorkflowRunIndexMappingBase, false);
            defaultTableMappings.Add(gnOuGoFlowPersistenceWorkflowRunIndexMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)runIdColumnBase, workflowRunIndex.FindProperty("RunId")!, gnOuGoFlowPersistenceWorkflowRunIndexMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)tenantIdColumnBase, workflowRunIndex.FindProperty("TenantId")!, gnOuGoFlowPersistenceWorkflowRunIndexMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)revisionColumnBase, workflowRunIndex.FindProperty("Revision")!, gnOuGoFlowPersistenceWorkflowRunIndexMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)statusColumnBase, workflowRunIndex.FindProperty("Status")!, gnOuGoFlowPersistenceWorkflowRunIndexMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)updatedAtTicksColumnBase, workflowRunIndex.FindProperty("UpdatedAtTicks")!, gnOuGoFlowPersistenceWorkflowRunIndexMappingBase);

            var tableMappings = new List<TableMapping>();
            workflowRunIndex.SetRuntimeAnnotation("Relational:TableMappings", tableMappings);
            var workflowRunsTable = new Table("WorkflowRuns", null, relationalModel);
            var tenantIdColumn = new Column("TenantId", "TEXT", workflowRunsTable);
            workflowRunsTable.Columns.Add("TenantId", tenantIdColumn);
            tenantIdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(tenantIdColumn);
            var runIdColumn = new Column("RunId", "TEXT", workflowRunsTable);
            workflowRunsTable.Columns.Add("RunId", runIdColumn);
            runIdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(runIdColumn);
            var revisionColumn = new Column("Revision", "INTEGER", workflowRunsTable);
            workflowRunsTable.Columns.Add("Revision", revisionColumn);
            revisionColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<long>(revisionColumn);
            var statusColumn = new Column("Status", "TEXT", workflowRunsTable);
            workflowRunsTable.Columns.Add("Status", statusColumn);
            statusColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(statusColumn);
            var updatedAtTicksColumn = new Column("UpdatedAtTicks", "INTEGER", workflowRunsTable);
            workflowRunsTable.Columns.Add("UpdatedAtTicks", updatedAtTicksColumn);
            updatedAtTicksColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<long>(updatedAtTicksColumn);
            relationalModel.Tables.Add(("WorkflowRuns", null), workflowRunsTable);
            var workflowRunsTableMapping = new TableMapping(workflowRunIndex, workflowRunsTable, null);
            workflowRunsTable.AddTypeMapping(workflowRunsTableMapping, false);
            tableMappings.Add(workflowRunsTableMapping);
            RelationalModel.CreateColumnMapping(runIdColumn, workflowRunIndex.FindProperty("RunId")!, workflowRunsTableMapping);
            RelationalModel.CreateColumnMapping(tenantIdColumn, workflowRunIndex.FindProperty("TenantId")!, workflowRunsTableMapping);
            RelationalModel.CreateColumnMapping(revisionColumn, workflowRunIndex.FindProperty("Revision")!, workflowRunsTableMapping);
            RelationalModel.CreateColumnMapping(statusColumn, workflowRunIndex.FindProperty("Status")!, workflowRunsTableMapping);
            RelationalModel.CreateColumnMapping(updatedAtTicksColumn, workflowRunIndex.FindProperty("UpdatedAtTicks")!, workflowRunsTableMapping);
            var pK_WorkflowRuns = new UniqueConstraint("PK_WorkflowRuns", workflowRunsTable, new[] { tenantIdColumn, runIdColumn });
            workflowRunsTable.PrimaryKey = pK_WorkflowRuns;
            pK_WorkflowRuns.SetRowKeyValueFactory(new CompositeRowKeyValueFactory(pK_WorkflowRuns));
            var pK_WorkflowRunsKey = RelationalModel.GetKey(this,
                "GnOuGo.Flow.Persistence.WorkflowRunIndex",
                new[] { "TenantId", "RunId" });
            pK_WorkflowRuns.MappedKeys.Add(pK_WorkflowRunsKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_WorkflowRunsKey).Add(pK_WorkflowRuns);
            workflowRunsTable.UniqueConstraints.Add("PK_WorkflowRuns", pK_WorkflowRuns);
            var iX_WorkflowRuns_TenantId_UpdatedAtTicks = new TableIndex(
            "IX_WorkflowRuns_TenantId_UpdatedAtTicks", workflowRunsTable, new[] { tenantIdColumn, updatedAtTicksColumn }, false);
            iX_WorkflowRuns_TenantId_UpdatedAtTicks.SetRowIndexValueFactory(new CompositeRowIndexValueFactory(iX_WorkflowRuns_TenantId_UpdatedAtTicks));
            var iX_WorkflowRuns_TenantId_UpdatedAtTicksIx = RelationalModel.GetIndex(this,
                "GnOuGo.Flow.Persistence.WorkflowRunIndex",
                new[] { "TenantId", "UpdatedAtTicks" });
            iX_WorkflowRuns_TenantId_UpdatedAtTicks.MappedIndexes.Add(iX_WorkflowRuns_TenantId_UpdatedAtTicksIx);
            RelationalModel.GetOrCreateTableIndexes(iX_WorkflowRuns_TenantId_UpdatedAtTicksIx).Add(iX_WorkflowRuns_TenantId_UpdatedAtTicks);
            workflowRunsTable.Indexes.Add("IX_WorkflowRuns_TenantId_UpdatedAtTicks", iX_WorkflowRuns_TenantId_UpdatedAtTicks);
            return relationalModel.MakeReadOnly();
        }
    }
}
