using System.Text.Json;
using System.Text.Json.Serialization;
using GitHub.Copilot;

namespace GnOuGo.GithubCopilot.Core;

[JsonSourceGenerationOptions(JsonSerializerDefaults.Web, UseStringEnumConverter = true)]
[JsonSerializable(typeof(CopilotCapabilityCatalogResult))]
[JsonSerializable(typeof(CopilotCapability))]
[JsonSerializable(typeof(IReadOnlyList<CopilotCapability>))]
[JsonSerializable(typeof(CopilotConnectivityResult))]
[JsonSerializable(typeof(CopilotStatusResult))]
[JsonSerializable(typeof(CopilotAuthResult))]
[JsonSerializable(typeof(CopilotModelResult))]
[JsonSerializable(typeof(IReadOnlyList<CopilotModelResult>))]
[JsonSerializable(typeof(CopilotSessionCreateRequest))]
[JsonSerializable(typeof(CopilotSessionResumeRequest))]
[JsonSerializable(typeof(CopilotSessionDescriptor))]
[JsonSerializable(typeof(IReadOnlyList<CopilotSessionDescriptor>))]
[JsonSerializable(typeof(CopilotStoredSession))]
[JsonSerializable(typeof(IReadOnlyList<CopilotStoredSession>))]
[JsonSerializable(typeof(CopilotSendRequest))]
[JsonSerializable(typeof(CopilotSendResult))]
[JsonSerializable(typeof(CopilotStreamEvent))]
[JsonSerializable(typeof(IReadOnlyList<CopilotStreamEvent>))]
[JsonSerializable(typeof(CopilotAttachment))]
[JsonSerializable(typeof(IReadOnlyList<CopilotAttachment>))]
[JsonSerializable(typeof(CopilotOperationResult))]
[JsonSerializable(typeof(CopilotPlanResult))]
[JsonSerializable(typeof(CopilotForegroundResult))]
[JsonSerializable(typeof(CopilotSessionConfigurationResult))]
[JsonSerializable(typeof(CopilotWorkspaceFileResult))]
[JsonSerializable(typeof(IReadOnlyList<string>))]
[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(ElicitationSchema))]
[JsonSerializable(typeof(Dictionary<string, object>))]
[JsonSerializable(typeof(CopilotHistoryEvent))]
[JsonSerializable(typeof(IReadOnlyList<CopilotHistoryEvent>))]
[JsonSerializable(typeof(ReviewFilePatch))]
[JsonSerializable(typeof(IReadOnlyList<ReviewFilePatch>))]
[JsonSerializable(typeof(ExistingReviewComment))]
[JsonSerializable(typeof(IReadOnlyList<ExistingReviewComment>))]
[JsonSerializable(typeof(ReviewFindingCandidate))]
[JsonSerializable(typeof(IReadOnlyList<ReviewFindingCandidate>))]
[JsonSerializable(typeof(ReviewFinding))]
[JsonSerializable(typeof(IReadOnlyList<ReviewFinding>))]
[JsonSerializable(typeof(ReviewCoverage))]
[JsonSerializable(typeof(CopilotReviewSession))]
[JsonSerializable(typeof(CopilotReviewBatch))]
[JsonSerializable(typeof(IReadOnlyList<CopilotReviewBatch>))]
[JsonSerializable(typeof(CopilotReviewAnalyzeResult))]
[JsonSerializable(typeof(CopilotReviewResult))]
[JsonSerializable(typeof(ReviewPublicationGateRequest))]
[JsonSerializable(typeof(ReviewPublicationGateResult))]
public partial class CopilotCoreJsonContext : JsonSerializerContext;
