// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Update.Internal;

#pragma warning disable 219, 612, 618
#nullable disable

namespace GnOuGo.Diff.Core.Data.CompiledModels
{
    public partial class DiffDbContextModel
    {
        private DiffDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("12076121-8425-4161-809f-09134899ce72"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var diffEntry = DiffEntryEntityType.Create(this);

            DiffEntryEntityType.CreateAnnotations(diffEntry);

            AddAnnotation("ProductVersion", "10.0.8");
            AddRuntimeAnnotation("Relational:RelationalModelFactory", () => CreateRelationalModel());
        }

        private IRelationalModel CreateRelationalModel()
        {
            var relationalModel = new RelationalModel(this);

            var diffEntry = FindEntityType("GnOuGo.Diff.Core.Models.DiffEntry")!;

            var defaultTableMappings = new List<TableMappingBase<ColumnMappingBase>>();
            diffEntry.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings);
            var gnOuGoDiffCoreModelsDiffEntryTableBase = new TableBase("GnOuGo.Diff.Core.Models.DiffEntry", null, relationalModel);
            var authorColumnBase = new ColumnBase<ColumnMappingBase>("Author", "TEXT", gnOuGoDiffCoreModelsDiffEntryTableBase);
            gnOuGoDiffCoreModelsDiffEntryTableBase.Columns.Add("Author", authorColumnBase);
            var currentValueColumnBase = new ColumnBase<ColumnMappingBase>("CurrentValue", "TEXT", gnOuGoDiffCoreModelsDiffEntryTableBase);
            gnOuGoDiffCoreModelsDiffEntryTableBase.Columns.Add("CurrentValue", currentValueColumnBase);
            var diffFromPreviousColumnBase = new ColumnBase<ColumnMappingBase>("DiffFromPrevious", "TEXT", gnOuGoDiffCoreModelsDiffEntryTableBase)
            {
                IsNullable = true
            };
            gnOuGoDiffCoreModelsDiffEntryTableBase.Columns.Add("DiffFromPrevious", diffFromPreviousColumnBase);
            var entityIdColumnBase = new ColumnBase<ColumnMappingBase>("EntityId", "TEXT", gnOuGoDiffCoreModelsDiffEntryTableBase);
            gnOuGoDiffCoreModelsDiffEntryTableBase.Columns.Add("EntityId", entityIdColumnBase);
            var entityTypeColumnBase = new ColumnBase<ColumnMappingBase>("EntityType", "TEXT", gnOuGoDiffCoreModelsDiffEntryTableBase);
            gnOuGoDiffCoreModelsDiffEntryTableBase.Columns.Add("EntityType", entityTypeColumnBase);
            var idColumnBase = new ColumnBase<ColumnMappingBase>("Id", "TEXT", gnOuGoDiffCoreModelsDiffEntryTableBase);
            gnOuGoDiffCoreModelsDiffEntryTableBase.Columns.Add("Id", idColumnBase);
            var timestampTicksColumnBase = new ColumnBase<ColumnMappingBase>("TimestampTicks", "INTEGER", gnOuGoDiffCoreModelsDiffEntryTableBase);
            gnOuGoDiffCoreModelsDiffEntryTableBase.Columns.Add("TimestampTicks", timestampTicksColumnBase);
            var valueHashColumnBase = new ColumnBase<ColumnMappingBase>("ValueHash", "TEXT", gnOuGoDiffCoreModelsDiffEntryTableBase);
            gnOuGoDiffCoreModelsDiffEntryTableBase.Columns.Add("ValueHash", valueHashColumnBase);
            relationalModel.DefaultTables.Add("GnOuGo.Diff.Core.Models.DiffEntry", gnOuGoDiffCoreModelsDiffEntryTableBase);
            var gnOuGoDiffCoreModelsDiffEntryMappingBase = new TableMappingBase<ColumnMappingBase>(diffEntry, gnOuGoDiffCoreModelsDiffEntryTableBase, null);
            gnOuGoDiffCoreModelsDiffEntryTableBase.AddTypeMapping(gnOuGoDiffCoreModelsDiffEntryMappingBase, false);
            defaultTableMappings.Add(gnOuGoDiffCoreModelsDiffEntryMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase, diffEntry.FindProperty("Id")!, gnOuGoDiffCoreModelsDiffEntryMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)authorColumnBase, diffEntry.FindProperty("Author")!, gnOuGoDiffCoreModelsDiffEntryMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)currentValueColumnBase, diffEntry.FindProperty("CurrentValue")!, gnOuGoDiffCoreModelsDiffEntryMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)diffFromPreviousColumnBase, diffEntry.FindProperty("DiffFromPrevious")!, gnOuGoDiffCoreModelsDiffEntryMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityIdColumnBase, diffEntry.FindProperty("EntityId")!, gnOuGoDiffCoreModelsDiffEntryMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityTypeColumnBase, diffEntry.FindProperty("EntityType")!, gnOuGoDiffCoreModelsDiffEntryMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)timestampTicksColumnBase, diffEntry.FindProperty("TimestampTicks")!, gnOuGoDiffCoreModelsDiffEntryMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)valueHashColumnBase, diffEntry.FindProperty("ValueHash")!, gnOuGoDiffCoreModelsDiffEntryMappingBase);

            var tableMappings = new List<TableMapping>();
            diffEntry.SetRuntimeAnnotation("Relational:TableMappings", tableMappings);
            var diffEntriesTable = new Table("DiffEntries", null, relationalModel);
            var idColumn = new Column("Id", "TEXT", diffEntriesTable);
            diffEntriesTable.Columns.Add("Id", idColumn);
            idColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(idColumn);
            var authorColumn = new Column("Author", "TEXT", diffEntriesTable);
            diffEntriesTable.Columns.Add("Author", authorColumn);
            authorColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(authorColumn);
            var currentValueColumn = new Column("CurrentValue", "TEXT", diffEntriesTable);
            diffEntriesTable.Columns.Add("CurrentValue", currentValueColumn);
            currentValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(currentValueColumn);
            var diffFromPreviousColumn = new Column("DiffFromPrevious", "TEXT", diffEntriesTable)
            {
                IsNullable = true
            };
            diffEntriesTable.Columns.Add("DiffFromPrevious", diffFromPreviousColumn);
            diffFromPreviousColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(diffFromPreviousColumn);
            var entityIdColumn = new Column("EntityId", "TEXT", diffEntriesTable);
            diffEntriesTable.Columns.Add("EntityId", entityIdColumn);
            entityIdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(entityIdColumn);
            var entityTypeColumn = new Column("EntityType", "TEXT", diffEntriesTable);
            diffEntriesTable.Columns.Add("EntityType", entityTypeColumn);
            entityTypeColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(entityTypeColumn);
            var timestampTicksColumn = new Column("TimestampTicks", "INTEGER", diffEntriesTable);
            diffEntriesTable.Columns.Add("TimestampTicks", timestampTicksColumn);
            timestampTicksColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<long>(timestampTicksColumn);
            var valueHashColumn = new Column("ValueHash", "TEXT", diffEntriesTable);
            diffEntriesTable.Columns.Add("ValueHash", valueHashColumn);
            valueHashColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(valueHashColumn);
            relationalModel.Tables.Add(("DiffEntries", null), diffEntriesTable);
            var diffEntriesTableMapping = new TableMapping(diffEntry, diffEntriesTable, null);
            diffEntriesTable.AddTypeMapping(diffEntriesTableMapping, false);
            tableMappings.Add(diffEntriesTableMapping);
            RelationalModel.CreateColumnMapping(idColumn, diffEntry.FindProperty("Id")!, diffEntriesTableMapping);
            RelationalModel.CreateColumnMapping(authorColumn, diffEntry.FindProperty("Author")!, diffEntriesTableMapping);
            RelationalModel.CreateColumnMapping(currentValueColumn, diffEntry.FindProperty("CurrentValue")!, diffEntriesTableMapping);
            RelationalModel.CreateColumnMapping(diffFromPreviousColumn, diffEntry.FindProperty("DiffFromPrevious")!, diffEntriesTableMapping);
            RelationalModel.CreateColumnMapping(entityIdColumn, diffEntry.FindProperty("EntityId")!, diffEntriesTableMapping);
            RelationalModel.CreateColumnMapping(entityTypeColumn, diffEntry.FindProperty("EntityType")!, diffEntriesTableMapping);
            RelationalModel.CreateColumnMapping(timestampTicksColumn, diffEntry.FindProperty("TimestampTicks")!, diffEntriesTableMapping);
            RelationalModel.CreateColumnMapping(valueHashColumn, diffEntry.FindProperty("ValueHash")!, diffEntriesTableMapping);
            var pK_DiffEntries = new UniqueConstraint("PK_DiffEntries", diffEntriesTable, new[] { idColumn });
            diffEntriesTable.PrimaryKey = pK_DiffEntries;
            pK_DiffEntries.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<Guid>(pK_DiffEntries));
            var pK_DiffEntriesKey = RelationalModel.GetKey(this,
                "GnOuGo.Diff.Core.Models.DiffEntry",
                new[] { "Id" });
            pK_DiffEntries.MappedKeys.Add(pK_DiffEntriesKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_DiffEntriesKey).Add(pK_DiffEntries);
            diffEntriesTable.UniqueConstraints.Add("PK_DiffEntries", pK_DiffEntries);
            var iX_DiffEntries_EntityType_EntityId = new TableIndex(
            "IX_DiffEntries_EntityType_EntityId", diffEntriesTable, new[] { entityTypeColumn, entityIdColumn }, false);
            iX_DiffEntries_EntityType_EntityId.SetRowIndexValueFactory(new CompositeRowIndexValueFactory(iX_DiffEntries_EntityType_EntityId));
            var iX_DiffEntries_EntityType_EntityIdIx = RelationalModel.GetIndex(this,
                "GnOuGo.Diff.Core.Models.DiffEntry",
                new[] { "EntityType", "EntityId" });
            iX_DiffEntries_EntityType_EntityId.MappedIndexes.Add(iX_DiffEntries_EntityType_EntityIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_DiffEntries_EntityType_EntityIdIx).Add(iX_DiffEntries_EntityType_EntityId);
            diffEntriesTable.Indexes.Add("IX_DiffEntries_EntityType_EntityId", iX_DiffEntries_EntityType_EntityId);
            var iX_DiffEntries_EntityType_EntityId_TimestampTicks = new TableIndex(
            "IX_DiffEntries_EntityType_EntityId_TimestampTicks", diffEntriesTable, new[] { entityTypeColumn, entityIdColumn, timestampTicksColumn }, false);
            iX_DiffEntries_EntityType_EntityId_TimestampTicks.SetRowIndexValueFactory(new CompositeRowIndexValueFactory(iX_DiffEntries_EntityType_EntityId_TimestampTicks));
            var iX_DiffEntries_EntityType_EntityId_TimestampTicksIx = RelationalModel.GetIndex(this,
                "GnOuGo.Diff.Core.Models.DiffEntry",
                new[] { "EntityType", "EntityId", "TimestampTicks" });
            iX_DiffEntries_EntityType_EntityId_TimestampTicks.MappedIndexes.Add(iX_DiffEntries_EntityType_EntityId_TimestampTicksIx);
            RelationalModel.GetOrCreateTableIndexes(iX_DiffEntries_EntityType_EntityId_TimestampTicksIx).Add(iX_DiffEntries_EntityType_EntityId_TimestampTicks);
            diffEntriesTable.Indexes.Add("IX_DiffEntries_EntityType_EntityId_TimestampTicks", iX_DiffEntries_EntityType_EntityId_TimestampTicks);
            var iX_DiffEntries_TimestampTicks = new TableIndex(
            "IX_DiffEntries_TimestampTicks", diffEntriesTable, new[] { timestampTicksColumn }, false);
            iX_DiffEntries_TimestampTicks.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<long>(iX_DiffEntries_TimestampTicks));
            var iX_DiffEntries_TimestampTicksIx = RelationalModel.GetIndex(this,
                "GnOuGo.Diff.Core.Models.DiffEntry",
                new[] { "TimestampTicks" });
            iX_DiffEntries_TimestampTicks.MappedIndexes.Add(iX_DiffEntries_TimestampTicksIx);
            RelationalModel.GetOrCreateTableIndexes(iX_DiffEntries_TimestampTicksIx).Add(iX_DiffEntries_TimestampTicks);
            diffEntriesTable.Indexes.Add("IX_DiffEntries_TimestampTicks", iX_DiffEntries_TimestampTicks);
            return relationalModel.MakeReadOnly();
        }
    }
}
