// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using GnOuGo.Diff.Core.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace GnOuGo.Diff.Core.Data.CompiledModels
{
    public static class DiffEntryUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref Guid Id(DiffEntry @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Author>k__BackingField")]
        public static extern ref string Author(DiffEntry @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CurrentValue>k__BackingField")]
        public static extern ref string CurrentValue(DiffEntry @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<DiffFromPrevious>k__BackingField")]
        public static extern ref string DiffFromPrevious(DiffEntry @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EntityId>k__BackingField")]
        public static extern ref string EntityId(DiffEntry @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EntityType>k__BackingField")]
        public static extern ref string EntityType(DiffEntry @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TimestampTicks>k__BackingField")]
        public static extern ref long TimestampTicks(DiffEntry @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ValueHash>k__BackingField")]
        public static extern ref string ValueHash(DiffEntry @this);
    }
}
