// <auto-generated />
using GnOuGo.Diff.Core.Data;
using GnOuGo.Diff.Core.Data.CompiledModels;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(DiffDbContext), typeof(DiffDbContextModel))]
