// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using GnOuGo.Diff.Core.Models;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;

#pragma warning disable 219, 612, 618
#nullable disable

namespace GnOuGo.Diff.Core.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class DiffEntryEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "GnOuGo.Diff.Core.Models.DiffEntry",
                typeof(DiffEntry),
                baseEntityType,
                propertyCount: 8,
                unnamedIndexCount: 3,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(DiffEntry).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(DiffEntry).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.SetGetter(
                Guid (DiffEntry instance) => DiffEntryUnsafeAccessors.Id(instance),
                bool (DiffEntry instance) => DiffEntryUnsafeAccessors.Id(instance) == new Guid("00000000-0000-0000-0000-000000000000"));
            id.SetSetter(
                DiffEntry (DiffEntry instance, Guid value) =>
                {
                    DiffEntryUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                DiffEntry (DiffEntry instance, Guid value) =>
                {
                    DiffEntryUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                Guid (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<Guid>(0) : (entry.FlaggedAsTemporary(0) && DiffEntryUnsafeAccessors.Id(((DiffEntry)(entry.Entity))) == new Guid("00000000-0000-0000-0000-000000000000") ? entry.ReadTemporaryValue<Guid>(0) : DiffEntryUnsafeAccessors.Id(((DiffEntry)(entry.Entity))))),
                Guid (IInternalEntry entry) => DiffEntryUnsafeAccessors.Id(((DiffEntry)(entry.Entity))),
                Guid (IInternalEntry entry) => entry.ReadOriginalValue<Guid>(id, 0),
                Guid (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<Guid>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = SqliteGuidTypeMapping.Default.Clone(
                comparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => v.GetHashCode(),
                    Guid (Guid v) => v),
                keyComparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => v.GetHashCode(),
                    Guid (Guid v) => v),
                providerValueComparer: new ValueComparer<Guid>(
                    bool (Guid v1, Guid v2) => v1 == v2,
                    int (Guid v) => v.GetHashCode(),
                    Guid (Guid v) => v));
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<Guid>(id));

            var author = runtimeEntityType.AddProperty(
                "Author",
                typeof(string),
                propertyInfo: typeof(DiffEntry).GetProperty("Author", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(DiffEntry).GetField("<Author>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 200);
            author.SetGetter(
                string (DiffEntry instance) => DiffEntryUnsafeAccessors.Author(instance),
                bool (DiffEntry instance) => DiffEntryUnsafeAccessors.Author(instance) == null);
            author.SetSetter(
                DiffEntry (DiffEntry instance, string value) =>
                {
                    DiffEntryUnsafeAccessors.Author(instance) = value;
                    return instance;
                });
            author.SetMaterializationSetter(
                DiffEntry (DiffEntry instance, string value) =>
                {
                    DiffEntryUnsafeAccessors.Author(instance) = value;
                    return instance;
                });
            author.SetAccessors(
                string (IInternalEntry entry) => DiffEntryUnsafeAccessors.Author(((DiffEntry)(entry.Entity))),
                string (IInternalEntry entry) => DiffEntryUnsafeAccessors.Author(((DiffEntry)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(author, 1),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(author));
            author.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            author.TypeMapping = SqliteStringTypeMapping.Default;

            var currentValue = runtimeEntityType.AddProperty(
                "CurrentValue",
                typeof(string),
                propertyInfo: typeof(DiffEntry).GetProperty("CurrentValue", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(DiffEntry).GetField("<CurrentValue>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            currentValue.SetGetter(
                string (DiffEntry instance) => DiffEntryUnsafeAccessors.CurrentValue(instance),
                bool (DiffEntry instance) => DiffEntryUnsafeAccessors.CurrentValue(instance) == null);
            currentValue.SetSetter(
                DiffEntry (DiffEntry instance, string value) =>
                {
                    DiffEntryUnsafeAccessors.CurrentValue(instance) = value;
                    return instance;
                });
            currentValue.SetMaterializationSetter(
                DiffEntry (DiffEntry instance, string value) =>
                {
                    DiffEntryUnsafeAccessors.CurrentValue(instance) = value;
                    return instance;
                });
            currentValue.SetAccessors(
                string (IInternalEntry entry) => DiffEntryUnsafeAccessors.CurrentValue(((DiffEntry)(entry.Entity))),
                string (IInternalEntry entry) => DiffEntryUnsafeAccessors.CurrentValue(((DiffEntry)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(currentValue, 2),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(currentValue));
            currentValue.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            currentValue.TypeMapping = SqliteStringTypeMapping.Default;

            var diffFromPrevious = runtimeEntityType.AddProperty(
                "DiffFromPrevious",
                typeof(string),
                propertyInfo: typeof(DiffEntry).GetProperty("DiffFromPrevious", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(DiffEntry).GetField("<DiffFromPrevious>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            diffFromPrevious.SetGetter(
                string (DiffEntry instance) => DiffEntryUnsafeAccessors.DiffFromPrevious(instance),
                bool (DiffEntry instance) => DiffEntryUnsafeAccessors.DiffFromPrevious(instance) == null);
            diffFromPrevious.SetSetter(
                DiffEntry (DiffEntry instance, string value) =>
                {
                    DiffEntryUnsafeAccessors.DiffFromPrevious(instance) = value;
                    return instance;
                });
            diffFromPrevious.SetMaterializationSetter(
                DiffEntry (DiffEntry instance, string value) =>
                {
                    DiffEntryUnsafeAccessors.DiffFromPrevious(instance) = value;
                    return instance;
                });
            diffFromPrevious.SetAccessors(
                string (IInternalEntry entry) => DiffEntryUnsafeAccessors.DiffFromPrevious(((DiffEntry)(entry.Entity))),
                string (IInternalEntry entry) => DiffEntryUnsafeAccessors.DiffFromPrevious(((DiffEntry)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(diffFromPrevious, 3),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(diffFromPrevious));
            diffFromPrevious.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            diffFromPrevious.TypeMapping = SqliteStringTypeMapping.Default;

            var entityId = runtimeEntityType.AddProperty(
                "EntityId",
                typeof(string),
                propertyInfo: typeof(DiffEntry).GetProperty("EntityId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(DiffEntry).GetField("<EntityId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 200);
            entityId.SetGetter(
                string (DiffEntry instance) => DiffEntryUnsafeAccessors.EntityId(instance),
                bool (DiffEntry instance) => DiffEntryUnsafeAccessors.EntityId(instance) == null);
            entityId.SetSetter(
                DiffEntry (DiffEntry instance, string value) =>
                {
                    DiffEntryUnsafeAccessors.EntityId(instance) = value;
                    return instance;
                });
            entityId.SetMaterializationSetter(
                DiffEntry (DiffEntry instance, string value) =>
                {
                    DiffEntryUnsafeAccessors.EntityId(instance) = value;
                    return instance;
                });
            entityId.SetAccessors(
                string (IInternalEntry entry) => DiffEntryUnsafeAccessors.EntityId(((DiffEntry)(entry.Entity))),
                string (IInternalEntry entry) => DiffEntryUnsafeAccessors.EntityId(((DiffEntry)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(entityId, 4),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(entityId));
            entityId.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            entityId.TypeMapping = SqliteStringTypeMapping.Default;

            var entityType = runtimeEntityType.AddProperty(
                "EntityType",
                typeof(string),
                propertyInfo: typeof(DiffEntry).GetProperty("EntityType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(DiffEntry).GetField("<EntityType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);
            entityType.SetGetter(
                string (DiffEntry instance) => DiffEntryUnsafeAccessors.EntityType(instance),
                bool (DiffEntry instance) => DiffEntryUnsafeAccessors.EntityType(instance) == null);
            entityType.SetSetter(
                DiffEntry (DiffEntry instance, string value) =>
                {
                    DiffEntryUnsafeAccessors.EntityType(instance) = value;
                    return instance;
                });
            entityType.SetMaterializationSetter(
                DiffEntry (DiffEntry instance, string value) =>
                {
                    DiffEntryUnsafeAccessors.EntityType(instance) = value;
                    return instance;
                });
            entityType.SetAccessors(
                string (IInternalEntry entry) => DiffEntryUnsafeAccessors.EntityType(((DiffEntry)(entry.Entity))),
                string (IInternalEntry entry) => DiffEntryUnsafeAccessors.EntityType(((DiffEntry)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(entityType, 5),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(entityType));
            entityType.SetPropertyIndexes(
                index: 5,
                originalValueIndex: 5,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            entityType.TypeMapping = SqliteStringTypeMapping.Default;

            var timestampTicks = runtimeEntityType.AddProperty(
                "TimestampTicks",
                typeof(long),
                propertyInfo: typeof(DiffEntry).GetProperty("TimestampTicks", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(DiffEntry).GetField("<TimestampTicks>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            timestampTicks.SetGetter(
                long (DiffEntry instance) => DiffEntryUnsafeAccessors.TimestampTicks(instance),
                bool (DiffEntry instance) => DiffEntryUnsafeAccessors.TimestampTicks(instance) == 0L);
            timestampTicks.SetSetter(
                DiffEntry (DiffEntry instance, long value) =>
                {
                    DiffEntryUnsafeAccessors.TimestampTicks(instance) = value;
                    return instance;
                });
            timestampTicks.SetMaterializationSetter(
                DiffEntry (DiffEntry instance, long value) =>
                {
                    DiffEntryUnsafeAccessors.TimestampTicks(instance) = value;
                    return instance;
                });
            timestampTicks.SetAccessors(
                long (IInternalEntry entry) => DiffEntryUnsafeAccessors.TimestampTicks(((DiffEntry)(entry.Entity))),
                long (IInternalEntry entry) => DiffEntryUnsafeAccessors.TimestampTicks(((DiffEntry)(entry.Entity))),
                long (IInternalEntry entry) => entry.ReadOriginalValue<long>(timestampTicks, 6),
                long (IInternalEntry entry) => entry.GetCurrentValue<long>(timestampTicks));
            timestampTicks.SetPropertyIndexes(
                index: 6,
                originalValueIndex: 6,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            timestampTicks.TypeMapping = LongTypeMapping.Default.Clone(
                comparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                keyComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                providerValueComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var valueHash = runtimeEntityType.AddProperty(
                "ValueHash",
                typeof(string),
                propertyInfo: typeof(DiffEntry).GetProperty("ValueHash", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(DiffEntry).GetField("<ValueHash>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 64);
            valueHash.SetGetter(
                string (DiffEntry instance) => DiffEntryUnsafeAccessors.ValueHash(instance),
                bool (DiffEntry instance) => DiffEntryUnsafeAccessors.ValueHash(instance) == null);
            valueHash.SetSetter(
                DiffEntry (DiffEntry instance, string value) =>
                {
                    DiffEntryUnsafeAccessors.ValueHash(instance) = value;
                    return instance;
                });
            valueHash.SetMaterializationSetter(
                DiffEntry (DiffEntry instance, string value) =>
                {
                    DiffEntryUnsafeAccessors.ValueHash(instance) = value;
                    return instance;
                });
            valueHash.SetAccessors(
                string (IInternalEntry entry) => DiffEntryUnsafeAccessors.ValueHash(((DiffEntry)(entry.Entity))),
                string (IInternalEntry entry) => DiffEntryUnsafeAccessors.ValueHash(((DiffEntry)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(valueHash, 7),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(valueHash));
            valueHash.SetPropertyIndexes(
                index: 7,
                originalValueIndex: 7,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            valueHash.TypeMapping = SqliteStringTypeMapping.Default;

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { timestampTicks });

            var index0 = runtimeEntityType.AddIndex(
                new[] { entityType, entityId });

            var index1 = runtimeEntityType.AddIndex(
                new[] { entityType, entityId, timestampTicks });

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var author = runtimeEntityType.FindProperty("Author");
            var currentValue = runtimeEntityType.FindProperty("CurrentValue");
            var diffFromPrevious = runtimeEntityType.FindProperty("DiffFromPrevious");
            var entityId = runtimeEntityType.FindProperty("EntityId");
            var entityType = runtimeEntityType.FindProperty("EntityType");
            var timestampTicks = runtimeEntityType.FindProperty("TimestampTicks");
            var valueHash = runtimeEntityType.FindProperty("ValueHash");
            var key = runtimeEntityType.FindKey(new[] { id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<Guid>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<Guid>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((DiffEntry)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid, string, string, string, string, string, long, string>(((ValueComparer<Guid>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid>(id)), (source.GetCurrentValue<string>(author) == null ? null : ((ValueComparer<string>)(((IProperty)author).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(author))), (source.GetCurrentValue<string>(currentValue) == null ? null : ((ValueComparer<string>)(((IProperty)currentValue).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(currentValue))), (source.GetCurrentValue<string>(diffFromPrevious) == null ? null : ((ValueComparer<string>)(((IProperty)diffFromPrevious).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(diffFromPrevious))), (source.GetCurrentValue<string>(entityId) == null ? null : ((ValueComparer<string>)(((IProperty)entityId).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(entityId))), (source.GetCurrentValue<string>(entityType) == null ? null : ((ValueComparer<string>)(((IProperty)entityType).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(entityType))), ((ValueComparer<long>)(((IProperty)timestampTicks).GetValueComparer())).Snapshot(source.GetCurrentValue<long>(timestampTicks)), (source.GetCurrentValue<string>(valueHash) == null ? null : ((ValueComparer<string>)(((IProperty)valueHash).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(valueHash))))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<Guid>(((ValueComparer<Guid>)(((IProperty)id).GetValueComparer())).Snapshot(default(Guid))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<Guid>(default(Guid)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((DiffEntry)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid>(((ValueComparer<Guid>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<Guid>(id)))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 8,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 8,
                shadowCount: 0,
                relationshipCount: 1,
                storeGeneratedCount: 1));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "DiffEntries");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
