// <auto-generated/>
// Generated by scripts/update-model-metadata.ps1 on 2026-05-01 17:56:48
// Source: src/GnOuGo.AI.Core/Telemetry/model-metadata.json
// DO NOT EDIT MANUALLY - run the script to regenerate.

using System.Collections.Frozen;

namespace GnOuGo.AI.Core;

public static partial class ModelMetadataCatalog
{
    private static readonly FrozenDictionary<string, LLMModelMetadata> BuiltinModels = new Dictionary<string, LLMModelMetadata>(StringComparer.OrdinalIgnoreCase)
    {
        ["text-embedding-3-large"] = new LLMModelMetadata
        {
            Id = "text-embedding-3-large",
            DisplayName = "text-embedding-3-large",
                ProviderType = "openai",
                OwnedBy = "openai",
            Pricing = new ModelPricingMetadata
            {
                Currency = "USD",
                InputPer1MTokens = 0.13m,
                OutputPer1MTokens = 0.0m,
            },
            Capabilities = new ModelCapabilityMetadata
            {
                SupportsTemperature = false,
                SupportsReasoningEffort = false,
                SupportsStructuredOutput = false,
                SupportsTools = false,
                SupportsJsonMode = false,
                SupportsEmbeddings = true,
            },
        },
        ["text-embedding-3-small"] = new LLMModelMetadata
        {
            Id = "text-embedding-3-small",
            DisplayName = "text-embedding-3-small",
                ProviderType = "openai",
                OwnedBy = "openai",
            Pricing = new ModelPricingMetadata
            {
                Currency = "USD",
                InputPer1MTokens = 0.02m,
                OutputPer1MTokens = 0.0m,
            },
            Capabilities = new ModelCapabilityMetadata
            {
                SupportsTemperature = false,
                SupportsReasoningEffort = false,
                SupportsStructuredOutput = false,
                SupportsTools = false,
                SupportsJsonMode = false,
                SupportsEmbeddings = true,
            },
        },
        ["text-embedding-ada-002"] = new LLMModelMetadata
        {
            Id = "text-embedding-ada-002",
            DisplayName = "text-embedding-ada-002",
                ProviderType = "openai",
                OwnedBy = "openai",
            Pricing = new ModelPricingMetadata
            {
                Currency = "USD",
                InputPer1MTokens = 0.1m,
                OutputPer1MTokens = 0.0m,
            },
            Capabilities = new ModelCapabilityMetadata
            {
                SupportsTemperature = false,
                SupportsReasoningEffort = false,
                SupportsStructuredOutput = false,
                SupportsTools = false,
                SupportsJsonMode = false,
                SupportsEmbeddings = true,
            },
        },
        ["gpt-4o"] = new LLMModelMetadata
        {
            Id = "gpt-4o",
            DisplayName = "gpt-4o",
                ProviderType = "openai",
                OwnedBy = "openai",
                ContextWindowTokens = 128000,
                MaxInputTokens = 128000,
                MaxOutputTokens = 16384,
            Pricing = new ModelPricingMetadata
            {
                Currency = "USD",
                InputPer1MTokens = 2.5m,
                OutputPer1MTokens = 10.0m,
            },
            Capabilities = new ModelCapabilityMetadata
            {
                SupportsTemperature = true,
                SupportsReasoningEffort = false,
                SupportsStructuredOutput = true,
                SupportsTools = true,
                SupportsJsonMode = true,
                SupportsVision = true,
            },
        },
        ["gpt-4o-2024-11-20"] = new LLMModelMetadata
        {
            Id = "gpt-4o-2024-11-20",
            DisplayName = "gpt-4o-2024-11-20",
                ProviderType = "openai",
                OwnedBy = "openai",
                ContextWindowTokens = 128000,
                MaxInputTokens = 128000,
                MaxOutputTokens = 16384,
            Pricing = new ModelPricingMetadata
            {
                Currency = "USD",
                InputPer1MTokens = 2.5m,
                OutputPer1MTokens = 10.0m,
            },
            Capabilities = new ModelCapabilityMetadata
            {
                SupportsTemperature = true,
                SupportsReasoningEffort = false,
                SupportsStructuredOutput = true,
                SupportsTools = true,
                SupportsJsonMode = true,
                SupportsVision = true,
            },
        },
        ["gpt-4o-mini"] = new LLMModelMetadata
        {
            Id = "gpt-4o-mini",
            DisplayName = "gpt-4o-mini",
                ProviderType = "openai",
                OwnedBy = "openai",
                ContextWindowTokens = 128000,
                MaxInputTokens = 128000,
                MaxOutputTokens = 16384,
            Pricing = new ModelPricingMetadata
            {
                Currency = "USD",
                InputPer1MTokens = 0.15m,
                OutputPer1MTokens = 0.6m,
            },
            Capabilities = new ModelCapabilityMetadata
            {
                SupportsTemperature = true,
                SupportsReasoningEffort = false,
                SupportsStructuredOutput = true,
                SupportsTools = true,
                SupportsJsonMode = true,
                SupportsVision = true,
            },
        },
        ["gpt-4o-mini-2024-07-18"] = new LLMModelMetadata
        {
            Id = "gpt-4o-mini-2024-07-18",
            DisplayName = "gpt-4o-mini-2024-07-18",
                ProviderType = "openai",
                OwnedBy = "openai",
                ContextWindowTokens = 128000,
                MaxInputTokens = 128000,
                MaxOutputTokens = 16384,
            Pricing = new ModelPricingMetadata
            {
                Currency = "USD",
                InputPer1MTokens = 0.15m,
                OutputPer1MTokens = 0.6m,
            },
            Capabilities = new ModelCapabilityMetadata
            {
                SupportsTemperature = true,
                SupportsReasoningEffort = false,
                SupportsStructuredOutput = true,
                SupportsTools = true,
                SupportsJsonMode = true,
                SupportsVision = true,
            },
        },
        ["gpt-4.1"] = new LLMModelMetadata
        {
            Id = "gpt-4.1",
            DisplayName = "gpt-4.1",
                ProviderType = "openai",
                OwnedBy = "openai",
                ContextWindowTokens = 1047576,
                MaxInputTokens = 1047576,
                MaxOutputTokens = 32768,
            Pricing = new ModelPricingMetadata
            {
                Currency = "USD",
                InputPer1MTokens = 2.0m,
                OutputPer1MTokens = 8.0m,
            },
            Capabilities = new ModelCapabilityMetadata
            {
                SupportsTemperature = true,
                SupportsReasoningEffort = false,
                SupportsStructuredOutput = true,
                SupportsTools = true,
                SupportsJsonMode = true,
                SupportsVision = true,
            },
        },
        ["gpt-4.1-mini"] = new LLMModelMetadata
        {
            Id = "gpt-4.1-mini",
            DisplayName = "gpt-4.1-mini",
                ProviderType = "openai",
                OwnedBy = "openai",
                ContextWindowTokens = 1047576,
                MaxInputTokens = 1047576,
                MaxOutputTokens = 32768,
            Pricing = new ModelPricingMetadata
            {
                Currency = "USD",
                InputPer1MTokens = 0.4m,
                OutputPer1MTokens = 1.6m,
            },
            Capabilities = new ModelCapabilityMetadata
            {
                SupportsTemperature = true,
                SupportsReasoningEffort = false,
                SupportsStructuredOutput = true,
                SupportsTools = true,
                SupportsJsonMode = true,
                SupportsVision = true,
            },
        },
        ["gpt-4.1-nano"] = new LLMModelMetadata
        {
            Id = "gpt-4.1-nano",
            DisplayName = "gpt-4.1-nano",
                ProviderType = "openai",
                OwnedBy = "openai",
                ContextWindowTokens = 1047576,
                MaxInputTokens = 1047576,
                MaxOutputTokens = 32768,
            Pricing = new ModelPricingMetadata
            {
                Currency = "USD",
                InputPer1MTokens = 0.1m,
                OutputPer1MTokens = 0.4m,
            },
            Capabilities = new ModelCapabilityMetadata
            {
                SupportsTemperature = true,
                SupportsReasoningEffort = false,
                SupportsStructuredOutput = true,
                SupportsTools = true,
                SupportsJsonMode = true,
                SupportsVision = true,
            },
        },
        ["gpt-4-turbo"] = new LLMModelMetadata
        {
            Id = "gpt-4-turbo",
            DisplayName = "gpt-4-turbo",
                ProviderType = "openai",
                OwnedBy = "openai",
                ContextWindowTokens = 128000,
                MaxInputTokens = 128000,
                MaxOutputTokens = 4096,
            Pricing = new ModelPricingMetadata
            {
                Currency = "USD",
                InputPer1MTokens = 10.0m,
                OutputPer1MTokens = 30.0m,
            },
            Capabilities = new ModelCapabilityMetadata
            {
                SupportsTemperature = true,
                SupportsReasoningEffort = false,
                SupportsStructuredOutput = true,
                SupportsTools = true,
                SupportsJsonMode = true,
                SupportsVision = true,
            },
        },
        ["gpt-3.5-turbo"] = new LLMModelMetadata
        {
            Id = "gpt-3.5-turbo",
            DisplayName = "gpt-3.5-turbo",
                ProviderType = "openai",
                OwnedBy = "openai",
                ContextWindowTokens = 16385,
                MaxInputTokens = 16385,
                MaxOutputTokens = 4096,
            Pricing = new ModelPricingMetadata
            {
                Currency = "USD",
                InputPer1MTokens = 0.5m,
                OutputPer1MTokens = 1.5m,
            },
            Capabilities = new ModelCapabilityMetadata
            {
                SupportsTemperature = true,
                SupportsReasoningEffort = false,
                SupportsStructuredOutput = true,
                SupportsTools = true,
                SupportsJsonMode = true,
            },
        },
        ["o1"] = new LLMModelMetadata
        {
            Id = "o1",
            DisplayName = "o1",
                ProviderType = "openai",
                OwnedBy = "openai",
                ContextWindowTokens = 200000,
                MaxInputTokens = 200000,
                MaxOutputTokens = 100000,
            Pricing = new ModelPricingMetadata
            {
                Currency = "USD",
                InputPer1MTokens = 15.0m,
                OutputPer1MTokens = 60.0m,
            },
            Capabilities = new ModelCapabilityMetadata
            {
                SupportsTemperature = false,
                SupportsReasoningEffort = true,
                SupportsStructuredOutput = true,
                SupportsTools = true,
                SupportsJsonMode = true,
                SupportedReasoningEfforts = ["minimal", "low", "medium", "high"],
                UnsupportedRequestParameters = ["temperature"],
            },
        },
        ["o1-mini"] = new LLMModelMetadata
        {
            Id = "o1-mini",
            DisplayName = "o1-mini",
                ProviderType = "openai",
                OwnedBy = "openai",
                ContextWindowTokens = 128000,
                MaxInputTokens = 128000,
                MaxOutputTokens = 65536,
            Pricing = new ModelPricingMetadata
            {
                Currency = "USD",
                InputPer1MTokens = 1.1m,
                OutputPer1MTokens = 4.4m,
            },
            Capabilities = new ModelCapabilityMetadata
            {
                SupportsTemperature = false,
                SupportsReasoningEffort = true,
                SupportsStructuredOutput = true,
                SupportsTools = true,
                SupportsJsonMode = true,
                SupportedReasoningEfforts = ["minimal", "low", "medium", "high"],
                UnsupportedRequestParameters = ["temperature"],
            },
        },
        ["o1-pro"] = new LLMModelMetadata
        {
            Id = "o1-pro",
            DisplayName = "o1-pro",
                ProviderType = "openai",
                OwnedBy = "openai",
                ContextWindowTokens = 200000,
                MaxInputTokens = 200000,
                MaxOutputTokens = 100000,
            Pricing = new ModelPricingMetadata
            {
                Currency = "USD",
                InputPer1MTokens = 150.0m,
                OutputPer1MTokens = 600.0m,
            },
            Capabilities = new ModelCapabilityMetadata
            {
                SupportsTemperature = false,
                SupportsReasoningEffort = true,
                SupportsStructuredOutput = true,
                SupportsTools = true,
                SupportsJsonMode = true,
                SupportedReasoningEfforts = ["minimal", "low", "medium", "high"],
                UnsupportedRequestParameters = ["temperature"],
            },
        },
        ["o3"] = new LLMModelMetadata
        {
            Id = "o3",
            DisplayName = "o3",
                ProviderType = "openai",
                OwnedBy = "openai",
                ContextWindowTokens = 200000,
                MaxInputTokens = 200000,
                MaxOutputTokens = 100000,
            Pricing = new ModelPricingMetadata
            {
                Currency = "USD",
                InputPer1MTokens = 2.0m,
                OutputPer1MTokens = 8.0m,
            },
            Capabilities = new ModelCapabilityMetadata
            {
                SupportsTemperature = false,
                SupportsReasoningEffort = true,
                SupportsStructuredOutput = true,
                SupportsTools = true,
                SupportsJsonMode = true,
                SupportedReasoningEfforts = ["minimal", "low", "medium", "high"],
                UnsupportedRequestParameters = ["temperature"],
            },
        },
        ["o3-mini"] = new LLMModelMetadata
        {
            Id = "o3-mini",
            DisplayName = "o3-mini",
                ProviderType = "openai",
                OwnedBy = "openai",
                ContextWindowTokens = 200000,
                MaxInputTokens = 200000,
                MaxOutputTokens = 100000,
            Pricing = new ModelPricingMetadata
            {
                Currency = "USD",
                InputPer1MTokens = 1.1m,
                OutputPer1MTokens = 4.4m,
            },
            Capabilities = new ModelCapabilityMetadata
            {
                SupportsTemperature = false,
                SupportsReasoningEffort = true,
                SupportsStructuredOutput = true,
                SupportsTools = true,
                SupportsJsonMode = true,
                SupportedReasoningEfforts = ["minimal", "low", "medium", "high"],
                UnsupportedRequestParameters = ["temperature"],
            },
        },
        ["o4-mini"] = new LLMModelMetadata
        {
            Id = "o4-mini",
            DisplayName = "o4-mini",
                ProviderType = "openai",
                OwnedBy = "openai",
                ContextWindowTokens = 200000,
                MaxInputTokens = 200000,
                MaxOutputTokens = 100000,
            Pricing = new ModelPricingMetadata
            {
                Currency = "USD",
                InputPer1MTokens = 1.1m,
                OutputPer1MTokens = 4.4m,
            },
            Capabilities = new ModelCapabilityMetadata
            {
                SupportsTemperature = false,
                SupportsReasoningEffort = true,
                SupportsStructuredOutput = true,
                SupportsTools = true,
                SupportsJsonMode = true,
                SupportedReasoningEfforts = ["minimal", "low", "medium", "high"],
                UnsupportedRequestParameters = ["temperature"],
            },
        },
        ["claude-3-5-sonnet-20241022"] = new LLMModelMetadata
        {
            Id = "claude-3-5-sonnet-20241022",
            DisplayName = "claude-3-5-sonnet-20241022",
                ProviderType = "copilot",
                OwnedBy = "anthropic",
                ContextWindowTokens = 200000,
                MaxInputTokens = 200000,
                MaxOutputTokens = 8192,
            Pricing = new ModelPricingMetadata
            {
                Currency = "USD",
                InputPer1MTokens = 3.0m,
                OutputPer1MTokens = 15.0m,
            },
            Capabilities = new ModelCapabilityMetadata
            {
                SupportsTemperature = true,
                SupportsReasoningEffort = false,
                SupportsStructuredOutput = false,
                SupportsTools = true,
                SupportsJsonMode = true,
            },
        },
        ["claude-3-5-haiku-20241022"] = new LLMModelMetadata
        {
            Id = "claude-3-5-haiku-20241022",
            DisplayName = "claude-3-5-haiku-20241022",
                ProviderType = "copilot",
                OwnedBy = "anthropic",
                ContextWindowTokens = 200000,
                MaxInputTokens = 200000,
                MaxOutputTokens = 8192,
            Pricing = new ModelPricingMetadata
            {
                Currency = "USD",
                InputPer1MTokens = 0.8m,
                OutputPer1MTokens = 4.0m,
            },
            Capabilities = new ModelCapabilityMetadata
            {
                SupportsTemperature = true,
                SupportsReasoningEffort = false,
                SupportsStructuredOutput = false,
                SupportsTools = true,
                SupportsJsonMode = true,
            },
        },
        ["claude-sonnet-4-20250514"] = new LLMModelMetadata
        {
            Id = "claude-sonnet-4-20250514",
            DisplayName = "claude-sonnet-4-20250514",
                ProviderType = "copilot",
                OwnedBy = "anthropic",
                ContextWindowTokens = 200000,
                MaxInputTokens = 200000,
                MaxOutputTokens = 64000,
            Pricing = new ModelPricingMetadata
            {
                Currency = "USD",
                InputPer1MTokens = 3.0m,
                OutputPer1MTokens = 15.0m,
            },
            Capabilities = new ModelCapabilityMetadata
            {
                SupportsTemperature = true,
                SupportsReasoningEffort = false,
                SupportsStructuredOutput = false,
                SupportsTools = true,
                SupportsJsonMode = true,
            },
        },
        ["claude-haiku-4-20250514"] = new LLMModelMetadata
        {
            Id = "claude-haiku-4-20250514",
            DisplayName = "claude-haiku-4-20250514",
                ProviderType = "copilot",
                OwnedBy = "anthropic",
                ContextWindowTokens = 200000,
                MaxInputTokens = 200000,
                MaxOutputTokens = 8192,
            Pricing = new ModelPricingMetadata
            {
                Currency = "USD",
                InputPer1MTokens = 0.8m,
                OutputPer1MTokens = 4.0m,
            },
            Capabilities = new ModelCapabilityMetadata
            {
                SupportsTemperature = true,
                SupportsReasoningEffort = false,
                SupportsStructuredOutput = false,
                SupportsTools = true,
                SupportsJsonMode = true,
            },
        },
        ["claude-3-7-sonnet-20250219"] = new LLMModelMetadata
        {
            Id = "claude-3-7-sonnet-20250219",
            DisplayName = "claude-3-7-sonnet-20250219",
                ProviderType = "copilot",
                OwnedBy = "anthropic",
                ContextWindowTokens = 200000,
                MaxInputTokens = 200000,
                MaxOutputTokens = 64000,
            Pricing = new ModelPricingMetadata
            {
                Currency = "USD",
                InputPer1MTokens = 3.0m,
                OutputPer1MTokens = 15.0m,
            },
            Capabilities = new ModelCapabilityMetadata
            {
                SupportsTemperature = true,
                SupportsReasoningEffort = false,
                SupportsStructuredOutput = false,
                SupportsTools = true,
                SupportsJsonMode = true,
            },
        },
        ["mistral-large-latest"] = new LLMModelMetadata
        {
            Id = "mistral-large-latest",
            DisplayName = "mistral-large-latest",
                ProviderType = "copilot",
                OwnedBy = "mistral",
                ContextWindowTokens = 128000,
                MaxInputTokens = 128000,
                MaxOutputTokens = 8192,
            Pricing = new ModelPricingMetadata
            {
                Currency = "USD",
                InputPer1MTokens = 2.0m,
                OutputPer1MTokens = 6.0m,
            },
            Capabilities = new ModelCapabilityMetadata
            {
                SupportsTemperature = true,
                SupportsReasoningEffort = false,
                SupportsStructuredOutput = true,
                SupportsTools = true,
                SupportsJsonMode = true,
            },
        },
        ["mistral-small-latest"] = new LLMModelMetadata
        {
            Id = "mistral-small-latest",
            DisplayName = "mistral-small-latest",
                ProviderType = "copilot",
                OwnedBy = "mistral",
                ContextWindowTokens = 128000,
                MaxInputTokens = 128000,
                MaxOutputTokens = 8192,
            Pricing = new ModelPricingMetadata
            {
                Currency = "USD",
                InputPer1MTokens = 0.2m,
                OutputPer1MTokens = 0.6m,
            },
            Capabilities = new ModelCapabilityMetadata
            {
                SupportsTemperature = true,
                SupportsReasoningEffort = false,
                SupportsStructuredOutput = true,
                SupportsTools = true,
                SupportsJsonMode = true,
            },
        },
        ["mistral-embed"] = new LLMModelMetadata
        {
            Id = "mistral-embed",
            DisplayName = "mistral-embed",
                ProviderType = "copilot",
                OwnedBy = "mistral",
            Pricing = new ModelPricingMetadata
            {
                Currency = "USD",
                InputPer1MTokens = 0.1m,
                OutputPer1MTokens = 0.0m,
            },
            Capabilities = new ModelCapabilityMetadata
            {
                SupportsTemperature = false,
                SupportsReasoningEffort = false,
                SupportsStructuredOutput = false,
                SupportsTools = false,
                SupportsJsonMode = false,
                SupportsEmbeddings = true,
            },
        },
        ["deepseek-chat"] = new LLMModelMetadata
        {
            Id = "deepseek-chat",
            DisplayName = "deepseek-chat",
                ProviderType = "copilot",
                OwnedBy = "deepseek",
                ContextWindowTokens = 64000,
                MaxInputTokens = 64000,
                MaxOutputTokens = 8192,
            Pricing = new ModelPricingMetadata
            {
                Currency = "USD",
                InputPer1MTokens = 0.14m,
                OutputPer1MTokens = 0.28m,
            },
            Capabilities = new ModelCapabilityMetadata
            {
                SupportsTemperature = true,
                SupportsReasoningEffort = false,
                SupportsStructuredOutput = true,
                SupportsTools = true,
                SupportsJsonMode = true,
            },
        },
        ["deepseek-reasoner"] = new LLMModelMetadata
        {
            Id = "deepseek-reasoner",
            DisplayName = "deepseek-reasoner",
                ProviderType = "copilot",
                OwnedBy = "deepseek",
                ContextWindowTokens = 64000,
                MaxInputTokens = 64000,
                MaxOutputTokens = 8192,
            Pricing = new ModelPricingMetadata
            {
                Currency = "USD",
                InputPer1MTokens = 0.55m,
                OutputPer1MTokens = 2.19m,
            },
            Capabilities = new ModelCapabilityMetadata
            {
                SupportsTemperature = false,
                SupportsReasoningEffort = true,
                SupportsStructuredOutput = true,
                SupportsTools = true,
                SupportsJsonMode = true,
                SupportedReasoningEfforts = ["minimal", "low", "medium", "high"],
                UnsupportedRequestParameters = ["temperature"],
            },
        },
        ["gpt-5.4"] = new LLMModelMetadata
        {
            Id = "gpt-5.4",
            DisplayName = "gpt-5.4",
                ProviderType = "openai",
                OwnedBy = "openai",
                ContextWindowTokens = 400000,
                MaxInputTokens = 400000,
                MaxOutputTokens = 128000,
            Pricing = new ModelPricingMetadata
            {
                Currency = "USD",
                InputPer1MTokens = 75.0m,
                OutputPer1MTokens = 150.0m,
            },
            Capabilities = new ModelCapabilityMetadata
            {
                SupportsTemperature = false,
                SupportsReasoningEffort = true,
                SupportsStructuredOutput = true,
                SupportsTools = true,
                SupportsJsonMode = true,
                SupportedReasoningEfforts = ["minimal", "low", "medium", "high"],
                UnsupportedRequestParameters = ["temperature"],
            },
        },
    }.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase);

    private static readonly FrozenDictionary<string, string> BuiltinAliases = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        ["gpt4o"] = "gpt-4o",
        ["gpt4o-mini"] = "gpt-4o-mini",
        ["gpt-4-o"] = "gpt-4o",
        ["gpt-4-o-mini"] = "gpt-4o-mini",
        ["embedding-3-large"] = "text-embedding-3-large",
        ["embedding-3-small"] = "text-embedding-3-small",
        ["ada-002"] = "text-embedding-ada-002",
        ["text-embedding-ada"] = "text-embedding-ada-002",
        ["claude-3.5-sonnet"] = "claude-3-5-sonnet-20241022",
        ["claude-3.5-haiku"] = "claude-3-5-haiku-20241022",
        ["claude-3.7-sonnet"] = "claude-3-7-sonnet-20250219",
        ["claude-4-sonnet"] = "claude-sonnet-4-20250514",
        ["claude-4-haiku"] = "claude-haiku-4-20250514",
        ["gpt-4.5"] = "chatgpt-4.5-preview",
        ["openai/gpt-4o"] = "gpt-4o",
        ["openai/gpt-4o-mini"] = "gpt-4o-mini",
        ["openai/o4-mini"] = "o4-mini",
        ["openai/o3-mini"] = "o3-mini",
        ["anthropic/claude-sonnet-4"] = "claude-sonnet-4-20250514",
        ["anthropic/claude-haiku-4"] = "claude-haiku-4-20250514",
        ["gpt-5.4"] = "gpt-5.4",
    }.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase);
}

