// <auto-generated/>
// Embedded model metadata catalog. Update together with Telemetry/model-metadata.json.

using System.Collections.Frozen;

namespace GnOuGo.AI.Core;

public static partial class ModelMetadataCatalog
{
    private static readonly FrozenDictionary<string, LLMModelMetadata> BuiltinModels = new Dictionary<string, LLMModelMetadata>(StringComparer.OrdinalIgnoreCase)
    {
        ["text-embedding-3-large"] = Metadata("text-embedding-3-large", "openai", "openai", null, null, null, 0.13m, 0.0m, temp: false, reasoning: false, structured: false, tools: false, json: false, embeddings: true),
        ["text-embedding-3-small"] = Metadata("text-embedding-3-small", "openai", "openai", null, null, null, 0.02m, 0.0m, temp: false, reasoning: false, structured: false, tools: false, json: false, embeddings: true),
        ["text-embedding-ada-002"] = Metadata("text-embedding-ada-002", "openai", "openai", null, null, null, 0.10m, 0.0m, temp: false, reasoning: false, structured: false, tools: false, json: false, embeddings: true),

        ["gpt-4o"] = Metadata("gpt-4o", "openai", "openai", 128000, 128000, 16384, 2.50m, 10.00m, temp: true, reasoning: false, structured: true, tools: true, json: true, vision: true),
        ["gpt-4o-2024-11-20"] = Metadata("gpt-4o-2024-11-20", "openai", "openai", 128000, 128000, 16384, 2.50m, 10.00m, temp: true, reasoning: false, structured: true, tools: true, json: true, vision: true),
        ["gpt-4o-mini"] = Metadata("gpt-4o-mini", "openai", "openai", 128000, 128000, 16384, 0.15m, 0.60m, temp: true, reasoning: false, structured: true, tools: true, json: true, vision: true),
        ["gpt-4o-mini-2024-07-18"] = Metadata("gpt-4o-mini-2024-07-18", "openai", "openai", 128000, 128000, 16384, 0.15m, 0.60m, temp: true, reasoning: false, structured: true, tools: true, json: true, vision: true),
        ["gpt-4.1"] = Metadata("gpt-4.1", "openai", "openai", 1047576, 1047576, 32768, 2.00m, 8.00m, temp: true, reasoning: false, structured: true, tools: true, json: true, vision: true),
        ["gpt-4.1-mini"] = Metadata("gpt-4.1-mini", "openai", "openai", 1047576, 1047576, 32768, 0.40m, 1.60m, temp: true, reasoning: false, structured: true, tools: true, json: true, vision: true),
        ["gpt-4.1-nano"] = Metadata("gpt-4.1-nano", "openai", "openai", 1047576, 1047576, 32768, 0.10m, 0.40m, temp: true, reasoning: false, structured: true, tools: true, json: true, vision: true),
        ["gpt-4-turbo"] = Metadata("gpt-4-turbo", "openai", "openai", 128000, 128000, 4096, 10.00m, 30.00m, temp: true, reasoning: false, structured: true, tools: true, json: true, vision: true),
        ["gpt-3.5-turbo"] = Metadata("gpt-3.5-turbo", "openai", "openai", 16385, 16385, 4096, 0.50m, 1.50m, temp: true, reasoning: false, structured: true, tools: true, json: true),

        ["o1"] = ReasoningMetadata("o1", "openai", "openai", 200000, 200000, 100000, 15.00m, 60.00m),
        ["o1-mini"] = ReasoningMetadata("o1-mini", "openai", "openai", 128000, 128000, 65536, 1.10m, 4.40m),
        ["o1-pro"] = ReasoningMetadata("o1-pro", "openai", "openai", 200000, 200000, 100000, 150.00m, 600.00m),
        ["o3"] = ReasoningMetadata("o3", "openai", "openai", 200000, 200000, 100000, 2.00m, 8.00m),
        ["o3-mini"] = ReasoningMetadata("o3-mini", "openai", "openai", 200000, 200000, 100000, 1.10m, 4.40m),
        ["o4-mini"] = ReasoningMetadata("o4-mini", "openai", "openai", 200000, 200000, 100000, 1.10m, 4.40m),

        ["claude-3-5-sonnet-20241022"] = Metadata("claude-3-5-sonnet-20241022", "copilot", "anthropic", 200000, 200000, 8192, 3.00m, 15.00m, temp: true, reasoning: false, structured: false, tools: true, json: true),
        ["claude-3-5-haiku-20241022"] = Metadata("claude-3-5-haiku-20241022", "copilot", "anthropic", 200000, 200000, 8192, 0.80m, 4.00m, temp: true, reasoning: false, structured: false, tools: true, json: true),
        ["claude-sonnet-4-20250514"] = Metadata("claude-sonnet-4-20250514", "copilot", "anthropic", 200000, 200000, 64000, 3.00m, 15.00m, temp: true, reasoning: false, structured: false, tools: true, json: true),
        ["claude-haiku-4-20250514"] = Metadata("claude-haiku-4-20250514", "copilot", "anthropic", 200000, 200000, 8192, 0.80m, 4.00m, temp: true, reasoning: false, structured: false, tools: true, json: true),
        ["claude-3-7-sonnet-20250219"] = Metadata("claude-3-7-sonnet-20250219", "copilot", "anthropic", 200000, 200000, 64000, 3.00m, 15.00m, temp: true, reasoning: false, structured: false, tools: true, json: true),

        ["mistral-large-latest"] = Metadata("mistral-large-latest", "copilot", "mistral", 128000, 128000, 8192, 2.00m, 6.00m, temp: true, reasoning: false, structured: true, tools: true, json: true),
        ["mistral-small-latest"] = Metadata("mistral-small-latest", "copilot", "mistral", 128000, 128000, 8192, 0.20m, 0.60m, temp: true, reasoning: false, structured: true, tools: true, json: true),
        ["mistral-embed"] = Metadata("mistral-embed", "copilot", "mistral", null, null, null, 0.10m, 0.0m, temp: false, reasoning: false, structured: false, tools: false, json: false, embeddings: true),
        ["deepseek-chat"] = Metadata("deepseek-chat", "copilot", "deepseek", 64000, 64000, 8192, 0.14m, 0.28m, temp: true, reasoning: false, structured: true, tools: true, json: true),
        ["deepseek-reasoner"] = ReasoningMetadata("deepseek-reasoner", "copilot", "deepseek", 64000, 64000, 8192, 0.55m, 2.19m),
        ["gpt-5.4"] = ReasoningMetadata("gpt-5.4", "openai", "openai", 400000, 400000, 128000, 75.00m, 150.00m),
    }.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase);

    private static readonly FrozenDictionary<string, string> BuiltinAliases = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        ["gpt4o"] = "gpt-4o",
        ["gpt4o-mini"] = "gpt-4o-mini",
        ["gpt-4-o"] = "gpt-4o",
        ["gpt-4-o-mini"] = "gpt-4o-mini",
        ["embedding-3-large"] = "text-embedding-3-large",
        ["embedding-3-small"] = "text-embedding-3-small",
        ["ada-002"] = "text-embedding-ada-002",
        ["text-embedding-ada"] = "text-embedding-ada-002",
        ["claude-3.5-sonnet"] = "claude-3-5-sonnet-20241022",
        ["claude-3.5-haiku"] = "claude-3-5-haiku-20241022",
        ["claude-3.7-sonnet"] = "claude-3-7-sonnet-20250219",
        ["claude-4-sonnet"] = "claude-sonnet-4-20250514",
        ["claude-4-haiku"] = "claude-haiku-4-20250514",
        ["gpt-4.5"] = "chatgpt-4.5-preview",
        ["openai/gpt-4o"] = "gpt-4o",
        ["openai/gpt-4o-mini"] = "gpt-4o-mini",
        ["openai/o4-mini"] = "o4-mini",
        ["openai/o3-mini"] = "o3-mini",
        ["anthropic/claude-sonnet-4"] = "claude-sonnet-4-20250514",
        ["anthropic/claude-haiku-4"] = "claude-haiku-4-20250514",
    }.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase);

    private static LLMModelMetadata Metadata(
        string id,
        string providerType,
        string ownedBy,
        int? contextWindow,
        int? maxInput,
        int? maxOutput,
        decimal? inputPrice,
        decimal? outputPrice,
        bool? temp,
        bool? reasoning,
        bool? structured,
        bool? tools,
        bool? json,
        bool? vision = null,
        bool? embeddings = null)
        => new()
        {
            Id = id,
            DisplayName = id,
            ProviderType = providerType,
            OwnedBy = ownedBy,
            ContextWindowTokens = contextWindow,
            MaxInputTokens = maxInput,
            MaxOutputTokens = maxOutput,
            Pricing = new ModelPricingMetadata { InputPer1MTokens = inputPrice, OutputPer1MTokens = outputPrice },
            Capabilities = new ModelCapabilityMetadata
            {
                SupportsTemperature = temp,
                SupportsReasoningEffort = reasoning,
                SupportsStructuredOutput = structured,
                SupportsTools = tools,
                SupportsJsonMode = json,
                SupportsVision = vision,
                SupportsEmbeddings = embeddings
            }
        };

    private static LLMModelMetadata ReasoningMetadata(
        string id,
        string providerType,
        string ownedBy,
        int? contextWindow,
        int? maxInput,
        int? maxOutput,
        decimal? inputPrice,
        decimal? outputPrice)
    {
        var metadata = Metadata(id, providerType, ownedBy, contextWindow, maxInput, maxOutput, inputPrice, outputPrice,
            temp: false, reasoning: true, structured: true, tools: true, json: true);
        metadata.Capabilities.SupportedReasoningEfforts = ["minimal", "low", "medium", "high"];
        metadata.Capabilities.UnsupportedRequestParameters = ["temperature"];
        return metadata;
    }
}

