// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace GnOuGo.Agent.Server.Planning.CompiledModels
{
    public partial class PlanningDbContextModel
    {
        private PlanningDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("07137bdb-a2ef-4ba5-9fb1-8c808e06d769"), entityTypeCount: 2)
        {
        }

        partial void Initialize()
        {
            var planningCallIndex = PlanningCallIndexEntityType.Create(this);
            var planningSessionIndex = PlanningSessionIndexEntityType.Create(this);

            PlanningCallIndexEntityType.CreateAnnotations(planningCallIndex);
            PlanningSessionIndexEntityType.CreateAnnotations(planningSessionIndex);

            AddAnnotation("ProductVersion", "10.0.11");
        }
    }
}
