// <auto-generated />
using GnOuGo.Agent.Server.Planning;
using GnOuGo.Agent.Server.Planning.CompiledModels;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(PlanningDbContext), typeof(PlanningDbContextModel))]
