// <auto-generated />
using System;
using System.Reflection;
using GnOuGo.Files.Server.Models;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace GnOuGo.Files.Server.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class FileRecordEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "GnOuGo.Files.Server.Models.FileRecord",
                typeof(FileRecord),
                baseEntityType,
                propertyCount: 9,
                unnamedIndexCount: 2,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(string),
                propertyInfo: typeof(FileRecord).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FileRecord).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 64);
            id.AddAnnotation("Relational:ColumnName", "id");

            var contentType = runtimeEntityType.AddProperty(
                "ContentType",
                typeof(string),
                propertyInfo: typeof(FileRecord).GetProperty("ContentType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FileRecord).GetField("<ContentType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 256);
            contentType.AddAnnotation("Relational:ColumnName", "content_type");

            var createdUtc = runtimeEntityType.AddProperty(
                "CreatedUtc",
                typeof(DateTimeOffset),
                propertyInfo: typeof(FileRecord).GetProperty("CreatedUtc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FileRecord).GetField("<CreatedUtc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            createdUtc.AddAnnotation("Relational:ColumnName", "created_utc");

            var expiresUtc = runtimeEntityType.AddProperty(
                "ExpiresUtc",
                typeof(DateTimeOffset),
                propertyInfo: typeof(FileRecord).GetProperty("ExpiresUtc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FileRecord).GetField("<ExpiresUtc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            expiresUtc.AddAnnotation("Relational:ColumnName", "expires_utc");

            var originalFileName = runtimeEntityType.AddProperty(
                "OriginalFileName",
                typeof(string),
                propertyInfo: typeof(FileRecord).GetProperty("OriginalFileName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FileRecord).GetField("<OriginalFileName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 512);
            originalFileName.AddAnnotation("Relational:ColumnName", "original_file_name");

            var sizeBytes = runtimeEntityType.AddProperty(
                "SizeBytes",
                typeof(long),
                propertyInfo: typeof(FileRecord).GetProperty("SizeBytes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FileRecord).GetField("<SizeBytes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            sizeBytes.AddAnnotation("Relational:ColumnName", "size_bytes");

            var storedFileName = runtimeEntityType.AddProperty(
                "StoredFileName",
                typeof(string),
                propertyInfo: typeof(FileRecord).GetProperty("StoredFileName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FileRecord).GetField("<StoredFileName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 128);
            storedFileName.AddAnnotation("Relational:ColumnName", "stored_file_name");

            var storedPath = runtimeEntityType.AddProperty(
                "StoredPath",
                typeof(string),
                propertyInfo: typeof(FileRecord).GetProperty("StoredPath", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FileRecord).GetField("<StoredPath>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 2048);
            storedPath.AddAnnotation("Relational:ColumnName", "stored_path");

            var tenantId = runtimeEntityType.AddProperty(
                "TenantId",
                typeof(string),
                propertyInfo: typeof(FileRecord).GetProperty("TenantId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FileRecord).GetField("<TenantId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 128);
            tenantId.AddAnnotation("Relational:ColumnName", "tenant_id");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { expiresUtc });

            var index0 = runtimeEntityType.AddIndex(
                new[] { tenantId, expiresUtc });

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "files");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
