// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace GnOuGo.Files.Server.Data.CompiledModels
{
    public partial class FilesDbContextModel
    {
        private FilesDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("93939bcb-0805-48b4-b32c-76357ee0c493"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var fileRecord = FileRecordEntityType.Create(this);

            FileRecordEntityType.CreateAnnotations(fileRecord);

            AddAnnotation("ProductVersion", "10.0.5");
        }
    }
}
