// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using GnOuGo.Files.Server.Models;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;

#pragma warning disable 219, 612, 618
#nullable disable

namespace GnOuGo.Files.Server.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class FileRecordEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "GnOuGo.Files.Server.Models.FileRecord",
                typeof(FileRecord),
                baseEntityType,
                propertyCount: 9,
                unnamedIndexCount: 2,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(string),
                propertyInfo: typeof(FileRecord).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FileRecord).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 64);
            id.SetGetter(
                string (FileRecord instance) => FileRecordUnsafeAccessors.Id(instance),
                bool (FileRecord instance) => FileRecordUnsafeAccessors.Id(instance) == null);
            id.SetSetter(
                FileRecord (FileRecord instance, string value) =>
                {
                    FileRecordUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                FileRecord (FileRecord instance, string value) =>
                {
                    FileRecordUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                string (IInternalEntry entry) => FileRecordUnsafeAccessors.Id(((FileRecord)(entry.Entity))),
                string (IInternalEntry entry) => FileRecordUnsafeAccessors.Id(((FileRecord)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(id, 0),
                string (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<string>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: -1);
            id.TypeMapping = SqliteStringTypeMapping.Default;
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(id));
            id.AddAnnotation("Relational:ColumnName", "id");

            var contentType = runtimeEntityType.AddProperty(
                "ContentType",
                typeof(string),
                propertyInfo: typeof(FileRecord).GetProperty("ContentType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FileRecord).GetField("<ContentType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 256);
            contentType.SetGetter(
                string (FileRecord instance) => FileRecordUnsafeAccessors.ContentType(instance),
                bool (FileRecord instance) => FileRecordUnsafeAccessors.ContentType(instance) == null);
            contentType.SetSetter(
                FileRecord (FileRecord instance, string value) =>
                {
                    FileRecordUnsafeAccessors.ContentType(instance) = value;
                    return instance;
                });
            contentType.SetMaterializationSetter(
                FileRecord (FileRecord instance, string value) =>
                {
                    FileRecordUnsafeAccessors.ContentType(instance) = value;
                    return instance;
                });
            contentType.SetAccessors(
                string (IInternalEntry entry) => FileRecordUnsafeAccessors.ContentType(((FileRecord)(entry.Entity))),
                string (IInternalEntry entry) => FileRecordUnsafeAccessors.ContentType(((FileRecord)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(contentType, 1),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(contentType));
            contentType.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            contentType.TypeMapping = SqliteStringTypeMapping.Default;
            contentType.AddAnnotation("Relational:ColumnName", "content_type");

            var createdUtc = runtimeEntityType.AddProperty(
                "CreatedUtc",
                typeof(DateTimeOffset),
                propertyInfo: typeof(FileRecord).GetProperty("CreatedUtc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FileRecord).GetField("<CreatedUtc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            createdUtc.SetGetter(
                DateTimeOffset (FileRecord instance) => FileRecordUnsafeAccessors.CreatedUtc(instance),
                bool (FileRecord instance) => FileRecordUnsafeAccessors.CreatedUtc(instance).Equals(default(DateTimeOffset)));
            createdUtc.SetSetter(
                FileRecord (FileRecord instance, DateTimeOffset value) =>
                {
                    FileRecordUnsafeAccessors.CreatedUtc(instance) = value;
                    return instance;
                });
            createdUtc.SetMaterializationSetter(
                FileRecord (FileRecord instance, DateTimeOffset value) =>
                {
                    FileRecordUnsafeAccessors.CreatedUtc(instance) = value;
                    return instance;
                });
            createdUtc.SetAccessors(
                DateTimeOffset (IInternalEntry entry) => FileRecordUnsafeAccessors.CreatedUtc(((FileRecord)(entry.Entity))),
                DateTimeOffset (IInternalEntry entry) => FileRecordUnsafeAccessors.CreatedUtc(((FileRecord)(entry.Entity))),
                DateTimeOffset (IInternalEntry entry) => entry.ReadOriginalValue<DateTimeOffset>(createdUtc, 2),
                DateTimeOffset (IInternalEntry entry) => entry.GetCurrentValue<DateTimeOffset>(createdUtc));
            createdUtc.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            createdUtc.TypeMapping = SqliteDateTimeOffsetTypeMapping.Default;
            createdUtc.SetComparer(new ValueComparer<DateTimeOffset>(
                bool (DateTimeOffset left, DateTimeOffset right) => left.Equals(right),
                int (DateTimeOffset value) => ((object)value).GetHashCode(),
                DateTimeOffset (DateTimeOffset value) => value));
            createdUtc.AddAnnotation("Relational:ColumnName", "created_utc");

            var expiresUtc = runtimeEntityType.AddProperty(
                "ExpiresUtc",
                typeof(DateTimeOffset),
                propertyInfo: typeof(FileRecord).GetProperty("ExpiresUtc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FileRecord).GetField("<ExpiresUtc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            expiresUtc.SetGetter(
                DateTimeOffset (FileRecord instance) => FileRecordUnsafeAccessors.ExpiresUtc(instance),
                bool (FileRecord instance) => FileRecordUnsafeAccessors.ExpiresUtc(instance).Equals(default(DateTimeOffset)));
            expiresUtc.SetSetter(
                FileRecord (FileRecord instance, DateTimeOffset value) =>
                {
                    FileRecordUnsafeAccessors.ExpiresUtc(instance) = value;
                    return instance;
                });
            expiresUtc.SetMaterializationSetter(
                FileRecord (FileRecord instance, DateTimeOffset value) =>
                {
                    FileRecordUnsafeAccessors.ExpiresUtc(instance) = value;
                    return instance;
                });
            expiresUtc.SetAccessors(
                DateTimeOffset (IInternalEntry entry) => FileRecordUnsafeAccessors.ExpiresUtc(((FileRecord)(entry.Entity))),
                DateTimeOffset (IInternalEntry entry) => FileRecordUnsafeAccessors.ExpiresUtc(((FileRecord)(entry.Entity))),
                DateTimeOffset (IInternalEntry entry) => entry.ReadOriginalValue<DateTimeOffset>(expiresUtc, 3),
                DateTimeOffset (IInternalEntry entry) => entry.GetCurrentValue<DateTimeOffset>(expiresUtc));
            expiresUtc.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            expiresUtc.TypeMapping = SqliteDateTimeOffsetTypeMapping.Default;
            expiresUtc.SetComparer(new ValueComparer<DateTimeOffset>(
                bool (DateTimeOffset left, DateTimeOffset right) => left.Equals(right),
                int (DateTimeOffset value) => ((object)value).GetHashCode(),
                DateTimeOffset (DateTimeOffset value) => value));
            expiresUtc.AddAnnotation("Relational:ColumnName", "expires_utc");

            var originalFileName = runtimeEntityType.AddProperty(
                "OriginalFileName",
                typeof(string),
                propertyInfo: typeof(FileRecord).GetProperty("OriginalFileName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FileRecord).GetField("<OriginalFileName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 512);
            originalFileName.SetGetter(
                string (FileRecord instance) => FileRecordUnsafeAccessors.OriginalFileName(instance),
                bool (FileRecord instance) => FileRecordUnsafeAccessors.OriginalFileName(instance) == null);
            originalFileName.SetSetter(
                FileRecord (FileRecord instance, string value) =>
                {
                    FileRecordUnsafeAccessors.OriginalFileName(instance) = value;
                    return instance;
                });
            originalFileName.SetMaterializationSetter(
                FileRecord (FileRecord instance, string value) =>
                {
                    FileRecordUnsafeAccessors.OriginalFileName(instance) = value;
                    return instance;
                });
            originalFileName.SetAccessors(
                string (IInternalEntry entry) => FileRecordUnsafeAccessors.OriginalFileName(((FileRecord)(entry.Entity))),
                string (IInternalEntry entry) => FileRecordUnsafeAccessors.OriginalFileName(((FileRecord)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(originalFileName, 4),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(originalFileName));
            originalFileName.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            originalFileName.TypeMapping = SqliteStringTypeMapping.Default;
            originalFileName.AddAnnotation("Relational:ColumnName", "original_file_name");

            var sizeBytes = runtimeEntityType.AddProperty(
                "SizeBytes",
                typeof(long),
                propertyInfo: typeof(FileRecord).GetProperty("SizeBytes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FileRecord).GetField("<SizeBytes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            sizeBytes.SetGetter(
                long (FileRecord instance) => FileRecordUnsafeAccessors.SizeBytes(instance),
                bool (FileRecord instance) => FileRecordUnsafeAccessors.SizeBytes(instance) == 0L);
            sizeBytes.SetSetter(
                FileRecord (FileRecord instance, long value) =>
                {
                    FileRecordUnsafeAccessors.SizeBytes(instance) = value;
                    return instance;
                });
            sizeBytes.SetMaterializationSetter(
                FileRecord (FileRecord instance, long value) =>
                {
                    FileRecordUnsafeAccessors.SizeBytes(instance) = value;
                    return instance;
                });
            sizeBytes.SetAccessors(
                long (IInternalEntry entry) => FileRecordUnsafeAccessors.SizeBytes(((FileRecord)(entry.Entity))),
                long (IInternalEntry entry) => FileRecordUnsafeAccessors.SizeBytes(((FileRecord)(entry.Entity))),
                long (IInternalEntry entry) => entry.ReadOriginalValue<long>(sizeBytes, 5),
                long (IInternalEntry entry) => entry.GetCurrentValue<long>(sizeBytes));
            sizeBytes.SetPropertyIndexes(
                index: 5,
                originalValueIndex: 5,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            sizeBytes.TypeMapping = LongTypeMapping.Default.Clone(
                comparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                keyComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                providerValueComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));
            sizeBytes.AddAnnotation("Relational:ColumnName", "size_bytes");

            var storedFileName = runtimeEntityType.AddProperty(
                "StoredFileName",
                typeof(string),
                propertyInfo: typeof(FileRecord).GetProperty("StoredFileName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FileRecord).GetField("<StoredFileName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 128);
            storedFileName.SetGetter(
                string (FileRecord instance) => FileRecordUnsafeAccessors.StoredFileName(instance),
                bool (FileRecord instance) => FileRecordUnsafeAccessors.StoredFileName(instance) == null);
            storedFileName.SetSetter(
                FileRecord (FileRecord instance, string value) =>
                {
                    FileRecordUnsafeAccessors.StoredFileName(instance) = value;
                    return instance;
                });
            storedFileName.SetMaterializationSetter(
                FileRecord (FileRecord instance, string value) =>
                {
                    FileRecordUnsafeAccessors.StoredFileName(instance) = value;
                    return instance;
                });
            storedFileName.SetAccessors(
                string (IInternalEntry entry) => FileRecordUnsafeAccessors.StoredFileName(((FileRecord)(entry.Entity))),
                string (IInternalEntry entry) => FileRecordUnsafeAccessors.StoredFileName(((FileRecord)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(storedFileName, 6),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(storedFileName));
            storedFileName.SetPropertyIndexes(
                index: 6,
                originalValueIndex: 6,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            storedFileName.TypeMapping = SqliteStringTypeMapping.Default;
            storedFileName.AddAnnotation("Relational:ColumnName", "stored_file_name");

            var storedPath = runtimeEntityType.AddProperty(
                "StoredPath",
                typeof(string),
                propertyInfo: typeof(FileRecord).GetProperty("StoredPath", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FileRecord).GetField("<StoredPath>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 2048);
            storedPath.SetGetter(
                string (FileRecord instance) => FileRecordUnsafeAccessors.StoredPath(instance),
                bool (FileRecord instance) => FileRecordUnsafeAccessors.StoredPath(instance) == null);
            storedPath.SetSetter(
                FileRecord (FileRecord instance, string value) =>
                {
                    FileRecordUnsafeAccessors.StoredPath(instance) = value;
                    return instance;
                });
            storedPath.SetMaterializationSetter(
                FileRecord (FileRecord instance, string value) =>
                {
                    FileRecordUnsafeAccessors.StoredPath(instance) = value;
                    return instance;
                });
            storedPath.SetAccessors(
                string (IInternalEntry entry) => FileRecordUnsafeAccessors.StoredPath(((FileRecord)(entry.Entity))),
                string (IInternalEntry entry) => FileRecordUnsafeAccessors.StoredPath(((FileRecord)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(storedPath, 7),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(storedPath));
            storedPath.SetPropertyIndexes(
                index: 7,
                originalValueIndex: 7,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            storedPath.TypeMapping = SqliteStringTypeMapping.Default;
            storedPath.AddAnnotation("Relational:ColumnName", "stored_path");

            var tenantId = runtimeEntityType.AddProperty(
                "TenantId",
                typeof(string),
                propertyInfo: typeof(FileRecord).GetProperty("TenantId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FileRecord).GetField("<TenantId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 128);
            tenantId.SetGetter(
                string (FileRecord instance) => FileRecordUnsafeAccessors.TenantId(instance),
                bool (FileRecord instance) => FileRecordUnsafeAccessors.TenantId(instance) == null);
            tenantId.SetSetter(
                FileRecord (FileRecord instance, string value) =>
                {
                    FileRecordUnsafeAccessors.TenantId(instance) = value;
                    return instance;
                });
            tenantId.SetMaterializationSetter(
                FileRecord (FileRecord instance, string value) =>
                {
                    FileRecordUnsafeAccessors.TenantId(instance) = value;
                    return instance;
                });
            tenantId.SetAccessors(
                string (IInternalEntry entry) => FileRecordUnsafeAccessors.TenantId(((FileRecord)(entry.Entity))),
                string (IInternalEntry entry) => FileRecordUnsafeAccessors.TenantId(((FileRecord)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(tenantId, 8),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(tenantId));
            tenantId.SetPropertyIndexes(
                index: 8,
                originalValueIndex: 8,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            tenantId.TypeMapping = SqliteStringTypeMapping.Default;
            tenantId.AddAnnotation("Relational:ColumnName", "tenant_id");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { expiresUtc });

            var index0 = runtimeEntityType.AddIndex(
                new[] { tenantId, expiresUtc });

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var contentType = runtimeEntityType.FindProperty("ContentType");
            var createdUtc = runtimeEntityType.FindProperty("CreatedUtc");
            var expiresUtc = runtimeEntityType.FindProperty("ExpiresUtc");
            var originalFileName = runtimeEntityType.FindProperty("OriginalFileName");
            var sizeBytes = runtimeEntityType.FindProperty("SizeBytes");
            var storedFileName = runtimeEntityType.FindProperty("StoredFileName");
            var storedPath = runtimeEntityType.FindProperty("StoredPath");
            var tenantId = runtimeEntityType.FindProperty("TenantId");
            var key = runtimeEntityType.FindKey(new[] { id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNullableFactory<string, int>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<string>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((FileRecord)(source.Entity));
                    return ((ISnapshot)(new Snapshot<string, string, DateTimeOffset, DateTimeOffset, string, long, string, string, string>((source.GetCurrentValue<string>(id) == null ? null : ((ValueComparer<string>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(id))), (source.GetCurrentValue<string>(contentType) == null ? null : ((ValueComparer<string>)(((IProperty)contentType).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(contentType))), ((ValueComparer<DateTimeOffset>)(((IProperty)createdUtc).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTimeOffset>(createdUtc)), ((ValueComparer<DateTimeOffset>)(((IProperty)expiresUtc).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTimeOffset>(expiresUtc)), (source.GetCurrentValue<string>(originalFileName) == null ? null : ((ValueComparer<string>)(((IProperty)originalFileName).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(originalFileName))), ((ValueComparer<long>)(((IProperty)sizeBytes).GetValueComparer())).Snapshot(source.GetCurrentValue<long>(sizeBytes)), (source.GetCurrentValue<string>(storedFileName) == null ? null : ((ValueComparer<string>)(((IProperty)storedFileName).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(storedFileName))), (source.GetCurrentValue<string>(storedPath) == null ? null : ((ValueComparer<string>)(((IProperty)storedPath).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(storedPath))), (source.GetCurrentValue<string>(tenantId) == null ? null : ((ValueComparer<string>)(((IProperty)tenantId).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(tenantId))))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => Snapshot.Empty);
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((FileRecord)(source.Entity));
                    return ((ISnapshot)(new Snapshot<string>((source.GetCurrentValue<string>(id) == null ? null : ((ValueComparer<string>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<string>(id))))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 9,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 9,
                shadowCount: 0,
                relationshipCount: 1,
                storeGeneratedCount: 0));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "files");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
