// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Update.Internal;

#pragma warning disable 219, 612, 618
#nullable disable

namespace GnOuGo.Files.Server.Data.CompiledModels
{
    public partial class FilesDbContextModel
    {
        private FilesDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("2f893c30-849e-4ca8-b6ca-a9190d2a4a24"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var fileRecord = FileRecordEntityType.Create(this);

            FileRecordEntityType.CreateAnnotations(fileRecord);

            AddAnnotation("ProductVersion", "10.0.11");
            AddRuntimeAnnotation("Relational:RelationalModelFactory", () => CreateRelationalModel());
        }

        private IRelationalModel CreateRelationalModel()
        {
            var relationalModel = new RelationalModel(this);

            var fileRecord = FindEntityType("GnOuGo.Files.Server.Models.FileRecord")!;

            var defaultTableMappings = new List<TableMappingBase<ColumnMappingBase>>();
            fileRecord.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings);
            var gnOuGoFilesServerModelsFileRecordTableBase = new TableBase("GnOuGo.Files.Server.Models.FileRecord", null, relationalModel);
            var content_typeColumnBase = new ColumnBase<ColumnMappingBase>("content_type", "TEXT", gnOuGoFilesServerModelsFileRecordTableBase);
            gnOuGoFilesServerModelsFileRecordTableBase.Columns.Add("content_type", content_typeColumnBase);
            var created_utcColumnBase = new ColumnBase<ColumnMappingBase>("created_utc", "TEXT", gnOuGoFilesServerModelsFileRecordTableBase);
            gnOuGoFilesServerModelsFileRecordTableBase.Columns.Add("created_utc", created_utcColumnBase);
            var expires_utcColumnBase = new ColumnBase<ColumnMappingBase>("expires_utc", "TEXT", gnOuGoFilesServerModelsFileRecordTableBase);
            gnOuGoFilesServerModelsFileRecordTableBase.Columns.Add("expires_utc", expires_utcColumnBase);
            var idColumnBase = new ColumnBase<ColumnMappingBase>("id", "TEXT", gnOuGoFilesServerModelsFileRecordTableBase);
            gnOuGoFilesServerModelsFileRecordTableBase.Columns.Add("id", idColumnBase);
            var original_file_nameColumnBase = new ColumnBase<ColumnMappingBase>("original_file_name", "TEXT", gnOuGoFilesServerModelsFileRecordTableBase);
            gnOuGoFilesServerModelsFileRecordTableBase.Columns.Add("original_file_name", original_file_nameColumnBase);
            var size_bytesColumnBase = new ColumnBase<ColumnMappingBase>("size_bytes", "INTEGER", gnOuGoFilesServerModelsFileRecordTableBase);
            gnOuGoFilesServerModelsFileRecordTableBase.Columns.Add("size_bytes", size_bytesColumnBase);
            var stored_file_nameColumnBase = new ColumnBase<ColumnMappingBase>("stored_file_name", "TEXT", gnOuGoFilesServerModelsFileRecordTableBase);
            gnOuGoFilesServerModelsFileRecordTableBase.Columns.Add("stored_file_name", stored_file_nameColumnBase);
            var stored_pathColumnBase = new ColumnBase<ColumnMappingBase>("stored_path", "TEXT", gnOuGoFilesServerModelsFileRecordTableBase);
            gnOuGoFilesServerModelsFileRecordTableBase.Columns.Add("stored_path", stored_pathColumnBase);
            var tenant_idColumnBase = new ColumnBase<ColumnMappingBase>("tenant_id", "TEXT", gnOuGoFilesServerModelsFileRecordTableBase);
            gnOuGoFilesServerModelsFileRecordTableBase.Columns.Add("tenant_id", tenant_idColumnBase);
            relationalModel.DefaultTables.Add("GnOuGo.Files.Server.Models.FileRecord", gnOuGoFilesServerModelsFileRecordTableBase);
            var gnOuGoFilesServerModelsFileRecordMappingBase = new TableMappingBase<ColumnMappingBase>(fileRecord, gnOuGoFilesServerModelsFileRecordTableBase, null);
            gnOuGoFilesServerModelsFileRecordTableBase.AddTypeMapping(gnOuGoFilesServerModelsFileRecordMappingBase, false);
            defaultTableMappings.Add(gnOuGoFilesServerModelsFileRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase, fileRecord.FindProperty("Id")!, gnOuGoFilesServerModelsFileRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)content_typeColumnBase, fileRecord.FindProperty("ContentType")!, gnOuGoFilesServerModelsFileRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)created_utcColumnBase, fileRecord.FindProperty("CreatedUtc")!, gnOuGoFilesServerModelsFileRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)expires_utcColumnBase, fileRecord.FindProperty("ExpiresUtc")!, gnOuGoFilesServerModelsFileRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)original_file_nameColumnBase, fileRecord.FindProperty("OriginalFileName")!, gnOuGoFilesServerModelsFileRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)size_bytesColumnBase, fileRecord.FindProperty("SizeBytes")!, gnOuGoFilesServerModelsFileRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)stored_file_nameColumnBase, fileRecord.FindProperty("StoredFileName")!, gnOuGoFilesServerModelsFileRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)stored_pathColumnBase, fileRecord.FindProperty("StoredPath")!, gnOuGoFilesServerModelsFileRecordMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)tenant_idColumnBase, fileRecord.FindProperty("TenantId")!, gnOuGoFilesServerModelsFileRecordMappingBase);

            var tableMappings = new List<TableMapping>();
            fileRecord.SetRuntimeAnnotation("Relational:TableMappings", tableMappings);
            var filesTable = new Table("files", null, relationalModel);
            var idColumn = new Column("id", "TEXT", filesTable);
            filesTable.Columns.Add("id", idColumn);
            idColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(idColumn);
            var content_typeColumn = new Column("content_type", "TEXT", filesTable);
            filesTable.Columns.Add("content_type", content_typeColumn);
            content_typeColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(content_typeColumn);
            var created_utcColumn = new Column("created_utc", "TEXT", filesTable);
            filesTable.Columns.Add("created_utc", created_utcColumn);
            created_utcColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTimeOffset>(created_utcColumn);
            var expires_utcColumn = new Column("expires_utc", "TEXT", filesTable);
            filesTable.Columns.Add("expires_utc", expires_utcColumn);
            expires_utcColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTimeOffset>(expires_utcColumn);
            var original_file_nameColumn = new Column("original_file_name", "TEXT", filesTable);
            filesTable.Columns.Add("original_file_name", original_file_nameColumn);
            original_file_nameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(original_file_nameColumn);
            var size_bytesColumn = new Column("size_bytes", "INTEGER", filesTable);
            filesTable.Columns.Add("size_bytes", size_bytesColumn);
            size_bytesColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<long>(size_bytesColumn);
            var stored_file_nameColumn = new Column("stored_file_name", "TEXT", filesTable);
            filesTable.Columns.Add("stored_file_name", stored_file_nameColumn);
            stored_file_nameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(stored_file_nameColumn);
            var stored_pathColumn = new Column("stored_path", "TEXT", filesTable);
            filesTable.Columns.Add("stored_path", stored_pathColumn);
            stored_pathColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(stored_pathColumn);
            var tenant_idColumn = new Column("tenant_id", "TEXT", filesTable);
            filesTable.Columns.Add("tenant_id", tenant_idColumn);
            tenant_idColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(tenant_idColumn);
            relationalModel.Tables.Add(("files", null), filesTable);
            var filesTableMapping = new TableMapping(fileRecord, filesTable, null);
            filesTable.AddTypeMapping(filesTableMapping, false);
            tableMappings.Add(filesTableMapping);
            RelationalModel.CreateColumnMapping(idColumn, fileRecord.FindProperty("Id")!, filesTableMapping);
            RelationalModel.CreateColumnMapping(content_typeColumn, fileRecord.FindProperty("ContentType")!, filesTableMapping);
            RelationalModel.CreateColumnMapping(created_utcColumn, fileRecord.FindProperty("CreatedUtc")!, filesTableMapping);
            RelationalModel.CreateColumnMapping(expires_utcColumn, fileRecord.FindProperty("ExpiresUtc")!, filesTableMapping);
            RelationalModel.CreateColumnMapping(original_file_nameColumn, fileRecord.FindProperty("OriginalFileName")!, filesTableMapping);
            RelationalModel.CreateColumnMapping(size_bytesColumn, fileRecord.FindProperty("SizeBytes")!, filesTableMapping);
            RelationalModel.CreateColumnMapping(stored_file_nameColumn, fileRecord.FindProperty("StoredFileName")!, filesTableMapping);
            RelationalModel.CreateColumnMapping(stored_pathColumn, fileRecord.FindProperty("StoredPath")!, filesTableMapping);
            RelationalModel.CreateColumnMapping(tenant_idColumn, fileRecord.FindProperty("TenantId")!, filesTableMapping);
            var pK_files = new UniqueConstraint("PK_files", filesTable, new[] { idColumn });
            filesTable.PrimaryKey = pK_files;
            pK_files.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<string>(pK_files));
            var pK_filesKey = RelationalModel.GetKey(this,
                "GnOuGo.Files.Server.Models.FileRecord",
                new[] { "Id" });
            pK_files.MappedKeys.Add(pK_filesKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_filesKey).Add(pK_files);
            filesTable.UniqueConstraints.Add("PK_files", pK_files);
            var iX_files_expires_utc = new TableIndex(
            "IX_files_expires_utc", filesTable, new[] { expires_utcColumn }, false);
            iX_files_expires_utc.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<DateTimeOffset>(iX_files_expires_utc));
            var iX_files_expires_utcIx = RelationalModel.GetIndex(this,
                "GnOuGo.Files.Server.Models.FileRecord",
                new[] { "ExpiresUtc" });
            iX_files_expires_utc.MappedIndexes.Add(iX_files_expires_utcIx);
            RelationalModel.GetOrCreateTableIndexes(iX_files_expires_utcIx).Add(iX_files_expires_utc);
            filesTable.Indexes.Add("IX_files_expires_utc", iX_files_expires_utc);
            var iX_files_tenant_id_expires_utc = new TableIndex(
            "IX_files_tenant_id_expires_utc", filesTable, new[] { tenant_idColumn, expires_utcColumn }, false);
            iX_files_tenant_id_expires_utc.SetRowIndexValueFactory(new CompositeRowIndexValueFactory(iX_files_tenant_id_expires_utc));
            var iX_files_tenant_id_expires_utcIx = RelationalModel.GetIndex(this,
                "GnOuGo.Files.Server.Models.FileRecord",
                new[] { "TenantId", "ExpiresUtc" });
            iX_files_tenant_id_expires_utc.MappedIndexes.Add(iX_files_tenant_id_expires_utcIx);
            RelationalModel.GetOrCreateTableIndexes(iX_files_tenant_id_expires_utcIx).Add(iX_files_tenant_id_expires_utc);
            filesTable.Indexes.Add("IX_files_tenant_id_expires_utc", iX_files_tenant_id_expires_utc);
            return relationalModel.MakeReadOnly();
        }
    }
}
