// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using GnOuGo.Files.Server.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace GnOuGo.Files.Server.Data.CompiledModels
{
    public static class FileRecordUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref string Id(FileRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ContentType>k__BackingField")]
        public static extern ref string ContentType(FileRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedUtc>k__BackingField")]
        public static extern ref DateTimeOffset CreatedUtc(FileRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ExpiresUtc>k__BackingField")]
        public static extern ref DateTimeOffset ExpiresUtc(FileRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<OriginalFileName>k__BackingField")]
        public static extern ref string OriginalFileName(FileRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SizeBytes>k__BackingField")]
        public static extern ref long SizeBytes(FileRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<StoredFileName>k__BackingField")]
        public static extern ref string StoredFileName(FileRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<StoredPath>k__BackingField")]
        public static extern ref string StoredPath(FileRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TenantId>k__BackingField")]
        public static extern ref string TenantId(FileRecord @this);
    }
}
