#!/usr/bin/env python3
"""Generate the macOS ProxyCopilot formula from a stable release's archives."""
import argparse
import hashlib
from pathlib import Path
import re
from string import Template


FORMULA = Template('''# Generated by scripts/update-proxy-copilot-homebrew.py in GnouGo/GnouGo.
class GnougoProxyCopilot < Formula
  desc "Standalone local LLM proxy for VS Code Chat and Agent mode"
  homepage "https://github.com/GnouGo/GnouGo/tree/main/src/GnOuGo.ProxyCopilot.Server"
  version "${version}"
  license "Apache-2.0"

  on_arm do
    url "https://github.com/GnouGo/GnouGo/releases/download/v#{version}/GnOuGo.ProxyCopilot.Server-osx-arm64-aot.tar.gz"
    sha256 "${arm_sha}"
  end

  on_intel do
    url "https://github.com/GnouGo/GnouGo/releases/download/v#{version}/GnOuGo.ProxyCopilot.Server-osx-x64-aot.tar.gz"
    sha256 "${intel_sha}"
  end

  depends_on :macos

  on_macos do
    depends_on macos: :monterey
  end

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"GnOuGo.ProxyCopilot.Server" => "gnougo-proxy-copilot"
  end

  def caveats
    <<~EOS
      Run gnougo-proxy-copilot, then open http://127.0.0.1:5087/ui/.
      Configure providers with ProxyCopilot__Providers__... environment variables.
      Do not store private settings in the Cellar: upgrades replace that directory.
      No background service is started automatically.
    EOS
  end

  test do
    require "net/http"
    require "timeout"

    env = {
      "HOME" => testpath.to_s,
      "TMPDIR" => ENV.fetch("TMPDIR"),
      "PATH" => ENV.fetch("PATH"),
      "DOTNET_ENVIRONMENT" => "Production",
      "ASPNETCORE_ENVIRONMENT" => "Production",
      "OpenTelemetry__Enabled" => "false",
    }
    base = "http://127.0.0.1:#{free_port}"
    pid = spawn(env, (bin/"gnougo-proxy-copilot").to_s, "--urls", base,
                unsetenv_others: true, in: File::NULL,
                out: (testpath/"server.log").to_s, err: [:child, :out])
    begin
      Timeout.timeout(20) do
        loop do
          begin
            response = Net::HTTP.get_response(URI("#{base}/health"))
            assert_equal "200", response.code
            assert_equal "ok", JSON.parse(response.body)["status"]
            break
          rescue Errno::ECONNREFUSED
            sleep 0.2
          end
        end
      end
      assert_match "<html", Net::HTTP.get(URI("#{base}/ui/"))
      assert_empty JSON.parse(Net::HTTP.get(URI("#{base}/v1/models")))["data"]
    ensure
      Process.kill("TERM", pid)
      Process.wait(pid)
    end
  end
end
''')


def archive_sha256(artifacts, arch):
    name = f"GnOuGo.ProxyCopilot.Server-osx-{arch}-aot.tar.gz"
    matches = [path for path in artifacts.rglob(name) if path.is_file()]
    if len(matches) != 1:
        raise ValueError(f"Expected exactly one release archive {name}; found {len(matches)}.")
    with matches[0].open("rb") as archive:
        return hashlib.file_digest(archive, "sha256").hexdigest()


def update_formula(version_tag, artifacts, tap):
    if not re.fullmatch(r"v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)", version_tag):
        raise ValueError("Homebrew requires a stable release tag in vMAJOR.MINOR.PATCH format.")
    formula = FORMULA.substitute(
        version=version_tag[1:],
        arm_sha=archive_sha256(artifacts, "arm64"),
        intel_sha=archive_sha256(artifacts, "x64"),
    )
    destination = tap / "Formula/gnougo-proxy-copilot.rb"
    if destination.is_file() and destination.read_text(encoding="utf-8") == formula:
        return False
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(formula, encoding="utf-8")
    return True


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version-tag", required=True)
    parser.add_argument("--artifacts", required=True, type=Path)
    parser.add_argument("--tap", required=True, type=Path)
    args = parser.parse_args()
    changed = update_formula(args.version_tag, args.artifacts, args.tap)
    print("Updated ProxyCopilot Homebrew formula." if changed else "ProxyCopilot Homebrew formula is already up to date.")


if __name__ == "__main__":
    main()
