<#
.SYNOPSIS
    Downloads latest model pricing data and regenerates the C# pricing catalog.

.DESCRIPTION
    1) Optionally downloads model pricing from the LiteLLM community catalog (GitHub).
    2) Merges with the local model-pricing.json (local overrides win).
    3) Regenerates ModelPricingCatalog.Generated.cs for AOT-friendly embedding.

.PARAMETER DownloadLatest
    If set, fetches the latest prices from LiteLLM GitHub and merges them.
    Without this flag, only regenerates the C# file from the existing JSON.

.PARAMETER JsonPath
    Path to the local model-pricing.json file.

.PARAMETER OutputPath
    Path for the generated C# file.

.EXAMPLE
    # Regenerate C# from existing JSON only
    .\update-model-pricing.ps1

    # Download latest + merge + regenerate
    .\update-model-pricing.ps1 -DownloadLatest
#>
param(
    [switch]$DownloadLatest,
    [string]$JsonPath = "$PSScriptRoot\..\src\GnOuGo.AI.Core\Telemetry\model-pricing.json",
    [string]$OutputPath = "$PSScriptRoot\..\src\GnOuGo.AI.Core\Telemetry\ModelPricingCatalog.Generated.cs"
)

$ErrorActionPreference = "Stop"

$resolved = Resolve-Path $JsonPath -ErrorAction SilentlyContinue
if ($resolved) { $JsonPath = $resolved.Path }
Write-Host "JSON path : $JsonPath"
Write-Host "Output path: $OutputPath"

# ── 1) Optionally download & merge from LiteLLM ─────────────────────
if ($DownloadLatest) {
    Write-Host "`nDownloading latest pricing from LiteLLM..."
    $litellmUrl = "https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json"

    try {
        $raw = Invoke-RestMethod -Uri $litellmUrl -TimeoutSec 30
        $local = Get-Content $JsonPath -Raw | ConvertFrom-Json

        $addedCount = 0
        $updatedCount = 0

        foreach ($prop in $raw.PSObject.Properties) {
            $modelName = $prop.Name
            $data = $prop.Value

            # Skip entries without pricing
            $inputCost = $data.input_cost_per_token
            $outputCost = $data.output_cost_per_token
            if (-not $inputCost -and -not $outputCost) { continue }

            # Filter to known providers
            $provider = ""
            if ($data.PSObject.Properties["litellm_provider"]) {
                $provider = $data.litellm_provider
            }
            $validProviders = @("openai", "anthropic", "mistralai", "deepseek", "cohere", "text-completion-openai")
            $isValid = $false
            foreach ($vp in $validProviders) {
                if ($provider -like "*$vp*") { $isValid = $true; break }
            }
            if (-not $isValid) { continue }

            if (-not $inputCost) { $inputCost = 0 }
            if (-not $outputCost) { $outputCost = 0 }
            $inputPer1M = [math]::Round([double]$inputCost * 1000000, 4)
            $outputPer1M = [math]::Round([double]$outputCost * 1000000, 4)

            # Clean model name (remove provider prefix like "openai/")
            $cleanName = $modelName -replace "^[^/]+/", ""

            if (-not $local.models.PSObject.Properties[$cleanName]) {
                $local.models | Add-Member -NotePropertyName $cleanName -NotePropertyValue ([PSCustomObject]@{
                    inputPer1MTokens  = $inputPer1M
                    outputPer1MTokens = $outputPer1M
                })
                $addedCount++
            }
            else {
                $existing = $local.models.$cleanName
                if ($existing.inputPer1MTokens -ne $inputPer1M -or $existing.outputPer1MTokens -ne $outputPer1M) {
                    $existing.inputPer1MTokens = $inputPer1M
                    $existing.outputPer1MTokens = $outputPer1M
                    $updatedCount++
                }
            }
        }

        $local._updated = (Get-Date).ToString("yyyy-MM-dd")
        $local | ConvertTo-Json -Depth 10 | Set-Content $JsonPath -Encoding UTF8
        Write-Host "Merged: $addedCount added, $updatedCount updated"
    }
    catch {
        Write-Warning "Could not download LiteLLM pricing: $_"
        Write-Host "Continuing with existing local data..."
    }
}

# ── 2) Read local JSON ───────────────────────────────────────────────
$json = Get-Content $JsonPath -Raw | ConvertFrom-Json
$models = $json.models
$aliases = $json.aliases

# ── 3) Generate C# ──────────────────────────────────────────────────
$sb = New-Object System.Text.StringBuilder

[void]$sb.AppendLine("// <auto-generated/>")
[void]$sb.AppendLine("// Generated by scripts/update-model-pricing.ps1 on $((Get-Date).ToString('yyyy-MM-dd HH:mm:ss'))")
[void]$sb.AppendLine("// Source: src/GnOuGo.AI.Core/Telemetry/model-pricing.json")
[void]$sb.AppendLine("// DO NOT EDIT MANUALLY - run the script to regenerate.")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("using System.Collections.Frozen;")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("namespace GnOuGo.AI.Core.Telemetry;")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("public static partial class ModelPricingCatalog")
[void]$sb.AppendLine("{")
[void]$sb.AppendLine("    private static readonly FrozenDictionary<string, ModelPricing> Models = new Dictionary<string, ModelPricing>(StringComparer.OrdinalIgnoreCase)")
[void]$sb.AppendLine("    {")

$modelCount = 0
foreach ($prop in $models.PSObject.Properties) {
    $name = $prop.Name
    if ($name.StartsWith("_")) { continue }
    $inp = [decimal]$prop.Value.inputPer1MTokens
    $outp = [decimal]$prop.Value.outputPer1MTokens
    $inpStr = $inp.ToString([System.Globalization.CultureInfo]::InvariantCulture) + "m"
    $outpStr = $outp.ToString([System.Globalization.CultureInfo]::InvariantCulture) + "m"
    [void]$sb.AppendLine("        [`"$name`"] = new($inpStr, $outpStr),")
    $modelCount++
}

[void]$sb.AppendLine("    }.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase);")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("    private static readonly FrozenDictionary<string, string> Aliases = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)")
[void]$sb.AppendLine("    {")

$aliasCount = 0
if ($aliases) {
    foreach ($prop in $aliases.PSObject.Properties) {
        [void]$sb.AppendLine("        [`"$($prop.Name)`"] = `"$($prop.Value)`",")
        $aliasCount++
    }
}

[void]$sb.AppendLine("    }.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase);")
[void]$sb.AppendLine("}")

$content = $sb.ToString()
Set-Content $OutputPath -Value $content -Encoding UTF8
Write-Host "`nGenerated $OutputPath ($modelCount models, $aliasCount aliases)"
