using System.Text.Json.Nodes;
using Microsoft.Extensions.Logging;
using GnOuGo.Flow.Core.Expressions;
using GnOuGo.Flow.Core.Models;

namespace GnOuGo.Flow.Core.Runtime.Executors;

/// <summary>
/// Executes a workflow generated by workflow.plan.
/// </summary>
public sealed class WorkflowExecuteExecutor : IStepExecutor
{
    public StepRecovery Recovery => StepRecovery.Composite;
    public string StepType => "workflow.execute";

    public IReadOnlyList<StepExceptionDoc>? DocumentedExceptions => new StepExceptionDoc[]
    {
        new(ErrorCodes.InputValidation, false, "The `from_step` reference is missing, the planned YAML is missing/invalid, or no executable workflow entrypoint can be resolved."),
        new(ErrorCodes.WorkflowCycleDetected, false, "The runtime maximum call depth was exceeded while executing the planned workflow.")
    };

    public async Task<JsonNode?> ExecuteAsync(StepExecutionContext ctx, CancellationToken ct)
    {
        var input = ctx.Engine.GetResolvedInput(ctx) as JsonObject
            ?? throw new WorkflowRuntimeException(ErrorCodes.InputValidation, "workflow.execute input must be object");

        var fromStep = input["from_step"]?.GetValue<string>()
            ?? throw new WorkflowRuntimeException(ErrorCodes.InputValidation, "workflow.execute requires 'from_step'");

        // Get the planned workflow YAML from the referenced step
        var stepsObj = ctx.Data["steps"] as JsonObject;
        var planResult = stepsObj?[fromStep] as JsonObject
            ?? throw new WorkflowRuntimeException(ErrorCodes.InputValidation,
                $"No plan result found in step '{fromStep}'");

        var sessionId = planResult["session_id"]?.GetValue<string>();
        var hash = planResult["artifact_hash"]?.GetValue<string>();
        if (planResult["status"]?.GetValue<string>() != Planning.PlanningStatus.Approved ||
            string.IsNullOrWhiteSpace(sessionId) || string.IsNullOrWhiteSpace(hash) || ctx.Engine.PlanningRuntimeFactory is null)
            throw new WorkflowRuntimeException(ErrorCodes.InputValidation, "workflow.execute requires an approved planning session.");
        var yaml = await ctx.Engine.PlanningRuntimeFactory.ReadApprovedYamlAsync(ctx, sessionId, hash, ct);
        if (yaml != planResult["yaml"]?.GetValue<string>())
            throw new WorkflowRuntimeException(ErrorCodes.InputValidation, "The supplied YAML differs from the approved artifact.");

        var args = input["args"] ?? new JsonObject();

        // Parse and compile
        var doc = Parsing.WorkflowParser.Parse(yaml);
        var compiler = new Compilation.WorkflowCompiler();
        var compiledDoc = compiler.Compile(doc);

        // Find entrypoint
        var entrypoint = compiledDoc.Entrypoint ?? compiledDoc.Workflows.Keys.FirstOrDefault()
            ?? throw new WorkflowRuntimeException(ErrorCodes.InputValidation, "No workflow found in planned document");

        var workflow = compiledDoc.Workflows[entrypoint];

        // Execute in sandboxed context
        if (ctx.CallDepth >= ctx.Limits.MaxCallDepth)
        {
            ctx.Engine.Logger.LogError("workflow.execute: max call depth ({MaxCallDepth}) exceeded", ctx.Limits.MaxCallDepth);
            throw new WorkflowRuntimeException(ErrorCodes.WorkflowCycleDetected,
                $"Max call depth ({ctx.Limits.MaxCallDepth}) exceeded");
        }

        return await WorkflowCallExecutor.ExecuteResolvedWorkflow(ctx,
            new WorkflowCallResolution { Workflow = workflow, WorkflowName = entrypoint }, args, ct);
    }
}
