using System.Text.Json.Nodes;
using Microsoft.Extensions.Logging;
using GnOuGo.Flow.Core.Expressions;
using GnOuGo.Flow.Core.Models;

namespace GnOuGo.Flow.Core.Runtime.Executors;

/// <summary>
/// Executes a workflow generated by workflow.plan.
/// </summary>
public sealed class WorkflowExecuteExecutor : IStepExecutor
{
    public string StepType => "workflow.execute";

    public IReadOnlyList<StepExceptionDoc>? DocumentedExceptions => new StepExceptionDoc[]
    {
        new(ErrorCodes.InputValidation, false, "The `from_step` reference is missing, the planned YAML is missing/invalid, or no executable workflow entrypoint can be resolved."),
        new(ErrorCodes.WorkflowCycleDetected, false, "The runtime maximum call depth was exceeded while executing the planned workflow.")
    };

    public async Task<JsonNode?> ExecuteAsync(StepExecutionContext ctx, CancellationToken ct)
    {
        var input = ctx.Engine.GetResolvedInput(ctx) as JsonObject
            ?? throw new WorkflowRuntimeException(ErrorCodes.InputValidation, "workflow.execute input must be object");

        var fromStep = input["from_step"]?.GetValue<string>()
            ?? throw new WorkflowRuntimeException(ErrorCodes.InputValidation, "workflow.execute requires 'from_step'");

        // Get the planned workflow YAML from the referenced step
        var stepsObj = ctx.Data["steps"] as JsonObject;
        var planResult = stepsObj?[fromStep] as JsonObject
            ?? throw new WorkflowRuntimeException(ErrorCodes.InputValidation,
                $"No plan result found in step '{fromStep}'");

        var yaml = planResult["yaml"]?.GetValue<string>()
            ?? throw new WorkflowRuntimeException(ErrorCodes.InputValidation,
                $"No YAML found in plan result of step '{fromStep}'");

        var args = input["args"] ?? new JsonObject();

        // Parse and compile
        var doc = Parsing.WorkflowParser.Parse(yaml);
        var compiler = new Compilation.WorkflowCompiler();
        var compiledDoc = compiler.Compile(doc);

        // Find entrypoint
        var entrypoint = compiledDoc.Entrypoint ?? compiledDoc.Workflows.Keys.FirstOrDefault()
            ?? throw new WorkflowRuntimeException(ErrorCodes.InputValidation, "No workflow found in planned document");

        var workflow = compiledDoc.Workflows[entrypoint];

        // Execute in sandboxed context
        if (ctx.CallDepth >= ctx.Limits.MaxCallDepth)
        {
            ctx.Engine.Logger.LogError("workflow.execute: max call depth ({MaxCallDepth}) exceeded", ctx.Limits.MaxCallDepth);
            throw new WorkflowRuntimeException(ErrorCodes.WorkflowCycleDetected,
                $"Max call depth ({ctx.Limits.MaxCallDepth}) exceeded");
        }

        var subData = new JsonObject
        {
            ["inputs"] = args.DeepClone(),
            ["steps"] = new JsonObject(),
            ["env"] = ctx.Data["env"]?.DeepClone() ?? new JsonObject()
        };

        var result = new RunResult { Success = true };
        await ctx.Engine.ExecuteStepsAsync(workflow.Steps, subData, result, ctx.Limits, ctx.CallDepth + 1, ctx.CallStack, ct, ctx.TelemetrySpan);

        // Evaluate typed outputs if declared
        JsonNode? outputs;
        if (workflow.Outputs != null)
        {
            var outputObj = new JsonObject();
            foreach (var kv in workflow.Outputs)
            {
                outputObj[kv.Key] = ctx.Engine.EvaluateOutputDef(kv.Value, subData);
            }
            outputs = outputObj;
        }
        else
        {
            outputs = subData["steps"]?.DeepClone();
        }

        return new JsonObject
        {
            ["outputs"] = outputs,
            ["workflow"] = workflow.Name,
            ["run"] = new JsonObject
            {
                ["steps_executed"] = result.StepResults.Count,
                ["success"] = result.Success
            }
        };
    }
}
