// <auto-generated/>
// Generated by scripts/update-model-pricing.ps1 on 2026-03-16 19:49:18
// Source: src/GnOuGo.AI.Core/Telemetry/model-pricing.json
// DO NOT EDIT MANUALLY - run the script to regenerate.

using System.Collections.Frozen;

namespace GnOuGo.AI.Core.Telemetry;

public static partial class ModelPricingCatalog
{
    private static readonly FrozenDictionary<string, ModelPricing> Models = new Dictionary<string, ModelPricing>(StringComparer.OrdinalIgnoreCase)
    {
        ["text-embedding-3-large"] = new(0.13m, 0.0m),
        ["text-embedding-3-small"] = new(0.02m, 0.0m),
        ["text-embedding-ada-002"] = new(0.10m, 0.0m),
        ["gpt-4o"] = new(2.50m, 10.00m),
        ["gpt-4o-2024-11-20"] = new(2.50m, 10.00m),
        ["gpt-4o-mini"] = new(0.15m, 0.60m),
        ["gpt-4o-mini-2024-07-18"] = new(0.15m, 0.60m),
        ["gpt-4.1"] = new(2.00m, 8.00m),
        ["gpt-4.1-mini"] = new(0.40m, 1.60m),
        ["gpt-4.1-nano"] = new(0.10m, 0.40m),
        ["gpt-4-turbo"] = new(10.00m, 30.00m),
        ["gpt-3.5-turbo"] = new(0.50m, 1.50m),
        ["o1"] = new(15.00m, 60.00m),
        ["o1-mini"] = new(1.10m, 4.40m),
        ["o1-pro"] = new(150.00m, 600.00m),
        ["o3"] = new(2.00m, 8.00m),
        ["o3-mini"] = new(1.10m, 4.40m),
        ["o4-mini"] = new(1.10m, 4.40m),
        ["claude-3-5-sonnet-20241022"] = new(3.00m, 15.00m),
        ["claude-3-5-haiku-20241022"] = new(0.80m, 4.00m),
        ["claude-sonnet-4-20250514"] = new(3.00m, 15.00m),
        ["claude-haiku-4-20250514"] = new(0.80m, 4.00m),
        ["claude-3-7-sonnet-20250219"] = new(3.00m, 15.00m),
        ["mistral-large-latest"] = new(2.00m, 6.00m),
        ["mistral-small-latest"] = new(0.20m, 0.60m),
        ["mistral-embed"] = new(0.10m, 0.0m),
        ["deepseek-chat"] = new(0.14m, 0.28m),
        ["deepseek-reasoner"] = new(0.55m, 2.19m),
        ["gpt-5.4"] = new(75.00m, 150.00m),
    }.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase);

    private static readonly FrozenDictionary<string, string> Aliases = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        ["gpt4o"] = "gpt-4o",
        ["gpt4o-mini"] = "gpt-4o-mini",
        ["gpt-4-o"] = "gpt-4o",
        ["gpt-4-o-mini"] = "gpt-4o-mini",
        ["embedding-3-large"] = "text-embedding-3-large",
        ["embedding-3-small"] = "text-embedding-3-small",
        ["ada-002"] = "text-embedding-ada-002",
        ["text-embedding-ada"] = "text-embedding-ada-002",
        ["claude-3.5-sonnet"] = "claude-3-5-sonnet-20241022",
        ["claude-3.5-haiku"] = "claude-3-5-haiku-20241022",
        ["claude-3.7-sonnet"] = "claude-3-7-sonnet-20250219",
        ["claude-4-sonnet"] = "claude-sonnet-4-20250514",
        ["claude-4-haiku"] = "claude-haiku-4-20250514",
        ["gpt-4.5"] = "chatgpt-4.5-preview",
        ["gpt-5.4"] = "gpt-5.4",
    }.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase);
}

