// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using GnOuGo.KeyVault.Core.Models;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Json;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion.Internal;

#pragma warning disable 219, 612, 618
#nullable disable

namespace GnOuGo.KeyVault.Core.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class AuditEntryEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "GnOuGo.KeyVault.Core.Models.AuditEntry",
                typeof(AuditEntry),
                baseEntityType,
                propertyCount: 7,
                unnamedIndexCount: 2,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(AuditEntry).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AuditEntry).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.SetGetter(
                Guid (AuditEntry instance) => AuditEntryUnsafeAccessors.Id(instance),
                bool (AuditEntry instance) => AuditEntryUnsafeAccessors.Id(instance) == new Guid("00000000-0000-0000-0000-000000000000"));
            id.SetSetter(
                AuditEntry (AuditEntry instance, Guid value) =>
                {
                    AuditEntryUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                AuditEntry (AuditEntry instance, Guid value) =>
                {
                    AuditEntryUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                Guid (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<Guid>(0) : (entry.FlaggedAsTemporary(0) && AuditEntryUnsafeAccessors.Id(((AuditEntry)(entry.Entity))) == new Guid("00000000-0000-0000-0000-000000000000") ? entry.ReadTemporaryValue<Guid>(0) : AuditEntryUnsafeAccessors.Id(((AuditEntry)(entry.Entity))))),
                Guid (IInternalEntry entry) => AuditEntryUnsafeAccessors.Id(((AuditEntry)(entry.Entity))),
                Guid (IInternalEntry entry) => entry.ReadOriginalValue<Guid>(id, 0),
                Guid (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<Guid>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = SqliteGuidTypeMapping.Default;
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<Guid>(id));

            var author = runtimeEntityType.AddProperty(
                "Author",
                typeof(string),
                propertyInfo: typeof(AuditEntry).GetProperty("Author", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AuditEntry).GetField("<Author>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 256);
            author.SetGetter(
                string (AuditEntry instance) => AuditEntryUnsafeAccessors.Author(instance),
                bool (AuditEntry instance) => AuditEntryUnsafeAccessors.Author(instance) == null);
            author.SetSetter(
                AuditEntry (AuditEntry instance, string value) =>
                {
                    AuditEntryUnsafeAccessors.Author(instance) = value;
                    return instance;
                });
            author.SetMaterializationSetter(
                AuditEntry (AuditEntry instance, string value) =>
                {
                    AuditEntryUnsafeAccessors.Author(instance) = value;
                    return instance;
                });
            author.SetAccessors(
                string (IInternalEntry entry) => AuditEntryUnsafeAccessors.Author(((AuditEntry)(entry.Entity))),
                string (IInternalEntry entry) => AuditEntryUnsafeAccessors.Author(((AuditEntry)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(author, 1),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(author));
            author.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            author.TypeMapping = SqliteStringTypeMapping.Default;

            var details = runtimeEntityType.AddProperty(
                "Details",
                typeof(string),
                propertyInfo: typeof(AuditEntry).GetProperty("Details", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AuditEntry).GetField("<Details>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 2048);
            details.SetGetter(
                string (AuditEntry instance) => AuditEntryUnsafeAccessors.Details(instance),
                bool (AuditEntry instance) => AuditEntryUnsafeAccessors.Details(instance) == null);
            details.SetSetter(
                AuditEntry (AuditEntry instance, string value) =>
                {
                    AuditEntryUnsafeAccessors.Details(instance) = value;
                    return instance;
                });
            details.SetMaterializationSetter(
                AuditEntry (AuditEntry instance, string value) =>
                {
                    AuditEntryUnsafeAccessors.Details(instance) = value;
                    return instance;
                });
            details.SetAccessors(
                string (IInternalEntry entry) => AuditEntryUnsafeAccessors.Details(((AuditEntry)(entry.Entity))),
                string (IInternalEntry entry) => AuditEntryUnsafeAccessors.Details(((AuditEntry)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(details, 2),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(details));
            details.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            details.TypeMapping = SqliteStringTypeMapping.Default;

            var operation = runtimeEntityType.AddProperty(
                "Operation",
                typeof(AuditOperation),
                propertyInfo: typeof(AuditEntry).GetProperty("Operation", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AuditEntry).GetField("<Operation>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 64,
                providerPropertyType: typeof(string));
            operation.SetGetter(
                AuditOperation (AuditEntry instance) => AuditEntryUnsafeAccessors.Operation(instance),
                bool (AuditEntry instance) => object.Equals(((object)(AuditEntryUnsafeAccessors.Operation(instance))), ((object)(AuditOperation.CreateTenant))));
            operation.SetSetter(
                AuditEntry (AuditEntry instance, AuditOperation value) =>
                {
                    AuditEntryUnsafeAccessors.Operation(instance) = value;
                    return instance;
                });
            operation.SetMaterializationSetter(
                AuditEntry (AuditEntry instance, AuditOperation value) =>
                {
                    AuditEntryUnsafeAccessors.Operation(instance) = value;
                    return instance;
                });
            operation.SetAccessors(
                AuditOperation (IInternalEntry entry) => AuditEntryUnsafeAccessors.Operation(((AuditEntry)(entry.Entity))),
                AuditOperation (IInternalEntry entry) => AuditEntryUnsafeAccessors.Operation(((AuditEntry)(entry.Entity))),
                AuditOperation (IInternalEntry entry) => entry.ReadOriginalValue<AuditOperation>(operation, 3),
                AuditOperation (IInternalEntry entry) => entry.GetCurrentValue<AuditOperation>(operation));
            operation.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            operation.TypeMapping = SqliteStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<AuditOperation>(
                    bool (AuditOperation v1, AuditOperation v2) => object.Equals(((object)v1), ((object)v2)),
                    int (AuditOperation v) => ((object)v).GetHashCode(),
                    AuditOperation (AuditOperation v) => v),
                keyComparer: new ValueComparer<AuditOperation>(
                    bool (AuditOperation v1, AuditOperation v2) => object.Equals(((object)v1), ((object)v2)),
                    int (AuditOperation v) => ((object)v).GetHashCode(),
                    AuditOperation (AuditOperation v) => v),
                providerValueComparer: new ValueComparer<string>(
                    bool (string v1, string v2) => v1 == v2,
                    int (string v) => ((object)v).GetHashCode(),
                    string (string v) => v),
                converter: new ValueConverter<AuditOperation, string>(
                    string (AuditOperation v) => ((object)v).ToString(),
                    AuditOperation (string v) => StringEnumConverter<AuditOperation, string, AuditOperation>.ConvertToEnum(v)),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<AuditOperation, string>(
                    JsonStringReaderWriter.Instance,
                    new ValueConverter<AuditOperation, string>(
                        string (AuditOperation v) => ((object)v).ToString(),
                        AuditOperation (string v) => StringEnumConverter<AuditOperation, string, AuditOperation>.ConvertToEnum(v))));
            operation.SetSentinelFromProviderValue("CreateTenant");

            var secretKey = runtimeEntityType.AddProperty(
                "SecretKey",
                typeof(string),
                propertyInfo: typeof(AuditEntry).GetProperty("SecretKey", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AuditEntry).GetField("<SecretKey>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 512);
            secretKey.SetGetter(
                string (AuditEntry instance) => AuditEntryUnsafeAccessors.SecretKey(instance),
                bool (AuditEntry instance) => AuditEntryUnsafeAccessors.SecretKey(instance) == null);
            secretKey.SetSetter(
                AuditEntry (AuditEntry instance, string value) =>
                {
                    AuditEntryUnsafeAccessors.SecretKey(instance) = value;
                    return instance;
                });
            secretKey.SetMaterializationSetter(
                AuditEntry (AuditEntry instance, string value) =>
                {
                    AuditEntryUnsafeAccessors.SecretKey(instance) = value;
                    return instance;
                });
            secretKey.SetAccessors(
                string (IInternalEntry entry) => AuditEntryUnsafeAccessors.SecretKey(((AuditEntry)(entry.Entity))),
                string (IInternalEntry entry) => AuditEntryUnsafeAccessors.SecretKey(((AuditEntry)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(secretKey, 4),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(secretKey));
            secretKey.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            secretKey.TypeMapping = SqliteStringTypeMapping.Default;

            var tenantId = runtimeEntityType.AddProperty(
                "TenantId",
                typeof(Guid?),
                propertyInfo: typeof(AuditEntry).GetProperty("TenantId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AuditEntry).GetField("<TenantId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            tenantId.SetGetter(
                Guid? (AuditEntry instance) => AuditEntryUnsafeAccessors.TenantId(instance),
                bool (AuditEntry instance) => !(AuditEntryUnsafeAccessors.TenantId(instance).HasValue));
            tenantId.SetSetter(
                AuditEntry (AuditEntry instance, Guid? value) =>
                {
                    AuditEntryUnsafeAccessors.TenantId(instance) = value;
                    return instance;
                });
            tenantId.SetMaterializationSetter(
                AuditEntry (AuditEntry instance, Guid? value) =>
                {
                    AuditEntryUnsafeAccessors.TenantId(instance) = value;
                    return instance;
                });
            tenantId.SetAccessors(
                Guid? (IInternalEntry entry) => AuditEntryUnsafeAccessors.TenantId(((AuditEntry)(entry.Entity))),
                Guid? (IInternalEntry entry) => AuditEntryUnsafeAccessors.TenantId(((AuditEntry)(entry.Entity))),
                Guid? (IInternalEntry entry) => entry.ReadOriginalValue<Guid?>(tenantId, 5),
                Guid? (IInternalEntry entry) => entry.GetCurrentValue<Guid?>(tenantId));
            tenantId.SetPropertyIndexes(
                index: 5,
                originalValueIndex: 5,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            tenantId.TypeMapping = SqliteGuidTypeMapping.Default;
            tenantId.SetComparer(new NullableValueComparer<Guid>(tenantId.TypeMapping.Comparer));
            tenantId.SetKeyComparer(new NullableValueComparer<Guid>(tenantId.TypeMapping.KeyComparer));

            var timestampTicks = runtimeEntityType.AddProperty(
                "TimestampTicks",
                typeof(long),
                propertyInfo: typeof(AuditEntry).GetProperty("TimestampTicks", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AuditEntry).GetField("<TimestampTicks>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            timestampTicks.SetGetter(
                long (AuditEntry instance) => AuditEntryUnsafeAccessors.TimestampTicks(instance),
                bool (AuditEntry instance) => AuditEntryUnsafeAccessors.TimestampTicks(instance) == 0L);
            timestampTicks.SetSetter(
                AuditEntry (AuditEntry instance, long value) =>
                {
                    AuditEntryUnsafeAccessors.TimestampTicks(instance) = value;
                    return instance;
                });
            timestampTicks.SetMaterializationSetter(
                AuditEntry (AuditEntry instance, long value) =>
                {
                    AuditEntryUnsafeAccessors.TimestampTicks(instance) = value;
                    return instance;
                });
            timestampTicks.SetAccessors(
                long (IInternalEntry entry) => AuditEntryUnsafeAccessors.TimestampTicks(((AuditEntry)(entry.Entity))),
                long (IInternalEntry entry) => AuditEntryUnsafeAccessors.TimestampTicks(((AuditEntry)(entry.Entity))),
                long (IInternalEntry entry) => entry.ReadOriginalValue<long>(timestampTicks, 6),
                long (IInternalEntry entry) => entry.GetCurrentValue<long>(timestampTicks));
            timestampTicks.SetPropertyIndexes(
                index: 6,
                originalValueIndex: 6,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            timestampTicks.TypeMapping = LongTypeMapping.Default.Clone(
                comparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                keyComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                providerValueComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { timestampTicks });

            var index0 = runtimeEntityType.AddIndex(
                new[] { tenantId, timestampTicks });

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var author = runtimeEntityType.FindProperty("Author");
            var details = runtimeEntityType.FindProperty("Details");
            var operation = runtimeEntityType.FindProperty("Operation");
            var secretKey = runtimeEntityType.FindProperty("SecretKey");
            var tenantId = runtimeEntityType.FindProperty("TenantId");
            var timestampTicks = runtimeEntityType.FindProperty("TimestampTicks");
            var key = runtimeEntityType.FindKey(new[] { id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<Guid>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<Guid>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((AuditEntry)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid, string, string, AuditOperation, string, Guid?, long>(((ValueComparer<Guid>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid>(id)), (source.GetCurrentValue<string>(author) == null ? null : ((ValueComparer<string>)(((IProperty)author).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(author))), (source.GetCurrentValue<string>(details) == null ? null : ((ValueComparer<string>)(((IProperty)details).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(details))), ((ValueComparer<AuditOperation>)(((IProperty)operation).GetValueComparer())).Snapshot(source.GetCurrentValue<AuditOperation>(operation)), (source.GetCurrentValue<string>(secretKey) == null ? null : ((ValueComparer<string>)(((IProperty)secretKey).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(secretKey))), (source.GetCurrentValue<Guid?>(tenantId) == null ? null : ((ValueComparer<Guid?>)(((IProperty)tenantId).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid?>(tenantId))), ((ValueComparer<long>)(((IProperty)timestampTicks).GetValueComparer())).Snapshot(source.GetCurrentValue<long>(timestampTicks)))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<Guid>(((ValueComparer<Guid>)(((IProperty)id).GetValueComparer())).Snapshot(default(Guid))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<Guid>(default(Guid)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((AuditEntry)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid>(((ValueComparer<Guid>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<Guid>(id)))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 7,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 7,
                shadowCount: 0,
                relationshipCount: 1,
                storeGeneratedCount: 1));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "AuditEntries");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
