// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using GnOuGo.KeyVault.Core.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace GnOuGo.KeyVault.Core.Data.CompiledModels
{
    public static class AuditEntryUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref Guid Id(AuditEntry @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Author>k__BackingField")]
        public static extern ref string Author(AuditEntry @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Details>k__BackingField")]
        public static extern ref string Details(AuditEntry @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Operation>k__BackingField")]
        public static extern ref AuditOperation Operation(AuditEntry @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SecretKey>k__BackingField")]
        public static extern ref string SecretKey(AuditEntry @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TenantId>k__BackingField")]
        public static extern ref Guid? TenantId(AuditEntry @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TimestampTicks>k__BackingField")]
        public static extern ref long TimestampTicks(AuditEntry @this);
    }
}
