// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Update.Internal;

#pragma warning disable 219, 612, 618
#nullable disable

namespace GnOuGo.KeyVault.Core.Data.CompiledModels
{
    public partial class KeyVaultDbContextModel
    {
        private KeyVaultDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("2199d24f-6697-4768-baff-0b0ec5a9c073"), entityTypeCount: 4)
        {
        }

        partial void Initialize()
        {
            var auditEntry = AuditEntryEntityType.Create(this);
            var secret = SecretEntityType.Create(this);
            var secretVersion = SecretVersionEntityType.Create(this);
            var tenant = TenantEntityType.Create(this);

            SecretEntityType.CreateForeignKey1(secret, tenant);
            SecretVersionEntityType.CreateForeignKey1(secretVersion, secret);

            AuditEntryEntityType.CreateAnnotations(auditEntry);
            SecretEntityType.CreateAnnotations(secret);
            SecretVersionEntityType.CreateAnnotations(secretVersion);
            TenantEntityType.CreateAnnotations(tenant);

            AddAnnotation("ProductVersion", "10.0.8");
            AddRuntimeAnnotation("Relational:RelationalModelFactory", () => CreateRelationalModel());
        }

        private IRelationalModel CreateRelationalModel()
        {
            var relationalModel = new RelationalModel(this);

            var auditEntry = FindEntityType("GnOuGo.KeyVault.Core.Models.AuditEntry")!;

            var defaultTableMappings = new List<TableMappingBase<ColumnMappingBase>>();
            auditEntry.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings);
            var gnOuGoKeyVaultCoreModelsAuditEntryTableBase = new TableBase("GnOuGo.KeyVault.Core.Models.AuditEntry", null, relationalModel);
            var authorColumnBase = new ColumnBase<ColumnMappingBase>("Author", "TEXT", gnOuGoKeyVaultCoreModelsAuditEntryTableBase);
            gnOuGoKeyVaultCoreModelsAuditEntryTableBase.Columns.Add("Author", authorColumnBase);
            var detailsColumnBase = new ColumnBase<ColumnMappingBase>("Details", "TEXT", gnOuGoKeyVaultCoreModelsAuditEntryTableBase)
            {
                IsNullable = true
            };
            gnOuGoKeyVaultCoreModelsAuditEntryTableBase.Columns.Add("Details", detailsColumnBase);
            var idColumnBase = new ColumnBase<ColumnMappingBase>("Id", "TEXT", gnOuGoKeyVaultCoreModelsAuditEntryTableBase);
            gnOuGoKeyVaultCoreModelsAuditEntryTableBase.Columns.Add("Id", idColumnBase);
            var operationColumnBase = new ColumnBase<ColumnMappingBase>("Operation", "TEXT", gnOuGoKeyVaultCoreModelsAuditEntryTableBase);
            gnOuGoKeyVaultCoreModelsAuditEntryTableBase.Columns.Add("Operation", operationColumnBase);
            var secretKeyColumnBase = new ColumnBase<ColumnMappingBase>("SecretKey", "TEXT", gnOuGoKeyVaultCoreModelsAuditEntryTableBase)
            {
                IsNullable = true
            };
            gnOuGoKeyVaultCoreModelsAuditEntryTableBase.Columns.Add("SecretKey", secretKeyColumnBase);
            var tenantIdColumnBase = new ColumnBase<ColumnMappingBase>("TenantId", "TEXT", gnOuGoKeyVaultCoreModelsAuditEntryTableBase)
            {
                IsNullable = true
            };
            gnOuGoKeyVaultCoreModelsAuditEntryTableBase.Columns.Add("TenantId", tenantIdColumnBase);
            var timestampTicksColumnBase = new ColumnBase<ColumnMappingBase>("TimestampTicks", "INTEGER", gnOuGoKeyVaultCoreModelsAuditEntryTableBase);
            gnOuGoKeyVaultCoreModelsAuditEntryTableBase.Columns.Add("TimestampTicks", timestampTicksColumnBase);
            relationalModel.DefaultTables.Add("GnOuGo.KeyVault.Core.Models.AuditEntry", gnOuGoKeyVaultCoreModelsAuditEntryTableBase);
            var gnOuGoKeyVaultCoreModelsAuditEntryMappingBase = new TableMappingBase<ColumnMappingBase>(auditEntry, gnOuGoKeyVaultCoreModelsAuditEntryTableBase, null);
            gnOuGoKeyVaultCoreModelsAuditEntryTableBase.AddTypeMapping(gnOuGoKeyVaultCoreModelsAuditEntryMappingBase, false);
            defaultTableMappings.Add(gnOuGoKeyVaultCoreModelsAuditEntryMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase, auditEntry.FindProperty("Id")!, gnOuGoKeyVaultCoreModelsAuditEntryMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)authorColumnBase, auditEntry.FindProperty("Author")!, gnOuGoKeyVaultCoreModelsAuditEntryMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)detailsColumnBase, auditEntry.FindProperty("Details")!, gnOuGoKeyVaultCoreModelsAuditEntryMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)operationColumnBase, auditEntry.FindProperty("Operation")!, gnOuGoKeyVaultCoreModelsAuditEntryMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)secretKeyColumnBase, auditEntry.FindProperty("SecretKey")!, gnOuGoKeyVaultCoreModelsAuditEntryMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)tenantIdColumnBase, auditEntry.FindProperty("TenantId")!, gnOuGoKeyVaultCoreModelsAuditEntryMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)timestampTicksColumnBase, auditEntry.FindProperty("TimestampTicks")!, gnOuGoKeyVaultCoreModelsAuditEntryMappingBase);

            var tableMappings = new List<TableMapping>();
            auditEntry.SetRuntimeAnnotation("Relational:TableMappings", tableMappings);
            var auditEntriesTable = new Table("AuditEntries", null, relationalModel);
            var idColumn = new Column("Id", "TEXT", auditEntriesTable);
            auditEntriesTable.Columns.Add("Id", idColumn);
            idColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(idColumn);
            var authorColumn = new Column("Author", "TEXT", auditEntriesTable);
            auditEntriesTable.Columns.Add("Author", authorColumn);
            authorColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(authorColumn);
            var detailsColumn = new Column("Details", "TEXT", auditEntriesTable)
            {
                IsNullable = true
            };
            auditEntriesTable.Columns.Add("Details", detailsColumn);
            detailsColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(detailsColumn);
            var operationColumn = new Column("Operation", "TEXT", auditEntriesTable);
            auditEntriesTable.Columns.Add("Operation", operationColumn);
            operationColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(operationColumn);
            var secretKeyColumn = new Column("SecretKey", "TEXT", auditEntriesTable)
            {
                IsNullable = true
            };
            auditEntriesTable.Columns.Add("SecretKey", secretKeyColumn);
            secretKeyColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(secretKeyColumn);
            var tenantIdColumn = new Column("TenantId", "TEXT", auditEntriesTable)
            {
                IsNullable = true
            };
            auditEntriesTable.Columns.Add("TenantId", tenantIdColumn);
            tenantIdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(tenantIdColumn);
            var timestampTicksColumn = new Column("TimestampTicks", "INTEGER", auditEntriesTable);
            auditEntriesTable.Columns.Add("TimestampTicks", timestampTicksColumn);
            timestampTicksColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<long>(timestampTicksColumn);
            relationalModel.Tables.Add(("AuditEntries", null), auditEntriesTable);
            var auditEntriesTableMapping = new TableMapping(auditEntry, auditEntriesTable, null);
            auditEntriesTable.AddTypeMapping(auditEntriesTableMapping, false);
            tableMappings.Add(auditEntriesTableMapping);
            RelationalModel.CreateColumnMapping(idColumn, auditEntry.FindProperty("Id")!, auditEntriesTableMapping);
            RelationalModel.CreateColumnMapping(authorColumn, auditEntry.FindProperty("Author")!, auditEntriesTableMapping);
            RelationalModel.CreateColumnMapping(detailsColumn, auditEntry.FindProperty("Details")!, auditEntriesTableMapping);
            RelationalModel.CreateColumnMapping(operationColumn, auditEntry.FindProperty("Operation")!, auditEntriesTableMapping);
            RelationalModel.CreateColumnMapping(secretKeyColumn, auditEntry.FindProperty("SecretKey")!, auditEntriesTableMapping);
            RelationalModel.CreateColumnMapping(tenantIdColumn, auditEntry.FindProperty("TenantId")!, auditEntriesTableMapping);
            RelationalModel.CreateColumnMapping(timestampTicksColumn, auditEntry.FindProperty("TimestampTicks")!, auditEntriesTableMapping);
            var pK_AuditEntries = new UniqueConstraint("PK_AuditEntries", auditEntriesTable, new[] { idColumn });
            auditEntriesTable.PrimaryKey = pK_AuditEntries;
            pK_AuditEntries.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<Guid>(pK_AuditEntries));
            var pK_AuditEntriesKey = RelationalModel.GetKey(this,
                "GnOuGo.KeyVault.Core.Models.AuditEntry",
                new[] { "Id" });
            pK_AuditEntries.MappedKeys.Add(pK_AuditEntriesKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_AuditEntriesKey).Add(pK_AuditEntries);
            auditEntriesTable.UniqueConstraints.Add("PK_AuditEntries", pK_AuditEntries);
            var iX_AuditEntries_TenantId_TimestampTicks = new TableIndex(
            "IX_AuditEntries_TenantId_TimestampTicks", auditEntriesTable, new[] { tenantIdColumn, timestampTicksColumn }, false);
            iX_AuditEntries_TenantId_TimestampTicks.SetRowIndexValueFactory(new CompositeRowIndexValueFactory(iX_AuditEntries_TenantId_TimestampTicks));
            var iX_AuditEntries_TenantId_TimestampTicksIx = RelationalModel.GetIndex(this,
                "GnOuGo.KeyVault.Core.Models.AuditEntry",
                new[] { "TenantId", "TimestampTicks" });
            iX_AuditEntries_TenantId_TimestampTicks.MappedIndexes.Add(iX_AuditEntries_TenantId_TimestampTicksIx);
            RelationalModel.GetOrCreateTableIndexes(iX_AuditEntries_TenantId_TimestampTicksIx).Add(iX_AuditEntries_TenantId_TimestampTicks);
            auditEntriesTable.Indexes.Add("IX_AuditEntries_TenantId_TimestampTicks", iX_AuditEntries_TenantId_TimestampTicks);
            var iX_AuditEntries_TimestampTicks = new TableIndex(
            "IX_AuditEntries_TimestampTicks", auditEntriesTable, new[] { timestampTicksColumn }, false);
            iX_AuditEntries_TimestampTicks.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<long>(iX_AuditEntries_TimestampTicks));
            var iX_AuditEntries_TimestampTicksIx = RelationalModel.GetIndex(this,
                "GnOuGo.KeyVault.Core.Models.AuditEntry",
                new[] { "TimestampTicks" });
            iX_AuditEntries_TimestampTicks.MappedIndexes.Add(iX_AuditEntries_TimestampTicksIx);
            RelationalModel.GetOrCreateTableIndexes(iX_AuditEntries_TimestampTicksIx).Add(iX_AuditEntries_TimestampTicks);
            auditEntriesTable.Indexes.Add("IX_AuditEntries_TimestampTicks", iX_AuditEntries_TimestampTicks);

            var secret = FindEntityType("GnOuGo.KeyVault.Core.Models.Secret")!;

            var defaultTableMappings0 = new List<TableMappingBase<ColumnMappingBase>>();
            secret.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings0);
            var gnOuGoKeyVaultCoreModelsSecretTableBase = new TableBase("GnOuGo.KeyVault.Core.Models.Secret", null, relationalModel);
            var createdAtTicksColumnBase = new ColumnBase<ColumnMappingBase>("CreatedAtTicks", "INTEGER", gnOuGoKeyVaultCoreModelsSecretTableBase);
            gnOuGoKeyVaultCoreModelsSecretTableBase.Columns.Add("CreatedAtTicks", createdAtTicksColumnBase);
            var createdByColumnBase = new ColumnBase<ColumnMappingBase>("CreatedBy", "TEXT", gnOuGoKeyVaultCoreModelsSecretTableBase);
            gnOuGoKeyVaultCoreModelsSecretTableBase.Columns.Add("CreatedBy", createdByColumnBase);
            var idColumnBase0 = new ColumnBase<ColumnMappingBase>("Id", "TEXT", gnOuGoKeyVaultCoreModelsSecretTableBase);
            gnOuGoKeyVaultCoreModelsSecretTableBase.Columns.Add("Id", idColumnBase0);
            var isDeletedColumnBase = new ColumnBase<ColumnMappingBase>("IsDeleted", "INTEGER", gnOuGoKeyVaultCoreModelsSecretTableBase);
            gnOuGoKeyVaultCoreModelsSecretTableBase.Columns.Add("IsDeleted", isDeletedColumnBase);
            var keyColumnBase = new ColumnBase<ColumnMappingBase>("Key", "TEXT", gnOuGoKeyVaultCoreModelsSecretTableBase);
            gnOuGoKeyVaultCoreModelsSecretTableBase.Columns.Add("Key", keyColumnBase);
            var tenantIdColumnBase0 = new ColumnBase<ColumnMappingBase>("TenantId", "TEXT", gnOuGoKeyVaultCoreModelsSecretTableBase)
            {
                IsNullable = true
            };
            gnOuGoKeyVaultCoreModelsSecretTableBase.Columns.Add("TenantId", tenantIdColumnBase0);
            relationalModel.DefaultTables.Add("GnOuGo.KeyVault.Core.Models.Secret", gnOuGoKeyVaultCoreModelsSecretTableBase);
            var gnOuGoKeyVaultCoreModelsSecretMappingBase = new TableMappingBase<ColumnMappingBase>(secret, gnOuGoKeyVaultCoreModelsSecretTableBase, null);
            gnOuGoKeyVaultCoreModelsSecretTableBase.AddTypeMapping(gnOuGoKeyVaultCoreModelsSecretMappingBase, false);
            defaultTableMappings0.Add(gnOuGoKeyVaultCoreModelsSecretMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase0, secret.FindProperty("Id")!, gnOuGoKeyVaultCoreModelsSecretMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)createdAtTicksColumnBase, secret.FindProperty("CreatedAtTicks")!, gnOuGoKeyVaultCoreModelsSecretMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)createdByColumnBase, secret.FindProperty("CreatedBy")!, gnOuGoKeyVaultCoreModelsSecretMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)isDeletedColumnBase, secret.FindProperty("IsDeleted")!, gnOuGoKeyVaultCoreModelsSecretMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)keyColumnBase, secret.FindProperty("Key")!, gnOuGoKeyVaultCoreModelsSecretMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)tenantIdColumnBase0, secret.FindProperty("TenantId")!, gnOuGoKeyVaultCoreModelsSecretMappingBase);

            var tableMappings0 = new List<TableMapping>();
            secret.SetRuntimeAnnotation("Relational:TableMappings", tableMappings0);
            var secretsTable = new Table("Secrets", null, relationalModel);
            var idColumn0 = new Column("Id", "TEXT", secretsTable);
            secretsTable.Columns.Add("Id", idColumn0);
            idColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(idColumn0);
            var createdAtTicksColumn = new Column("CreatedAtTicks", "INTEGER", secretsTable);
            secretsTable.Columns.Add("CreatedAtTicks", createdAtTicksColumn);
            createdAtTicksColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<long>(createdAtTicksColumn);
            var createdByColumn = new Column("CreatedBy", "TEXT", secretsTable);
            secretsTable.Columns.Add("CreatedBy", createdByColumn);
            createdByColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(createdByColumn);
            var isDeletedColumn = new Column("IsDeleted", "INTEGER", secretsTable);
            secretsTable.Columns.Add("IsDeleted", isDeletedColumn);
            isDeletedColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<bool>(isDeletedColumn);
            var keyColumn = new Column("Key", "TEXT", secretsTable);
            secretsTable.Columns.Add("Key", keyColumn);
            keyColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(keyColumn);
            var tenantIdColumn0 = new Column("TenantId", "TEXT", secretsTable)
            {
                IsNullable = true
            };
            secretsTable.Columns.Add("TenantId", tenantIdColumn0);
            tenantIdColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(tenantIdColumn0);
            relationalModel.Tables.Add(("Secrets", null), secretsTable);
            var secretsTableMapping = new TableMapping(secret, secretsTable, null);
            secretsTable.AddTypeMapping(secretsTableMapping, false);
            tableMappings0.Add(secretsTableMapping);
            RelationalModel.CreateColumnMapping(idColumn0, secret.FindProperty("Id")!, secretsTableMapping);
            RelationalModel.CreateColumnMapping(createdAtTicksColumn, secret.FindProperty("CreatedAtTicks")!, secretsTableMapping);
            RelationalModel.CreateColumnMapping(createdByColumn, secret.FindProperty("CreatedBy")!, secretsTableMapping);
            RelationalModel.CreateColumnMapping(isDeletedColumn, secret.FindProperty("IsDeleted")!, secretsTableMapping);
            RelationalModel.CreateColumnMapping(keyColumn, secret.FindProperty("Key")!, secretsTableMapping);
            RelationalModel.CreateColumnMapping(tenantIdColumn0, secret.FindProperty("TenantId")!, secretsTableMapping);
            var pK_Secrets = new UniqueConstraint("PK_Secrets", secretsTable, new[] { idColumn0 });
            secretsTable.PrimaryKey = pK_Secrets;
            pK_Secrets.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<Guid>(pK_Secrets));
            var pK_SecretsKey = RelationalModel.GetKey(this,
                "GnOuGo.KeyVault.Core.Models.Secret",
                new[] { "Id" });
            pK_Secrets.MappedKeys.Add(pK_SecretsKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_SecretsKey).Add(pK_Secrets);
            secretsTable.UniqueConstraints.Add("PK_Secrets", pK_Secrets);
            var iX_Secrets_Key_TenantId = new TableIndex(
            "IX_Secrets_Key_TenantId", secretsTable, new[] { keyColumn, tenantIdColumn0 }, true);
            iX_Secrets_Key_TenantId.SetRowIndexValueFactory(new CompositeRowIndexValueFactory(iX_Secrets_Key_TenantId));
            var iX_Secrets_Key_TenantIdIx = RelationalModel.GetIndex(this,
                "GnOuGo.KeyVault.Core.Models.Secret",
                new[] { "Key", "TenantId" });
            iX_Secrets_Key_TenantId.MappedIndexes.Add(iX_Secrets_Key_TenantIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Secrets_Key_TenantIdIx).Add(iX_Secrets_Key_TenantId);
            secretsTable.Indexes.Add("IX_Secrets_Key_TenantId", iX_Secrets_Key_TenantId);
            var iX_Secrets_TenantId = new TableIndex(
            "IX_Secrets_TenantId", secretsTable, new[] { tenantIdColumn0 }, false);
            iX_Secrets_TenantId.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<Guid>(iX_Secrets_TenantId));
            var iX_Secrets_TenantIdIx = RelationalModel.GetIndex(this,
                "GnOuGo.KeyVault.Core.Models.Secret",
                new[] { "TenantId" });
            iX_Secrets_TenantId.MappedIndexes.Add(iX_Secrets_TenantIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Secrets_TenantIdIx).Add(iX_Secrets_TenantId);
            secretsTable.Indexes.Add("IX_Secrets_TenantId", iX_Secrets_TenantId);

            var secretVersion = FindEntityType("GnOuGo.KeyVault.Core.Models.SecretVersion")!;

            var defaultTableMappings1 = new List<TableMappingBase<ColumnMappingBase>>();
            secretVersion.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings1);
            var gnOuGoKeyVaultCoreModelsSecretVersionTableBase = new TableBase("GnOuGo.KeyVault.Core.Models.SecretVersion", null, relationalModel);
            var createdAtTicksColumnBase0 = new ColumnBase<ColumnMappingBase>("CreatedAtTicks", "INTEGER", gnOuGoKeyVaultCoreModelsSecretVersionTableBase);
            gnOuGoKeyVaultCoreModelsSecretVersionTableBase.Columns.Add("CreatedAtTicks", createdAtTicksColumnBase0);
            var createdByColumnBase0 = new ColumnBase<ColumnMappingBase>("CreatedBy", "TEXT", gnOuGoKeyVaultCoreModelsSecretVersionTableBase);
            gnOuGoKeyVaultCoreModelsSecretVersionTableBase.Columns.Add("CreatedBy", createdByColumnBase0);
            var encryptedValueColumnBase = new ColumnBase<ColumnMappingBase>("EncryptedValue", "TEXT", gnOuGoKeyVaultCoreModelsSecretVersionTableBase);
            gnOuGoKeyVaultCoreModelsSecretVersionTableBase.Columns.Add("EncryptedValue", encryptedValueColumnBase);
            var idColumnBase1 = new ColumnBase<ColumnMappingBase>("Id", "TEXT", gnOuGoKeyVaultCoreModelsSecretVersionTableBase);
            gnOuGoKeyVaultCoreModelsSecretVersionTableBase.Columns.Add("Id", idColumnBase1);
            var secretIdColumnBase = new ColumnBase<ColumnMappingBase>("SecretId", "TEXT", gnOuGoKeyVaultCoreModelsSecretVersionTableBase);
            gnOuGoKeyVaultCoreModelsSecretVersionTableBase.Columns.Add("SecretId", secretIdColumnBase);
            var versionColumnBase = new ColumnBase<ColumnMappingBase>("Version", "INTEGER", gnOuGoKeyVaultCoreModelsSecretVersionTableBase);
            gnOuGoKeyVaultCoreModelsSecretVersionTableBase.Columns.Add("Version", versionColumnBase);
            relationalModel.DefaultTables.Add("GnOuGo.KeyVault.Core.Models.SecretVersion", gnOuGoKeyVaultCoreModelsSecretVersionTableBase);
            var gnOuGoKeyVaultCoreModelsSecretVersionMappingBase = new TableMappingBase<ColumnMappingBase>(secretVersion, gnOuGoKeyVaultCoreModelsSecretVersionTableBase, null);
            gnOuGoKeyVaultCoreModelsSecretVersionTableBase.AddTypeMapping(gnOuGoKeyVaultCoreModelsSecretVersionMappingBase, false);
            defaultTableMappings1.Add(gnOuGoKeyVaultCoreModelsSecretVersionMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase1, secretVersion.FindProperty("Id")!, gnOuGoKeyVaultCoreModelsSecretVersionMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)createdAtTicksColumnBase0, secretVersion.FindProperty("CreatedAtTicks")!, gnOuGoKeyVaultCoreModelsSecretVersionMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)createdByColumnBase0, secretVersion.FindProperty("CreatedBy")!, gnOuGoKeyVaultCoreModelsSecretVersionMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)encryptedValueColumnBase, secretVersion.FindProperty("EncryptedValue")!, gnOuGoKeyVaultCoreModelsSecretVersionMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)secretIdColumnBase, secretVersion.FindProperty("SecretId")!, gnOuGoKeyVaultCoreModelsSecretVersionMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)versionColumnBase, secretVersion.FindProperty("Version")!, gnOuGoKeyVaultCoreModelsSecretVersionMappingBase);

            var tableMappings1 = new List<TableMapping>();
            secretVersion.SetRuntimeAnnotation("Relational:TableMappings", tableMappings1);
            var secretVersionsTable = new Table("SecretVersions", null, relationalModel);
            var idColumn1 = new Column("Id", "TEXT", secretVersionsTable);
            secretVersionsTable.Columns.Add("Id", idColumn1);
            idColumn1.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(idColumn1);
            var createdAtTicksColumn0 = new Column("CreatedAtTicks", "INTEGER", secretVersionsTable);
            secretVersionsTable.Columns.Add("CreatedAtTicks", createdAtTicksColumn0);
            createdAtTicksColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<long>(createdAtTicksColumn0);
            var createdByColumn0 = new Column("CreatedBy", "TEXT", secretVersionsTable);
            secretVersionsTable.Columns.Add("CreatedBy", createdByColumn0);
            createdByColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(createdByColumn0);
            var encryptedValueColumn = new Column("EncryptedValue", "TEXT", secretVersionsTable);
            secretVersionsTable.Columns.Add("EncryptedValue", encryptedValueColumn);
            encryptedValueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(encryptedValueColumn);
            var secretIdColumn = new Column("SecretId", "TEXT", secretVersionsTable);
            secretVersionsTable.Columns.Add("SecretId", secretIdColumn);
            secretIdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(secretIdColumn);
            var versionColumn = new Column("Version", "INTEGER", secretVersionsTable);
            secretVersionsTable.Columns.Add("Version", versionColumn);
            versionColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(versionColumn);
            relationalModel.Tables.Add(("SecretVersions", null), secretVersionsTable);
            var secretVersionsTableMapping = new TableMapping(secretVersion, secretVersionsTable, null);
            secretVersionsTable.AddTypeMapping(secretVersionsTableMapping, false);
            tableMappings1.Add(secretVersionsTableMapping);
            RelationalModel.CreateColumnMapping(idColumn1, secretVersion.FindProperty("Id")!, secretVersionsTableMapping);
            RelationalModel.CreateColumnMapping(createdAtTicksColumn0, secretVersion.FindProperty("CreatedAtTicks")!, secretVersionsTableMapping);
            RelationalModel.CreateColumnMapping(createdByColumn0, secretVersion.FindProperty("CreatedBy")!, secretVersionsTableMapping);
            RelationalModel.CreateColumnMapping(encryptedValueColumn, secretVersion.FindProperty("EncryptedValue")!, secretVersionsTableMapping);
            RelationalModel.CreateColumnMapping(secretIdColumn, secretVersion.FindProperty("SecretId")!, secretVersionsTableMapping);
            RelationalModel.CreateColumnMapping(versionColumn, secretVersion.FindProperty("Version")!, secretVersionsTableMapping);
            var pK_SecretVersions = new UniqueConstraint("PK_SecretVersions", secretVersionsTable, new[] { idColumn1 });
            secretVersionsTable.PrimaryKey = pK_SecretVersions;
            pK_SecretVersions.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<Guid>(pK_SecretVersions));
            var pK_SecretVersionsKey = RelationalModel.GetKey(this,
                "GnOuGo.KeyVault.Core.Models.SecretVersion",
                new[] { "Id" });
            pK_SecretVersions.MappedKeys.Add(pK_SecretVersionsKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_SecretVersionsKey).Add(pK_SecretVersions);
            secretVersionsTable.UniqueConstraints.Add("PK_SecretVersions", pK_SecretVersions);
            var iX_SecretVersions_SecretId_Version = new TableIndex(
            "IX_SecretVersions_SecretId_Version", secretVersionsTable, new[] { secretIdColumn, versionColumn }, true);
            iX_SecretVersions_SecretId_Version.SetRowIndexValueFactory(new CompositeRowIndexValueFactory(iX_SecretVersions_SecretId_Version));
            var iX_SecretVersions_SecretId_VersionIx = RelationalModel.GetIndex(this,
                "GnOuGo.KeyVault.Core.Models.SecretVersion",
                new[] { "SecretId", "Version" });
            iX_SecretVersions_SecretId_Version.MappedIndexes.Add(iX_SecretVersions_SecretId_VersionIx);
            RelationalModel.GetOrCreateTableIndexes(iX_SecretVersions_SecretId_VersionIx).Add(iX_SecretVersions_SecretId_Version);
            secretVersionsTable.Indexes.Add("IX_SecretVersions_SecretId_Version", iX_SecretVersions_SecretId_Version);

            var tenant = FindEntityType("GnOuGo.KeyVault.Core.Models.Tenant")!;

            var defaultTableMappings2 = new List<TableMappingBase<ColumnMappingBase>>();
            tenant.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings2);
            var gnOuGoKeyVaultCoreModelsTenantTableBase = new TableBase("GnOuGo.KeyVault.Core.Models.Tenant", null, relationalModel);
            var createdAtTicksColumnBase1 = new ColumnBase<ColumnMappingBase>("CreatedAtTicks", "INTEGER", gnOuGoKeyVaultCoreModelsTenantTableBase);
            gnOuGoKeyVaultCoreModelsTenantTableBase.Columns.Add("CreatedAtTicks", createdAtTicksColumnBase1);
            var createdByColumnBase1 = new ColumnBase<ColumnMappingBase>("CreatedBy", "TEXT", gnOuGoKeyVaultCoreModelsTenantTableBase);
            gnOuGoKeyVaultCoreModelsTenantTableBase.Columns.Add("CreatedBy", createdByColumnBase1);
            var idColumnBase2 = new ColumnBase<ColumnMappingBase>("Id", "TEXT", gnOuGoKeyVaultCoreModelsTenantTableBase);
            gnOuGoKeyVaultCoreModelsTenantTableBase.Columns.Add("Id", idColumnBase2);
            var isDeletedColumnBase0 = new ColumnBase<ColumnMappingBase>("IsDeleted", "INTEGER", gnOuGoKeyVaultCoreModelsTenantTableBase);
            gnOuGoKeyVaultCoreModelsTenantTableBase.Columns.Add("IsDeleted", isDeletedColumnBase0);
            var nameColumnBase = new ColumnBase<ColumnMappingBase>("Name", "TEXT", gnOuGoKeyVaultCoreModelsTenantTableBase);
            gnOuGoKeyVaultCoreModelsTenantTableBase.Columns.Add("Name", nameColumnBase);
            var privateKeyPemColumnBase = new ColumnBase<ColumnMappingBase>("PrivateKeyPem", "TEXT", gnOuGoKeyVaultCoreModelsTenantTableBase);
            gnOuGoKeyVaultCoreModelsTenantTableBase.Columns.Add("PrivateKeyPem", privateKeyPemColumnBase);
            var publicKeyPemColumnBase = new ColumnBase<ColumnMappingBase>("PublicKeyPem", "TEXT", gnOuGoKeyVaultCoreModelsTenantTableBase);
            gnOuGoKeyVaultCoreModelsTenantTableBase.Columns.Add("PublicKeyPem", publicKeyPemColumnBase);
            relationalModel.DefaultTables.Add("GnOuGo.KeyVault.Core.Models.Tenant", gnOuGoKeyVaultCoreModelsTenantTableBase);
            var gnOuGoKeyVaultCoreModelsTenantMappingBase = new TableMappingBase<ColumnMappingBase>(tenant, gnOuGoKeyVaultCoreModelsTenantTableBase, null);
            gnOuGoKeyVaultCoreModelsTenantTableBase.AddTypeMapping(gnOuGoKeyVaultCoreModelsTenantMappingBase, false);
            defaultTableMappings2.Add(gnOuGoKeyVaultCoreModelsTenantMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase2, tenant.FindProperty("Id")!, gnOuGoKeyVaultCoreModelsTenantMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)createdAtTicksColumnBase1, tenant.FindProperty("CreatedAtTicks")!, gnOuGoKeyVaultCoreModelsTenantMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)createdByColumnBase1, tenant.FindProperty("CreatedBy")!, gnOuGoKeyVaultCoreModelsTenantMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)isDeletedColumnBase0, tenant.FindProperty("IsDeleted")!, gnOuGoKeyVaultCoreModelsTenantMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nameColumnBase, tenant.FindProperty("Name")!, gnOuGoKeyVaultCoreModelsTenantMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)privateKeyPemColumnBase, tenant.FindProperty("PrivateKeyPem")!, gnOuGoKeyVaultCoreModelsTenantMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)publicKeyPemColumnBase, tenant.FindProperty("PublicKeyPem")!, gnOuGoKeyVaultCoreModelsTenantMappingBase);

            var tableMappings2 = new List<TableMapping>();
            tenant.SetRuntimeAnnotation("Relational:TableMappings", tableMappings2);
            var tenantsTable = new Table("Tenants", null, relationalModel);
            var idColumn2 = new Column("Id", "TEXT", tenantsTable);
            tenantsTable.Columns.Add("Id", idColumn2);
            idColumn2.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(idColumn2);
            var createdAtTicksColumn1 = new Column("CreatedAtTicks", "INTEGER", tenantsTable);
            tenantsTable.Columns.Add("CreatedAtTicks", createdAtTicksColumn1);
            createdAtTicksColumn1.Accessors = ColumnAccessorsFactory.CreateGeneric<long>(createdAtTicksColumn1);
            var createdByColumn1 = new Column("CreatedBy", "TEXT", tenantsTable);
            tenantsTable.Columns.Add("CreatedBy", createdByColumn1);
            createdByColumn1.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(createdByColumn1);
            var isDeletedColumn0 = new Column("IsDeleted", "INTEGER", tenantsTable);
            tenantsTable.Columns.Add("IsDeleted", isDeletedColumn0);
            isDeletedColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<bool>(isDeletedColumn0);
            var nameColumn = new Column("Name", "TEXT", tenantsTable);
            tenantsTable.Columns.Add("Name", nameColumn);
            nameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(nameColumn);
            var privateKeyPemColumn = new Column("PrivateKeyPem", "TEXT", tenantsTable);
            tenantsTable.Columns.Add("PrivateKeyPem", privateKeyPemColumn);
            privateKeyPemColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(privateKeyPemColumn);
            var publicKeyPemColumn = new Column("PublicKeyPem", "TEXT", tenantsTable);
            tenantsTable.Columns.Add("PublicKeyPem", publicKeyPemColumn);
            publicKeyPemColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(publicKeyPemColumn);
            relationalModel.Tables.Add(("Tenants", null), tenantsTable);
            var tenantsTableMapping = new TableMapping(tenant, tenantsTable, null);
            tenantsTable.AddTypeMapping(tenantsTableMapping, false);
            tableMappings2.Add(tenantsTableMapping);
            RelationalModel.CreateColumnMapping(idColumn2, tenant.FindProperty("Id")!, tenantsTableMapping);
            RelationalModel.CreateColumnMapping(createdAtTicksColumn1, tenant.FindProperty("CreatedAtTicks")!, tenantsTableMapping);
            RelationalModel.CreateColumnMapping(createdByColumn1, tenant.FindProperty("CreatedBy")!, tenantsTableMapping);
            RelationalModel.CreateColumnMapping(isDeletedColumn0, tenant.FindProperty("IsDeleted")!, tenantsTableMapping);
            RelationalModel.CreateColumnMapping(nameColumn, tenant.FindProperty("Name")!, tenantsTableMapping);
            RelationalModel.CreateColumnMapping(privateKeyPemColumn, tenant.FindProperty("PrivateKeyPem")!, tenantsTableMapping);
            RelationalModel.CreateColumnMapping(publicKeyPemColumn, tenant.FindProperty("PublicKeyPem")!, tenantsTableMapping);
            var pK_Tenants = new UniqueConstraint("PK_Tenants", tenantsTable, new[] { idColumn2 });
            tenantsTable.PrimaryKey = pK_Tenants;
            pK_Tenants.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<Guid>(pK_Tenants));
            var pK_TenantsKey = RelationalModel.GetKey(this,
                "GnOuGo.KeyVault.Core.Models.Tenant",
                new[] { "Id" });
            pK_Tenants.MappedKeys.Add(pK_TenantsKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_TenantsKey).Add(pK_Tenants);
            tenantsTable.UniqueConstraints.Add("PK_Tenants", pK_Tenants);
            var iX_Tenants_Name = new TableIndex(
            "IX_Tenants_Name", tenantsTable, new[] { nameColumn }, true);
            iX_Tenants_Name.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<string>(iX_Tenants_Name));
            var iX_Tenants_NameIx = RelationalModel.GetIndex(this,
                "GnOuGo.KeyVault.Core.Models.Tenant",
                new[] { "Name" });
            iX_Tenants_Name.MappedIndexes.Add(iX_Tenants_NameIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Tenants_NameIx).Add(iX_Tenants_Name);
            tenantsTable.Indexes.Add("IX_Tenants_Name", iX_Tenants_Name);
            var fK_Secrets_Tenants_TenantId = new ForeignKeyConstraint(
                "FK_Secrets_Tenants_TenantId", secretsTable, tenantsTable,
                new[] { tenantIdColumn0 },
                tenantsTable.FindUniqueConstraint("PK_Tenants")!, ReferentialAction.SetNull);
            fK_Secrets_Tenants_TenantId.SetRowForeignKeyValueFactory(RowForeignKeyValueFactoryFactory.CreateSimpleNonNullableFactory<Guid, Guid>(fK_Secrets_Tenants_TenantId));
            var fK_Secrets_Tenants_TenantIdFk = RelationalModel.GetForeignKey(this,
                "GnOuGo.KeyVault.Core.Models.Secret",
                new[] { "TenantId" },
                "GnOuGo.KeyVault.Core.Models.Tenant",
                new[] { "Id" });
            fK_Secrets_Tenants_TenantId.MappedForeignKeys.Add(fK_Secrets_Tenants_TenantIdFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_Secrets_Tenants_TenantIdFk).Add(fK_Secrets_Tenants_TenantId);
            secretsTable.ForeignKeyConstraints.Add(fK_Secrets_Tenants_TenantId);
            tenantsTable.ReferencingForeignKeyConstraints.Add(fK_Secrets_Tenants_TenantId);
            var fK_SecretVersions_Secrets_SecretId = new ForeignKeyConstraint(
                "FK_SecretVersions_Secrets_SecretId", secretVersionsTable, secretsTable,
                new[] { secretIdColumn },
                secretsTable.FindUniqueConstraint("PK_Secrets")!, ReferentialAction.Cascade);
            fK_SecretVersions_Secrets_SecretId.SetRowForeignKeyValueFactory(RowForeignKeyValueFactoryFactory.CreateSimpleNonNullableFactory<Guid, Guid>(fK_SecretVersions_Secrets_SecretId));
            var fK_SecretVersions_Secrets_SecretIdFk = RelationalModel.GetForeignKey(this,
                "GnOuGo.KeyVault.Core.Models.SecretVersion",
                new[] { "SecretId" },
                "GnOuGo.KeyVault.Core.Models.Secret",
                new[] { "Id" });
            fK_SecretVersions_Secrets_SecretId.MappedForeignKeys.Add(fK_SecretVersions_Secrets_SecretIdFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_SecretVersions_Secrets_SecretIdFk).Add(fK_SecretVersions_Secrets_SecretId);
            secretVersionsTable.ForeignKeyConstraints.Add(fK_SecretVersions_Secrets_SecretId);
            secretsTable.ReferencingForeignKeyConstraints.Add(fK_SecretVersions_Secrets_SecretId);
            return relationalModel.MakeReadOnly();
        }
    }
}
