// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace GnOuGo.KeyVault.Core.Data.CompiledModels
{
    public partial class KeyVaultDbContextModel
    {
        private KeyVaultDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("c8762ca4-be0f-439b-bcd5-b2333fb86f60"), entityTypeCount: 4)
        {
        }

        partial void Initialize()
        {
            var auditEntry = AuditEntryEntityType.Create(this);
            var secret = SecretEntityType.Create(this);
            var secretVersion = SecretVersionEntityType.Create(this);
            var tenant = TenantEntityType.Create(this);

            SecretEntityType.CreateForeignKey1(secret, tenant);
            SecretVersionEntityType.CreateForeignKey1(secretVersion, secret);

            AuditEntryEntityType.CreateAnnotations(auditEntry);
            SecretEntityType.CreateAnnotations(secret);
            SecretVersionEntityType.CreateAnnotations(secretVersion);
            TenantEntityType.CreateAnnotations(tenant);

            AddAnnotation("ProductVersion", "10.0.11");
        }
    }
}
