// <auto-generated />
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using GnOuGo.KeyVault.Core.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace GnOuGo.KeyVault.Core.Data.CompiledModels
{
    public static class SecretUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref Guid Id(Secret @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAtTicks>k__BackingField")]
        public static extern ref long CreatedAtTicks(Secret @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedBy>k__BackingField")]
        public static extern ref string CreatedBy(Secret @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsDeleted>k__BackingField")]
        public static extern ref bool IsDeleted(Secret @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Key>k__BackingField")]
        public static extern ref string Key(Secret @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TenantId>k__BackingField")]
        public static extern ref Guid? TenantId(Secret @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Tenant>k__BackingField")]
        public static extern ref Tenant Tenant(Secret @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Versions>k__BackingField")]
        public static extern ref ICollection<SecretVersion> Versions(Secret @this);
    }
}
