// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using GnOuGo.KeyVault.Core.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;

#pragma warning disable 219, 612, 618
#nullable disable

namespace GnOuGo.KeyVault.Core.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class SecretEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "GnOuGo.KeyVault.Core.Models.Secret",
                typeof(Secret),
                baseEntityType,
                propertyCount: 6,
                navigationCount: 2,
                foreignKeyCount: 1,
                unnamedIndexCount: 2,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(Secret).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Secret).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.SetGetter(
                Guid (Secret instance) => SecretUnsafeAccessors.Id(instance),
                bool (Secret instance) => SecretUnsafeAccessors.Id(instance) == new Guid("00000000-0000-0000-0000-000000000000"));
            id.SetSetter(
                Secret (Secret instance, Guid value) =>
                {
                    SecretUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                Secret (Secret instance, Guid value) =>
                {
                    SecretUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                Guid (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<Guid>(0) : (entry.FlaggedAsTemporary(0) && SecretUnsafeAccessors.Id(((Secret)(entry.Entity))) == new Guid("00000000-0000-0000-0000-000000000000") ? entry.ReadTemporaryValue<Guid>(0) : SecretUnsafeAccessors.Id(((Secret)(entry.Entity))))),
                Guid (IInternalEntry entry) => SecretUnsafeAccessors.Id(((Secret)(entry.Entity))),
                Guid (IInternalEntry entry) => entry.ReadOriginalValue<Guid>(id, 0),
                Guid (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<Guid>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = SqliteGuidTypeMapping.Default;
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<Guid>(id));

            var createdAtTicks = runtimeEntityType.AddProperty(
                "CreatedAtTicks",
                typeof(long),
                propertyInfo: typeof(Secret).GetProperty("CreatedAtTicks", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Secret).GetField("<CreatedAtTicks>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            createdAtTicks.SetGetter(
                long (Secret instance) => SecretUnsafeAccessors.CreatedAtTicks(instance),
                bool (Secret instance) => SecretUnsafeAccessors.CreatedAtTicks(instance) == 0L);
            createdAtTicks.SetSetter(
                Secret (Secret instance, long value) =>
                {
                    SecretUnsafeAccessors.CreatedAtTicks(instance) = value;
                    return instance;
                });
            createdAtTicks.SetMaterializationSetter(
                Secret (Secret instance, long value) =>
                {
                    SecretUnsafeAccessors.CreatedAtTicks(instance) = value;
                    return instance;
                });
            createdAtTicks.SetAccessors(
                long (IInternalEntry entry) => SecretUnsafeAccessors.CreatedAtTicks(((Secret)(entry.Entity))),
                long (IInternalEntry entry) => SecretUnsafeAccessors.CreatedAtTicks(((Secret)(entry.Entity))),
                long (IInternalEntry entry) => entry.ReadOriginalValue<long>(createdAtTicks, 1),
                long (IInternalEntry entry) => entry.GetCurrentValue<long>(createdAtTicks));
            createdAtTicks.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            createdAtTicks.TypeMapping = LongTypeMapping.Default.Clone(
                comparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                keyComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                providerValueComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var createdBy = runtimeEntityType.AddProperty(
                "CreatedBy",
                typeof(string),
                propertyInfo: typeof(Secret).GetProperty("CreatedBy", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Secret).GetField("<CreatedBy>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 256);
            createdBy.SetGetter(
                string (Secret instance) => SecretUnsafeAccessors.CreatedBy(instance),
                bool (Secret instance) => SecretUnsafeAccessors.CreatedBy(instance) == null);
            createdBy.SetSetter(
                Secret (Secret instance, string value) =>
                {
                    SecretUnsafeAccessors.CreatedBy(instance) = value;
                    return instance;
                });
            createdBy.SetMaterializationSetter(
                Secret (Secret instance, string value) =>
                {
                    SecretUnsafeAccessors.CreatedBy(instance) = value;
                    return instance;
                });
            createdBy.SetAccessors(
                string (IInternalEntry entry) => SecretUnsafeAccessors.CreatedBy(((Secret)(entry.Entity))),
                string (IInternalEntry entry) => SecretUnsafeAccessors.CreatedBy(((Secret)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(createdBy, 2),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(createdBy));
            createdBy.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            createdBy.TypeMapping = SqliteStringTypeMapping.Default;

            var isDeleted = runtimeEntityType.AddProperty(
                "IsDeleted",
                typeof(bool),
                propertyInfo: typeof(Secret).GetProperty("IsDeleted", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Secret).GetField("<IsDeleted>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            isDeleted.SetGetter(
                bool (Secret instance) => SecretUnsafeAccessors.IsDeleted(instance),
                bool (Secret instance) => SecretUnsafeAccessors.IsDeleted(instance) == false);
            isDeleted.SetSetter(
                Secret (Secret instance, bool value) =>
                {
                    SecretUnsafeAccessors.IsDeleted(instance) = value;
                    return instance;
                });
            isDeleted.SetMaterializationSetter(
                Secret (Secret instance, bool value) =>
                {
                    SecretUnsafeAccessors.IsDeleted(instance) = value;
                    return instance;
                });
            isDeleted.SetAccessors(
                bool (IInternalEntry entry) => SecretUnsafeAccessors.IsDeleted(((Secret)(entry.Entity))),
                bool (IInternalEntry entry) => SecretUnsafeAccessors.IsDeleted(((Secret)(entry.Entity))),
                bool (IInternalEntry entry) => entry.ReadOriginalValue<bool>(isDeleted, 3),
                bool (IInternalEntry entry) => entry.GetCurrentValue<bool>(isDeleted));
            isDeleted.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            isDeleted.TypeMapping = BoolTypeMapping.Default.Clone(
                comparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v),
                keyComparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v),
                providerValueComparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var key = runtimeEntityType.AddProperty(
                "Key",
                typeof(string),
                propertyInfo: typeof(Secret).GetProperty("Key", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Secret).GetField("<Key>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 512);
            key.SetGetter(
                string (Secret instance) => SecretUnsafeAccessors.Key(instance),
                bool (Secret instance) => SecretUnsafeAccessors.Key(instance) == null);
            key.SetSetter(
                Secret (Secret instance, string value) =>
                {
                    SecretUnsafeAccessors.Key(instance) = value;
                    return instance;
                });
            key.SetMaterializationSetter(
                Secret (Secret instance, string value) =>
                {
                    SecretUnsafeAccessors.Key(instance) = value;
                    return instance;
                });
            key.SetAccessors(
                string (IInternalEntry entry) => SecretUnsafeAccessors.Key(((Secret)(entry.Entity))),
                string (IInternalEntry entry) => SecretUnsafeAccessors.Key(((Secret)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(key, 4),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(key));
            key.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            key.TypeMapping = SqliteStringTypeMapping.Default;
            key.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(key));

            var tenantId = runtimeEntityType.AddProperty(
                "TenantId",
                typeof(Guid?),
                propertyInfo: typeof(Secret).GetProperty("TenantId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Secret).GetField("<TenantId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            tenantId.SetGetter(
                Guid? (Secret instance) => SecretUnsafeAccessors.TenantId(instance),
                bool (Secret instance) => !(SecretUnsafeAccessors.TenantId(instance).HasValue));
            tenantId.SetSetter(
                Secret (Secret instance, Guid? value) =>
                {
                    SecretUnsafeAccessors.TenantId(instance) = value;
                    return instance;
                });
            tenantId.SetMaterializationSetter(
                Secret (Secret instance, Guid? value) =>
                {
                    SecretUnsafeAccessors.TenantId(instance) = value;
                    return instance;
                });
            tenantId.SetAccessors(
                Guid? (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(5) ? entry.ReadStoreGeneratedValue<Guid?>(1) : (entry.FlaggedAsTemporary(5) && !(SecretUnsafeAccessors.TenantId(((Secret)(entry.Entity))).HasValue) ? entry.ReadTemporaryValue<Guid?>(1) : SecretUnsafeAccessors.TenantId(((Secret)(entry.Entity))))),
                Guid? (IInternalEntry entry) => SecretUnsafeAccessors.TenantId(((Secret)(entry.Entity))),
                Guid? (IInternalEntry entry) => entry.ReadOriginalValue<Guid?>(tenantId, 5),
                Guid? (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<Guid?>(tenantId, 1));
            tenantId.SetPropertyIndexes(
                index: 5,
                originalValueIndex: 5,
                shadowIndex: -1,
                relationshipIndex: 1,
                storeGenerationIndex: 1);
            tenantId.TypeMapping = SqliteGuidTypeMapping.Default;
            tenantId.SetCurrentValueComparer(new EntryCurrentValueComparer<Guid?>(tenantId));
            tenantId.SetComparer(new NullableValueComparer<Guid>(tenantId.TypeMapping.Comparer));
            tenantId.SetKeyComparer(new NullableValueComparer<Guid>(tenantId.TypeMapping.KeyComparer));

            var key0 = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key0);

            var index = runtimeEntityType.AddIndex(
                new[] { tenantId });

            var index0 = runtimeEntityType.AddIndex(
                new[] { key, tenantId },
                unique: true);
            index0.AddAnnotation("Relational:Filter", "IsDeleted = 0");

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("TenantId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.SetNull);

            var tenant = declaringEntityType.AddNavigation("Tenant",
                runtimeForeignKey,
                onDependent: true,
                typeof(Tenant),
                propertyInfo: typeof(Secret).GetProperty("Tenant", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Secret).GetField("<Tenant>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            tenant.SetGetter(
                Tenant (Secret instance) => SecretUnsafeAccessors.Tenant(instance),
                bool (Secret instance) => SecretUnsafeAccessors.Tenant(instance) == null);
            tenant.SetSetter(
                Secret (Secret instance, Tenant value) =>
                {
                    SecretUnsafeAccessors.Tenant(instance) = value;
                    return instance;
                });
            tenant.SetMaterializationSetter(
                Secret (Secret instance, Tenant value) =>
                {
                    SecretUnsafeAccessors.Tenant(instance) = value;
                    return instance;
                });
            tenant.SetAccessors(
                Tenant (IInternalEntry entry) => SecretUnsafeAccessors.Tenant(((Secret)(entry.Entity))),
                Tenant (IInternalEntry entry) => SecretUnsafeAccessors.Tenant(((Secret)(entry.Entity))),
                null,
                Tenant (IInternalEntry entry) => entry.GetCurrentValue<Tenant>(tenant));
            tenant.SetPropertyIndexes(
                index: 0,
                originalValueIndex: -1,
                shadowIndex: -1,
                relationshipIndex: 2,
                storeGenerationIndex: -1);
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var createdAtTicks = runtimeEntityType.FindProperty("CreatedAtTicks");
            var createdBy = runtimeEntityType.FindProperty("CreatedBy");
            var isDeleted = runtimeEntityType.FindProperty("IsDeleted");
            var key = runtimeEntityType.FindProperty("Key");
            var tenantId = runtimeEntityType.FindProperty("TenantId");
            var key0 = runtimeEntityType.FindKey(new[] { id });
            key0.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<Guid>(key0));
            key0.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<Guid>(key0));
            var tenant = runtimeEntityType.FindNavigation("Tenant");
            var versions = runtimeEntityType.FindNavigation("Versions");
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((Secret)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid, long, string, bool, string, Guid?>(((ValueComparer<Guid>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid>(id)), ((ValueComparer<long>)(((IProperty)createdAtTicks).GetValueComparer())).Snapshot(source.GetCurrentValue<long>(createdAtTicks)), (source.GetCurrentValue<string>(createdBy) == null ? null : ((ValueComparer<string>)(((IProperty)createdBy).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(createdBy))), ((ValueComparer<bool>)(((IProperty)isDeleted).GetValueComparer())).Snapshot(source.GetCurrentValue<bool>(isDeleted)), (source.GetCurrentValue<string>(key) == null ? null : ((ValueComparer<string>)(((IProperty)key).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(key))), (source.GetCurrentValue<Guid?>(tenantId) == null ? null : ((ValueComparer<Guid?>)(((IProperty)tenantId).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid?>(tenantId))))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<Guid, Guid?>(((ValueComparer<Guid>)(((IProperty)id).GetValueComparer())).Snapshot(default(Guid)), (default(Guid? ) == null ? null : ((ValueComparer<Guid?>)(((IProperty)tenantId).GetValueComparer())).Snapshot(default(Guid? )))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<Guid, Guid?>(default(Guid), default(Guid? )))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((Secret)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid, Guid?, object, object>(((ValueComparer<Guid>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<Guid>(id)), (source.GetCurrentValue<Guid?>(tenantId) == null ? null : ((ValueComparer<Guid?>)(((IProperty)tenantId).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<Guid?>(tenantId))), source.GetCurrentValue<Tenant>(tenant), SnapshotFactoryFactory.SnapshotCollection(source.GetCurrentValue<ICollection<SecretVersion>>(versions)))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 6,
                navigationCount: 2,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 6,
                shadowCount: 0,
                relationshipCount: 4,
                storeGeneratedCount: 2));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Secrets");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
