// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using GnOuGo.KeyVault.Core.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace GnOuGo.KeyVault.Core.Data.CompiledModels
{
    public static class SecretVersionUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref Guid Id(SecretVersion @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAtTicks>k__BackingField")]
        public static extern ref long CreatedAtTicks(SecretVersion @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedBy>k__BackingField")]
        public static extern ref string CreatedBy(SecretVersion @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EncryptedValue>k__BackingField")]
        public static extern ref string EncryptedValue(SecretVersion @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SecretId>k__BackingField")]
        public static extern ref Guid SecretId(SecretVersion @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Version>k__BackingField")]
        public static extern ref int Version(SecretVersion @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Secret>k__BackingField")]
        public static extern ref Secret Secret(SecretVersion @this);
    }
}
