// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using GnOuGo.KeyVault.Core.Models;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;

#pragma warning disable 219, 612, 618
#nullable disable

namespace GnOuGo.KeyVault.Core.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class TenantEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "GnOuGo.KeyVault.Core.Models.Tenant",
                typeof(Tenant),
                baseEntityType,
                propertyCount: 7,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(Tenant).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Tenant).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.SetGetter(
                Guid (Tenant instance) => TenantUnsafeAccessors.Id(instance),
                bool (Tenant instance) => TenantUnsafeAccessors.Id(instance) == new Guid("00000000-0000-0000-0000-000000000000"));
            id.SetSetter(
                Tenant (Tenant instance, Guid value) =>
                {
                    TenantUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                Tenant (Tenant instance, Guid value) =>
                {
                    TenantUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                Guid (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<Guid>(0) : (entry.FlaggedAsTemporary(0) && TenantUnsafeAccessors.Id(((Tenant)(entry.Entity))) == new Guid("00000000-0000-0000-0000-000000000000") ? entry.ReadTemporaryValue<Guid>(0) : TenantUnsafeAccessors.Id(((Tenant)(entry.Entity))))),
                Guid (IInternalEntry entry) => TenantUnsafeAccessors.Id(((Tenant)(entry.Entity))),
                Guid (IInternalEntry entry) => entry.ReadOriginalValue<Guid>(id, 0),
                Guid (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<Guid>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = SqliteGuidTypeMapping.Default;
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<Guid>(id));

            var createdAtTicks = runtimeEntityType.AddProperty(
                "CreatedAtTicks",
                typeof(long),
                propertyInfo: typeof(Tenant).GetProperty("CreatedAtTicks", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Tenant).GetField("<CreatedAtTicks>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            createdAtTicks.SetGetter(
                long (Tenant instance) => TenantUnsafeAccessors.CreatedAtTicks(instance),
                bool (Tenant instance) => TenantUnsafeAccessors.CreatedAtTicks(instance) == 0L);
            createdAtTicks.SetSetter(
                Tenant (Tenant instance, long value) =>
                {
                    TenantUnsafeAccessors.CreatedAtTicks(instance) = value;
                    return instance;
                });
            createdAtTicks.SetMaterializationSetter(
                Tenant (Tenant instance, long value) =>
                {
                    TenantUnsafeAccessors.CreatedAtTicks(instance) = value;
                    return instance;
                });
            createdAtTicks.SetAccessors(
                long (IInternalEntry entry) => TenantUnsafeAccessors.CreatedAtTicks(((Tenant)(entry.Entity))),
                long (IInternalEntry entry) => TenantUnsafeAccessors.CreatedAtTicks(((Tenant)(entry.Entity))),
                long (IInternalEntry entry) => entry.ReadOriginalValue<long>(createdAtTicks, 1),
                long (IInternalEntry entry) => entry.GetCurrentValue<long>(createdAtTicks));
            createdAtTicks.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            createdAtTicks.TypeMapping = LongTypeMapping.Default.Clone(
                comparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                keyComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                providerValueComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var createdBy = runtimeEntityType.AddProperty(
                "CreatedBy",
                typeof(string),
                propertyInfo: typeof(Tenant).GetProperty("CreatedBy", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Tenant).GetField("<CreatedBy>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 256);
            createdBy.SetGetter(
                string (Tenant instance) => TenantUnsafeAccessors.CreatedBy(instance),
                bool (Tenant instance) => TenantUnsafeAccessors.CreatedBy(instance) == null);
            createdBy.SetSetter(
                Tenant (Tenant instance, string value) =>
                {
                    TenantUnsafeAccessors.CreatedBy(instance) = value;
                    return instance;
                });
            createdBy.SetMaterializationSetter(
                Tenant (Tenant instance, string value) =>
                {
                    TenantUnsafeAccessors.CreatedBy(instance) = value;
                    return instance;
                });
            createdBy.SetAccessors(
                string (IInternalEntry entry) => TenantUnsafeAccessors.CreatedBy(((Tenant)(entry.Entity))),
                string (IInternalEntry entry) => TenantUnsafeAccessors.CreatedBy(((Tenant)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(createdBy, 2),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(createdBy));
            createdBy.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            createdBy.TypeMapping = SqliteStringTypeMapping.Default;

            var isDeleted = runtimeEntityType.AddProperty(
                "IsDeleted",
                typeof(bool),
                propertyInfo: typeof(Tenant).GetProperty("IsDeleted", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Tenant).GetField("<IsDeleted>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            isDeleted.SetGetter(
                bool (Tenant instance) => TenantUnsafeAccessors.IsDeleted(instance),
                bool (Tenant instance) => TenantUnsafeAccessors.IsDeleted(instance) == false);
            isDeleted.SetSetter(
                Tenant (Tenant instance, bool value) =>
                {
                    TenantUnsafeAccessors.IsDeleted(instance) = value;
                    return instance;
                });
            isDeleted.SetMaterializationSetter(
                Tenant (Tenant instance, bool value) =>
                {
                    TenantUnsafeAccessors.IsDeleted(instance) = value;
                    return instance;
                });
            isDeleted.SetAccessors(
                bool (IInternalEntry entry) => TenantUnsafeAccessors.IsDeleted(((Tenant)(entry.Entity))),
                bool (IInternalEntry entry) => TenantUnsafeAccessors.IsDeleted(((Tenant)(entry.Entity))),
                bool (IInternalEntry entry) => entry.ReadOriginalValue<bool>(isDeleted, 3),
                bool (IInternalEntry entry) => entry.GetCurrentValue<bool>(isDeleted));
            isDeleted.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            isDeleted.TypeMapping = BoolTypeMapping.Default.Clone(
                comparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v),
                keyComparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v),
                providerValueComparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var name = runtimeEntityType.AddProperty(
                "Name",
                typeof(string),
                propertyInfo: typeof(Tenant).GetProperty("Name", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Tenant).GetField("<Name>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 256);
            name.SetGetter(
                string (Tenant instance) => TenantUnsafeAccessors.Name(instance),
                bool (Tenant instance) => TenantUnsafeAccessors.Name(instance) == null);
            name.SetSetter(
                Tenant (Tenant instance, string value) =>
                {
                    TenantUnsafeAccessors.Name(instance) = value;
                    return instance;
                });
            name.SetMaterializationSetter(
                Tenant (Tenant instance, string value) =>
                {
                    TenantUnsafeAccessors.Name(instance) = value;
                    return instance;
                });
            name.SetAccessors(
                string (IInternalEntry entry) => TenantUnsafeAccessors.Name(((Tenant)(entry.Entity))),
                string (IInternalEntry entry) => TenantUnsafeAccessors.Name(((Tenant)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(name, 4),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(name));
            name.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            name.TypeMapping = SqliteStringTypeMapping.Default;
            name.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(name));

            var privateKeyPem = runtimeEntityType.AddProperty(
                "PrivateKeyPem",
                typeof(string),
                propertyInfo: typeof(Tenant).GetProperty("PrivateKeyPem", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Tenant).GetField("<PrivateKeyPem>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            privateKeyPem.SetGetter(
                string (Tenant instance) => TenantUnsafeAccessors.PrivateKeyPem(instance),
                bool (Tenant instance) => TenantUnsafeAccessors.PrivateKeyPem(instance) == null);
            privateKeyPem.SetSetter(
                Tenant (Tenant instance, string value) =>
                {
                    TenantUnsafeAccessors.PrivateKeyPem(instance) = value;
                    return instance;
                });
            privateKeyPem.SetMaterializationSetter(
                Tenant (Tenant instance, string value) =>
                {
                    TenantUnsafeAccessors.PrivateKeyPem(instance) = value;
                    return instance;
                });
            privateKeyPem.SetAccessors(
                string (IInternalEntry entry) => TenantUnsafeAccessors.PrivateKeyPem(((Tenant)(entry.Entity))),
                string (IInternalEntry entry) => TenantUnsafeAccessors.PrivateKeyPem(((Tenant)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(privateKeyPem, 5),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(privateKeyPem));
            privateKeyPem.SetPropertyIndexes(
                index: 5,
                originalValueIndex: 5,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            privateKeyPem.TypeMapping = SqliteStringTypeMapping.Default;

            var publicKeyPem = runtimeEntityType.AddProperty(
                "PublicKeyPem",
                typeof(string),
                propertyInfo: typeof(Tenant).GetProperty("PublicKeyPem", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Tenant).GetField("<PublicKeyPem>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            publicKeyPem.SetGetter(
                string (Tenant instance) => TenantUnsafeAccessors.PublicKeyPem(instance),
                bool (Tenant instance) => TenantUnsafeAccessors.PublicKeyPem(instance) == null);
            publicKeyPem.SetSetter(
                Tenant (Tenant instance, string value) =>
                {
                    TenantUnsafeAccessors.PublicKeyPem(instance) = value;
                    return instance;
                });
            publicKeyPem.SetMaterializationSetter(
                Tenant (Tenant instance, string value) =>
                {
                    TenantUnsafeAccessors.PublicKeyPem(instance) = value;
                    return instance;
                });
            publicKeyPem.SetAccessors(
                string (IInternalEntry entry) => TenantUnsafeAccessors.PublicKeyPem(((Tenant)(entry.Entity))),
                string (IInternalEntry entry) => TenantUnsafeAccessors.PublicKeyPem(((Tenant)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(publicKeyPem, 6),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(publicKeyPem));
            publicKeyPem.SetPropertyIndexes(
                index: 6,
                originalValueIndex: 6,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            publicKeyPem.TypeMapping = SqliteStringTypeMapping.Default;

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { name },
                unique: true);
            index.AddAnnotation("Relational:Filter", "IsDeleted = 0");

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var createdAtTicks = runtimeEntityType.FindProperty("CreatedAtTicks");
            var createdBy = runtimeEntityType.FindProperty("CreatedBy");
            var isDeleted = runtimeEntityType.FindProperty("IsDeleted");
            var name = runtimeEntityType.FindProperty("Name");
            var privateKeyPem = runtimeEntityType.FindProperty("PrivateKeyPem");
            var publicKeyPem = runtimeEntityType.FindProperty("PublicKeyPem");
            var key = runtimeEntityType.FindKey(new[] { id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<Guid>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<Guid>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((Tenant)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid, long, string, bool, string, string, string>(((ValueComparer<Guid>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid>(id)), ((ValueComparer<long>)(((IProperty)createdAtTicks).GetValueComparer())).Snapshot(source.GetCurrentValue<long>(createdAtTicks)), (source.GetCurrentValue<string>(createdBy) == null ? null : ((ValueComparer<string>)(((IProperty)createdBy).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(createdBy))), ((ValueComparer<bool>)(((IProperty)isDeleted).GetValueComparer())).Snapshot(source.GetCurrentValue<bool>(isDeleted)), (source.GetCurrentValue<string>(name) == null ? null : ((ValueComparer<string>)(((IProperty)name).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(name))), (source.GetCurrentValue<string>(privateKeyPem) == null ? null : ((ValueComparer<string>)(((IProperty)privateKeyPem).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(privateKeyPem))), (source.GetCurrentValue<string>(publicKeyPem) == null ? null : ((ValueComparer<string>)(((IProperty)publicKeyPem).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(publicKeyPem))))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<Guid>(((ValueComparer<Guid>)(((IProperty)id).GetValueComparer())).Snapshot(default(Guid))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<Guid>(default(Guid)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((Tenant)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid>(((ValueComparer<Guid>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<Guid>(id)))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 7,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 7,
                shadowCount: 0,
                relationshipCount: 1,
                storeGeneratedCount: 1));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Tenants");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
