// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using GnOuGo.KeyVault.Core.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace GnOuGo.KeyVault.Core.Data.CompiledModels
{
    public static class TenantUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref Guid Id(Tenant @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAtTicks>k__BackingField")]
        public static extern ref long CreatedAtTicks(Tenant @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedBy>k__BackingField")]
        public static extern ref string CreatedBy(Tenant @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsDeleted>k__BackingField")]
        public static extern ref bool IsDeleted(Tenant @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
        public static extern ref string Name(Tenant @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PrivateKeyPem>k__BackingField")]
        public static extern ref string PrivateKeyPem(Tenant @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PublicKeyPem>k__BackingField")]
        public static extern ref string PublicKeyPem(Tenant @this);
    }
}
